/* --- å®Œæ•´æ–‡ä»¶ä»£ç  --- */
// Source/XiaoBinDaTianXia/Private/Soldier/XBSoldierCharacter.cpp

/**
 * @file XBSoldierCharacter.cpp
 * @brief å£«å…µActorå®ç°
 * 
 * @note ğŸ”§ ä¿®æ”¹è®°å½•:
 *       1. ä½¿ç”¨çƒå½¢æ£€æµ‹æ›¿ä»£å…¨é‡Actoræœç´¢
 *       2. ä»æ•°æ®è¡¨è¯»å–æ‰€æœ‰é…ç½®å€¼ï¼ˆæ¶ˆé™¤ç¡¬ç¼–ç ï¼‰
 *       3. ä½¿ç”¨é¡¹ç›®ä¸“ç”¨æ—¥å¿—ç±»åˆ«
 *       4. ä½¿ç”¨é€šç”¨å‡½æ•°åº“è¿›è¡Œé˜µè¥åˆ¤æ–­
 */

#include "Soldier/XBSoldierCharacter.h"
#include "Utils/XBLogCategories.h"
#include "Utils/XBBlueprintFunctionLibrary.h"
#include "Components/CapsuleComponent.h"
#include "Components/SkeletalMeshComponent.h"
#include "Soldier/Component/XBSoldierFollowComponent.h"
#include "Character/XBCharacterBase.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "AIController.h"
#include "AI/XBSoldierAIController.h"
#include "BehaviorTree/BehaviorTree.h"
#include "BehaviorTree/BlackboardComponent.h"
#include "Engine/DataTable.h"
#include "Animation/AnimInstance.h"
#include "TimerManager.h"
#include "Soldier/Component/XBSoldierDebugComponent.h"

AXBSoldierCharacter::AXBSoldierCharacter()
{
    PrimaryActorTick.bCanEverTick = true;
    PrimaryActorTick.bStartWithTickEnabled = false;

    if (UCapsuleComponent* Capsule = GetCapsuleComponent())
    {
        Capsule->InitCapsuleSize(34.0f, 88.0f);
        Capsule->SetCollisionProfileName(TEXT("Pawn"));
    }

    if (USkeletalMeshComponent* MeshComp = GetMesh())
    {
        MeshComp->SetRelativeLocation(FVector(0.0f, 0.0f, -88.0f));
    }

    FollowComponent = CreateDefaultSubobject<UXBSoldierFollowComponent>(TEXT("FollowComponent"));
    // âœ¨ æ–°å¢ - åˆ›å»ºè°ƒè¯•ç»„ä»¶
    DebugComponent = CreateDefaultSubobject<UXBSoldierDebugComponent>(TEXT("DebugComponent"));
    
    if (UCharacterMovementComponent* MovementComp = GetCharacterMovement())
    {
        MovementComp->bOrientRotationToMovement = true;
        MovementComp->RotationRate = FRotator(0.0f, 360.0f, 0.0f);
        MovementComp->MaxWalkSpeed = 400.0f;
        MovementComp->BrakingDecelerationWalking = 2000.0f;
        MovementComp->SetComponentTickEnabled(false);
    }

    AutoPossessAI = EAutoPossessAI::Disabled;
    AIControllerClass = nullptr;
}

void AXBSoldierCharacter::PostInitializeComponents()
{
    Super::PostInitializeComponents();
    
    bComponentsInitialized = true;
    
    UCapsuleComponent* Capsule = GetCapsuleComponent();
    if (Capsule)
    {
        FTransform CapsuleTransform = Capsule->GetComponentTransform();
        FVector Scale = CapsuleTransform.GetScale3D();
        
        if (Scale.IsNearlyZero() || Scale.ContainsNaN())
        {
            UE_LOG(LogXBSoldier, Warning, TEXT("å£«å…µ %s: Capsule Scale æ— æ•ˆ (%s)ï¼Œä¿®æ­£ä¸º (1,1,1)"), 
                *GetName(), *Scale.ToString());
            Capsule->SetWorldScale3D(FVector::OneVector);
        }
    }
    else
    {
        UE_LOG(LogXBSoldier, Error, TEXT("å£«å…µ %s: CapsuleComponent ä¸ºç©º!"), *GetName());
    }
    
    UCharacterMovementComponent* MoveComp = GetCharacterMovement();
    if (MoveComp)
    {
        if (!MoveComp->UpdatedComponent)
        {
            UE_LOG(LogXBSoldier, Warning, TEXT("å£«å…µ %s: MovementComponent çš„ UpdatedComponent ä¸ºç©º"), *GetName());
            MoveComp->SetUpdatedComponent(Capsule);
        }
    }
    else
    {
        UE_LOG(LogXBSoldier, Error, TEXT("å£«å…µ %s: CharacterMovementComponent ä¸ºç©º!"), *GetName());
    }
    
    UE_LOG(LogXBSoldier, Log, TEXT("å£«å…µ %s: PostInitializeComponents å®Œæˆ"), *GetName());
}

void AXBSoldierCharacter::BeginPlay()
{
    Super::BeginPlay();

    if (bInitializedFromDataTable)
    {
        CurrentHealth = CachedTableRow.MaxHealth;
    }
    else
    {
        CurrentHealth = SoldierConfig.MaxHealth;
    }
    
    GetWorldTimerManager().SetTimerForNextTick([this]()
    {
        EnableMovementAndTick();
    });

    UE_LOG(LogXBSoldier, Log, TEXT("å£«å…µ %s BeginPlay - é˜µè¥: %d, çŠ¶æ€: %d"), 
        *GetName(), static_cast<int32>(Faction), static_cast<int32>(CurrentState));
}

void AXBSoldierCharacter::EnableMovementAndTick()
{
    if (!IsValid(this) || IsPendingKillPending())
    {
        return;
    }
    
    UCapsuleComponent* Capsule = GetCapsuleComponent();
    UCharacterMovementComponent* MoveComp = GetCharacterMovement();
    
    if (!Capsule || !MoveComp)
    {
        UE_LOG(LogXBSoldier, Error, TEXT("å£«å…µ %s: ç»„ä»¶æ— æ•ˆï¼Œæ— æ³•å¯ç”¨ç§»åŠ¨"), *GetName());
        return;
    }
    
    FTransform CapsuleTransform = Capsule->GetComponentTransform();
    if (!CapsuleTransform.IsValid())
    {
        UE_LOG(LogXBSoldier, Error, TEXT("å£«å…µ %s: Capsule Transform æ— æ•ˆ"), *GetName());
        return;
    }
    
    MoveComp->SetComponentTickEnabled(true);
    SetActorTickEnabled(true);
    
    UE_LOG(LogXBSoldier, Log, TEXT("å£«å…µ %s: ç§»åŠ¨ç»„ä»¶å’ŒTickå·²å¯ç”¨"), *GetName());
}

void AXBSoldierCharacter::Tick(float DeltaTime)
{
    Super::Tick(DeltaTime);

    if (AttackCooldownTimer > 0.0f)
    {
        AttackCooldownTimer -= DeltaTime;
    }

    if (!bIsRecruited)
    {
        return;
    }

    AAIController* AICtrl = Cast<AAIController>(GetController());
    if (!BehaviorTreeAsset || !AICtrl)
    {
        switch (CurrentState)
        {
        case EXBSoldierState::Following:
            UpdateFollowing(DeltaTime);
            break;
        case EXBSoldierState::Combat:
            UpdateCombat(DeltaTime);
            break;
        case EXBSoldierState::Returning:
            UpdateReturning(DeltaTime);
            break;
        default:
            break;
        }
    }
}

// ==================== é…ç½®è®¿é—®æ–¹æ³•ï¼ˆâœ¨ æ–°å¢ï¼‰ ====================

float AXBSoldierCharacter::GetVisionRange() const
{
    if (bInitializedFromDataTable)
    {
        return CachedTableRow.GetVisionRange();
    }
    return 800.0f; // é»˜è®¤å€¼
}

float AXBSoldierCharacter::GetDisengageDistance() const
{
    if (bInitializedFromDataTable)
    {
        return CachedTableRow.AIConfig.DisengageDistance;
    }
    return 1000.0f; // é»˜è®¤å€¼
}

float AXBSoldierCharacter::GetReturnDelay() const
{
    if (bInitializedFromDataTable)
    {
        return CachedTableRow.AIConfig.ReturnDelay;
    }
    return 2.0f; // é»˜è®¤å€¼
}

float AXBSoldierCharacter::GetArrivalThreshold() const
{
    if (bInitializedFromDataTable)
    {
        return CachedTableRow.AIConfig.ArrivalThreshold;
    }
    return 50.0f; // é»˜è®¤å€¼
}

// ==================== æ‹›å‹Ÿç³»ç»Ÿå®ç° ====================

bool AXBSoldierCharacter::CanBeRecruited() const
{
    if (bIsRecruited)
    {
        return false;
    }
    
    if (Faction != EXBFaction::Neutral)
    {
        return false;
    }
    
    if (CurrentState != EXBSoldierState::Idle)
    {
        return false;
    }
    
    if (CurrentHealth <= 0.0f)
    {
        return false;
    }
    
    if (!bComponentsInitialized)
    {
        return false;
    }
    
    return true;
}

/**
 * @brief è¢«æ‹›å‹Ÿå›è°ƒ
 * @note ğŸ”§ ä¿®æ”¹ - æ‹›å‹Ÿåç«‹å³ä¼ é€åˆ°ç¼–é˜Ÿä½ç½®
 */
void AXBSoldierCharacter::OnRecruited(AActor* NewLeader, int32 SlotIndex)
{
    if (!NewLeader)
    {
        UE_LOG(LogXBSoldier, Warning, TEXT("å£«å…µ %s: æ‹›å‹Ÿå¤±è´¥ - å°†é¢†ä¸ºç©º"), *GetName());
        return;
    }
    
    if (bIsRecruited)
    {
        UE_LOG(LogXBSoldier, Warning, TEXT("å£«å…µ %s: å·²è¢«æ‹›å‹Ÿï¼Œå¿½ç•¥é‡å¤æ‹›å‹Ÿ"), *GetName());
        return;
    }
    
    if (!bComponentsInitialized)
    {
        UE_LOG(LogXBSoldier, Warning, TEXT("å£«å…µ %s: ç»„ä»¶æœªåˆå§‹åŒ–ï¼Œå»¶è¿Ÿæ‹›å‹Ÿ"), *GetName());
        FTimerHandle TempHandle;
        GetWorldTimerManager().SetTimer(TempHandle, [this, NewLeader, SlotIndex]()
        {
            OnRecruited(NewLeader, SlotIndex);
        }, 0.1f, false);
        return;
    }
    
    UE_LOG(LogXBSoldier, Log, TEXT("å£«å…µ %s: è¢«å°†é¢† %s æ‹›å‹Ÿï¼Œæ§½ä½: %d"), 
        *GetName(), *NewLeader->GetName(), SlotIndex);
    
    // æ ‡è®°ä¸ºå·²æ‹›å‹Ÿ
    bIsRecruited = true;
    
    // è®¾ç½®è·Ÿéšç›®æ ‡
    FollowTarget = NewLeader;
    FormationSlotIndex = SlotIndex;
    
    // æ›´æ–°è·Ÿéšç»„ä»¶
    if (FollowComponent)
    {
        FollowComponent->SetFollowTarget(NewLeader);
        FollowComponent->SetFormationSlotIndex(SlotIndex);
        
        // ğŸ”§ ä¿®æ”¹ - ä½¿ç”¨æ‹›å‹Ÿè¿‡æ¸¡æ¨¡å¼ï¼ˆç§»åŠ¨ç»„ä»¶é©±åŠ¨çš„å¹³æ»‘ç§»åŠ¨ï¼‰
        FollowComponent->StartRecruitTransition();
    }
    
    // æ›´æ–°é˜µè¥ä¸ºå°†é¢†é˜µè¥
    if (AXBCharacterBase* LeaderChar = Cast<AXBCharacterBase>(NewLeader))
    {
        Faction = LeaderChar->GetFaction();
    }
    
    // è®¾ç½®ä¸ºè·ŸéšçŠ¶æ€
    SetSoldierState(EXBSoldierState::Following);
    
    // å»¶è¿Ÿå¯åŠ¨AIæ§åˆ¶å™¨
    GetWorldTimerManager().SetTimer(
        DelayedAIStartTimerHandle,
        this,
        &AXBSoldierCharacter::SpawnAndPossessAIController,
        0.3f,
        false
    );
    
    // å¹¿æ’­æ‹›å‹Ÿäº‹ä»¶
    OnSoldierRecruited.Broadcast(this, NewLeader);
}

void AXBSoldierCharacter::SpawnAndPossessAIController()
{
    if (!IsValid(this) || IsPendingKillPending())
    {
        UE_LOG(LogXBSoldier, Warning, TEXT("SpawnAndPossessAIController: å£«å…µå·²æ— æ•ˆ"));
        return;
    }
    
    UCapsuleComponent* Capsule = GetCapsuleComponent();
    UCharacterMovementComponent* MoveComp = GetCharacterMovement();
    
    if (!Capsule || !MoveComp)
    {
        UE_LOG(LogXBSoldier, Error, TEXT("å£«å…µ %s: ç»„ä»¶æ— æ•ˆï¼Œæ— æ³•å¯åŠ¨AI"), *GetName());
        return;
    }
    
    FTransform CapsuleTransform = Capsule->GetComponentTransform();
    if (!CapsuleTransform.IsValid())
    {
        UE_LOG(LogXBSoldier, Warning, TEXT("å£«å…µ %s: Transform æ— æ•ˆï¼Œå†æ¬¡å»¶è¿Ÿ"), *GetName());
        GetWorldTimerManager().SetTimer(
            DelayedAIStartTimerHandle,
            this,
            &AXBSoldierCharacter::SpawnAndPossessAIController,
            0.1f,
            false
        );
        return;
    }
    
    if (GetController())
    {
        UE_LOG(LogXBSoldier, Log, TEXT("å£«å…µ %s: å·²æœ‰æ§åˆ¶å™¨ï¼Œç›´æ¥åˆå§‹åŒ–AI"), *GetName());
        InitializeAI();
        return;
    }
    
    UWorld* World = GetWorld();
    if (!World)
    {
        UE_LOG(LogXBSoldier, Error, TEXT("å£«å…µ %s: æ— æ³•è·å–World"), *GetName());
        return;
    }
    
    UClass* ControllerClassToUse = nullptr;
    if (SoldierAIControllerClass)
    {
        ControllerClassToUse = SoldierAIControllerClass.Get();
    }
    else
    {
        ControllerClassToUse = AXBSoldierAIController::StaticClass();
    }
    
    if (!ControllerClassToUse)
    {
        UE_LOG(LogXBSoldier, Error, TEXT("å£«å…µ %s: AIæ§åˆ¶å™¨ç±»æ— æ•ˆ"), *GetName());
        return;
    }
    
    FActorSpawnParameters SpawnParams;
    SpawnParams.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AlwaysSpawn;
    
    AAIController* NewController = World->SpawnActor<AAIController>(
        ControllerClassToUse,
        GetActorLocation(),
        GetActorRotation(),
        SpawnParams
    );
    
    if (NewController)
    {
        NewController->Possess(this);
        
        UE_LOG(LogXBSoldier, Log, TEXT("å£«å…µ %s: AIæ§åˆ¶å™¨åˆ›å»ºæˆåŠŸ - %s"), 
            *GetName(), *NewController->GetName());
        
        InitializeAI();
    }
    else
    {
        UE_LOG(LogXBSoldier, Error, TEXT("å£«å…µ %s: æ— æ³•åˆ›å»ºAIæ§åˆ¶å™¨"), *GetName());
    }
}

void AXBSoldierCharacter::InitializeAI()
{
    AAIController* AICtrl = Cast<AAIController>(GetController());
    if (!AICtrl)
    {
        UE_LOG(LogXBSoldier, Warning, TEXT("å£«å…µ %s: InitializeAI - æ— AIæ§åˆ¶å™¨"), *GetName());
        return;
    }
    
    if (BehaviorTreeAsset)
    {
        AICtrl->RunBehaviorTree(BehaviorTreeAsset);
        
        if (UBlackboardComponent* BBComp = AICtrl->GetBlackboardComponent())
        {
            BBComp->SetValueAsObject(TEXT("Self"), this);
            BBComp->SetValueAsObject(TEXT("Leader"), FollowTarget.Get());
            // ğŸ”§ ä¿®æ”¹ - ä½¿ç”¨ Int ç±»å‹
            BBComp->SetValueAsInt(TEXT("SoldierState"), static_cast<int32>(CurrentState));
            BBComp->SetValueAsInt(TEXT("FormationSlot"), FormationSlotIndex);
            
            float AttackRange = bInitializedFromDataTable ? CachedTableRow.AttackRange : SoldierConfig.AttackRange;
            BBComp->SetValueAsFloat(TEXT("AttackRange"), AttackRange);
            BBComp->SetValueAsFloat(TEXT("VisionRange"), GetVisionRange());
            BBComp->SetValueAsFloat(TEXT("DetectionRange"), GetVisionRange());
            BBComp->SetValueAsBool(TEXT("IsAtFormation"), true);
            BBComp->SetValueAsBool(TEXT("CanAttack"), true);
        }
        
        UE_LOG(LogXBSoldier, Log, TEXT("å£«å…µ %s: è¡Œä¸ºæ ‘å¯åŠ¨æˆåŠŸ"), *GetName());
    }
    else
    {
        UE_LOG(LogXBSoldier, Log, TEXT("å£«å…µ %s: æ— è¡Œä¸ºæ ‘ï¼Œä½¿ç”¨çŠ¶æ€æœº"), *GetName());
    }
}

// ==================== åˆå§‹åŒ–å®ç° ====================

void AXBSoldierCharacter::InitializeFromDataTable(UDataTable* DataTable, FName RowName, EXBFaction InFaction)
{
    if (!DataTable)
    {
        UE_LOG(LogXBSoldier, Error, TEXT("å£«å…µåˆå§‹åŒ–å¤±è´¥: æ•°æ®è¡¨ä¸ºç©º"));
        return;
    }

    if (RowName.IsNone())
    {
        UE_LOG(LogXBSoldier, Error, TEXT("å£«å…µåˆå§‹åŒ–å¤±è´¥: è¡Œåä¸ºç©º"));
        return;
    }

    FXBSoldierTableRow* Row = DataTable->FindRow<FXBSoldierTableRow>(RowName, TEXT("AXBSoldierCharacter::InitializeFromDataTable"));
    if (!Row)
    {
        UE_LOG(LogXBSoldier, Error, TEXT("å£«å…µåˆå§‹åŒ–å¤±è´¥: æ‰¾ä¸åˆ°è¡Œ '%s'"), *RowName.ToString());
        return;
    }

    CachedTableRow = *Row;
    bInitializedFromDataTable = true;

    SoldierType = Row->SoldierType;
    Faction = InFaction;
    CurrentHealth = Row->MaxHealth;

    if (UCharacterMovementComponent* MovementComp = GetCharacterMovement())
    {
        MovementComp->MaxWalkSpeed = Row->MoveSpeed;
        MovementComp->RotationRate = FRotator(0.0f, Row->RotationSpeed, 0.0f);
    }

    if (FollowComponent)
    {
        FollowComponent->SetFollowSpeed(Row->MoveSpeed);
        FollowComponent->SetFollowInterpSpeed(Row->FollowInterpSpeed);
    }

    if (!Row->AIConfig.BehaviorTree.IsNull())
    {
        BehaviorTreeAsset = Row->AIConfig.BehaviorTree.LoadSynchronous();
    }

    ApplyVisualConfig();

    SoldierConfig.SoldierType = Row->SoldierType;
    SoldierConfig.MaxHealth = Row->MaxHealth;
    SoldierConfig.BaseDamage = Row->BaseDamage;
    SoldierConfig.AttackRange = Row->AttackRange;
    SoldierConfig.AttackInterval = Row->AttackInterval;
    SoldierConfig.MoveSpeed = Row->MoveSpeed;
    SoldierConfig.FollowInterpSpeed = Row->FollowInterpSpeed;
    SoldierConfig.HealthBonusToLeader = Row->HealthBonusToLeader;
    SoldierConfig.DamageBonusToLeader = Row->DamageBonusToLeader;

    UE_LOG(LogXBSoldier, Log, TEXT("å£«å…µä»æ•°æ®è¡¨åˆå§‹åŒ–: %s, ç±»å‹=%d, è¡€é‡=%.1f, è§†é‡=%.0f"), 
        *RowName.ToString(), static_cast<int32>(SoldierType), CurrentHealth, GetVisionRange());
}

void AXBSoldierCharacter::InitializeSoldier(const FXBSoldierConfig& InConfig, EXBFaction InFaction)
{
    SoldierConfig = InConfig;
    SoldierType = InConfig.SoldierType;
    Faction = InFaction;
    CurrentHealth = InConfig.MaxHealth;

    if (UCharacterMovementComponent* MovementComp = GetCharacterMovement())
    {
        MovementComp->MaxWalkSpeed = InConfig.MoveSpeed;
    }

    if (FollowComponent)
    {
        FollowComponent->SetFollowSpeed(InConfig.MoveSpeed);
        FollowComponent->SetFollowInterpSpeed(InConfig.FollowInterpSpeed);
    }

    if (InConfig.SoldierMesh)
    {
        GetMesh()->SetSkeletalMesh(InConfig.SoldierMesh);
    }

    UE_LOG(LogXBSoldier, Log, TEXT("å£«å…µåˆå§‹åŒ–: Type=%d, Health=%.1f"), 
        static_cast<int32>(SoldierType), CurrentHealth);
}

void AXBSoldierCharacter::ApplyVisualConfig()
{
    if (!bInitializedFromDataTable)
    {
        return;
    }

    if (!CachedTableRow.VisualConfig.SkeletalMesh.IsNull())
    {
        USkeletalMesh* LoadedMesh = CachedTableRow.VisualConfig.SkeletalMesh.LoadSynchronous();
        if (LoadedMesh)
        {
            GetMesh()->SetSkeletalMesh(LoadedMesh);
        }
    }

    if (CachedTableRow.VisualConfig.AnimClass)
    {
        GetMesh()->SetAnimInstanceClass(CachedTableRow.VisualConfig.AnimClass);
    }

    SetActorScale3D(FVector(CachedTableRow.VisualConfig.MeshScale));
}

// ==================== AIç³»ç»Ÿå®ç°ï¼ˆğŸ”§ ä¿®æ”¹ - ä½¿ç”¨çƒå½¢æ£€æµ‹ï¼‰ ====================

/**
 * @brief å¯»æ‰¾æœ€è¿‘çš„æ•Œäºº
 * @return æœ€è¿‘çš„æ•ŒäººActor
 * @note ğŸ”§ ä¿®æ”¹ - ä½¿ç”¨é€šç”¨å‡½æ•°åº“çš„çƒå½¢æ£€æµ‹æ›¿ä»£å…¨é‡Actoræœç´¢
 */
AActor* AXBSoldierCharacter::FindNearestEnemy() const
{
    if (!bIsRecruited)
    {
        return nullptr;
    }

    // ğŸ”§ ä¿®æ”¹ - ä»æ•°æ®è¡¨è¯»å–è§†é‡èŒƒå›´
    float VisionRange = GetVisionRange();

    // ğŸ”§ ä¿®æ”¹ - ä½¿ç”¨é€šç”¨å‡½æ•°åº“çš„çƒå½¢æ£€æµ‹
    return UXBBlueprintFunctionLibrary::FindNearestEnemy(
        this,                       // WorldContext
        GetActorLocation(),         // Origin
        VisionRange,                // Radius
        Faction,                    // SourceFaction
        true                        // bIgnoreDead
    );
}

/**
 * @brief æ£€æŸ¥å‘¨è¾¹æ˜¯å¦æœ‰æ•Œäºº
 * @param Radius æ£€æµ‹åŠå¾„
 * @return æ˜¯å¦æœ‰æ•Œäºº
 * @note ğŸ”§ ä¿®æ”¹ - ä½¿ç”¨é€šç”¨å‡½æ•°åº“çš„çƒå½¢æ£€æµ‹
 */
bool AXBSoldierCharacter::HasEnemiesInRadius(float Radius) const
{
    FXBDetectionResult Result;
    return UXBBlueprintFunctionLibrary::DetectEnemiesInRadius(
        this,               // WorldContext
        GetActorLocation(), // Origin
        Radius,             // Radius
        Faction,            // SourceFaction
        true,               // bIgnoreDead
        Result              // OutResult
    );
}

float AXBSoldierCharacter::GetDistanceToTarget(AActor* Target) const
{
    if (!Target || !IsValid(Target))
    {
        return MAX_FLT;
    }
    return FVector::Dist(GetActorLocation(), Target->GetActorLocation());
}

bool AXBSoldierCharacter::IsInAttackRange(AActor* Target) const
{
    if (!Target || !IsValid(Target))
    {
        return false;
    }

    float AttackRange = bInitializedFromDataTable ? CachedTableRow.AttackRange : SoldierConfig.AttackRange;
    return GetDistanceToTarget(Target) <= AttackRange;
}

/**
 * @brief æ£€æŸ¥æ˜¯å¦åº”è¯¥è„±ç¦»æˆ˜æ–—
 * @return trueè¡¨ç¤ºåº”è¯¥è¿”å›é˜Ÿåˆ—
 * @note ğŸ”§ ä¿®æ”¹ - ä»æ•°æ®è¡¨è¯»å–é…ç½®
 */
bool AXBSoldierCharacter::ShouldDisengage() const
{
    // ğŸ”§ ä¿®æ”¹ - ä»æ•°æ®è¡¨è¯»å–è„±ç¦»è·ç¦»
    float DisengageDistance = GetDisengageDistance();

    // æ¡ä»¶1ï¼šè·ç¦»å°†é¢†è¿‡è¿œ
    if (FollowTarget.IsValid())
    {
        AActor* Leader = FollowTarget.Get();
        if (Leader && IsValid(Leader))
        {
            float DistToLeader = FVector::Dist(GetActorLocation(), Leader->GetActorLocation());
            if (DistToLeader > DisengageDistance)
            {
                UE_LOG(LogXBSoldier, Verbose, TEXT("å£«å…µ %s è·ç¦»å°†é¢†è¿‡è¿œ: %.0f > %.0f"), 
                    *GetName(), DistToLeader, DisengageDistance);
                return true;
            }
        }
    }

    // ğŸ”§ ä¿®æ”¹ - ä»æ•°æ®è¡¨è¯»å–è§†é‡èŒƒå›´å’Œè¿”å›å»¶è¿Ÿ
    float VisionRange = GetVisionRange();
    float ReturnDelay = GetReturnDelay();

    // æ¡ä»¶2ï¼šå‘¨è¾¹æ— æ•Œäººä¸”è¶…è¿‡è¿”å›å»¶è¿Ÿ
    if (!HasEnemiesInRadius(VisionRange))
    {
        float TimeSinceLastEnemy = GetWorld()->GetTimeSeconds() - LastEnemySeenTime;
        if (TimeSinceLastEnemy > ReturnDelay)
        {
            UE_LOG(LogXBSoldier, Verbose, TEXT("å£«å…µ %s å‘¨è¾¹æ— æ•Œäººï¼Œè¿”å›é˜Ÿåˆ—"), *GetName());
            return true;
        }
    }

    return false;
}


/**
 * @brief è¿”å›é˜Ÿåˆ—
 * @note ğŸ”§ ä¿®æ”¹ - ä½¿ç”¨è·Ÿéšç»„ä»¶ä¼ é€å›ç¼–é˜Ÿä½ç½®
 */
void AXBSoldierCharacter::ReturnToFormation()
{
    CurrentAttackTarget = nullptr;
    
    // ğŸ”§ ä¿®æ”¹ - ç›´æ¥ä¼ é€å›ç¼–é˜Ÿä½ç½®
    if (FollowComponent)
    {
        FollowComponent->ExitCombatMode();
    }
    
    // åœæ­¢AIç§»åŠ¨
    if (AAIController* AICtrl = Cast<AAIController>(GetController()))
    {
        AICtrl->StopMovement();
    }
    
    SetSoldierState(EXBSoldierState::Following);

    UE_LOG(LogXBSoldier, Log, TEXT("å£«å…µ %s ä¼ é€å›é˜Ÿåˆ—"), *GetName());
}

bool AXBSoldierCharacter::ShouldRetreat() const
{
    if (SoldierType != EXBSoldierType::Archer)
    {
        return false;
    }

    if (!CurrentAttackTarget.IsValid())
    {
        return false;
    }

    if (!bInitializedFromDataTable)
    {
        return false;
    }

    float DistToTarget = GetDistanceToTarget(CurrentAttackTarget.Get());
    return DistToTarget < CachedTableRow.ArcherConfig.MinAttackDistance;
}

void AXBSoldierCharacter::RetreatFromTarget(AActor* Target)
{
    if (!Target || !IsValid(Target) || !bInitializedFromDataTable)
    {
        return;
    }

    FVector RetreatDirection = (GetActorLocation() - Target->GetActorLocation()).GetSafeNormal2D();
    float RetreatDistance = CachedTableRow.ArcherConfig.RetreatDistance;
    FVector RetreatTarget = GetActorLocation() + RetreatDirection * RetreatDistance;

    if (AAIController* AICtrl = Cast<AAIController>(GetController()))
    {
        AICtrl->MoveToLocation(RetreatTarget, 10.0f, true, true, true, true);
    }

    UE_LOG(LogXBSoldier, Verbose, TEXT("å¼“æ‰‹ %s åæ’¤ï¼Œç›®æ ‡è·ç¦»: %.0f"), 
        *GetName(), GetDistanceToTarget(Target));
}

FVector AXBSoldierCharacter::CalculateAvoidanceDirection(const FVector& DesiredDirection)
{
    // ğŸ”§ ä¿®æ”¹ - ä»æ•°æ®è¡¨è¯»å–é¿éšœé…ç½®
    float AvoidanceRadius = bInitializedFromDataTable ? 
        CachedTableRow.AIConfig.AvoidanceRadius : 100.0f;
    float AvoidanceWeight = bInitializedFromDataTable ?
        CachedTableRow.AIConfig.AvoidanceWeight : 0.3f;

    if (AvoidanceRadius <= 0.0f)
    {
        return DesiredDirection;
    }

    FVector AvoidanceForce = FVector::ZeroVector;
    FVector MyLocation = GetActorLocation();

    // ğŸ”§ ä¿®æ”¹ - ä½¿ç”¨çƒå½¢æ£€æµ‹è·å–é™„è¿‘çš„å‹å†›
    FXBDetectionResult AlliesResult;
    UXBBlueprintFunctionLibrary::DetectAlliesInRadius(
        this,
        MyLocation,
        AvoidanceRadius,
        Faction,
        true,
        AlliesResult
    );

    int32 AvoidanceCount = 0;

    for (AActor* OtherActor : AlliesResult.DetectedActors)
    {
        if (OtherActor == this)
        {
            continue;
        }

        float Distance = FVector::Dist2D(MyLocation, OtherActor->GetActorLocation());
        if (Distance > KINDA_SMALL_NUMBER)
        {
            FVector AwayDirection = (MyLocation - OtherActor->GetActorLocation()).GetSafeNormal2D();
            float Strength = 1.0f - (Distance / AvoidanceRadius);
            AvoidanceForce += AwayDirection * Strength;
            AvoidanceCount++;
        }
    }

    if (AvoidanceCount == 0)
    {
        return DesiredDirection;
    }

    AvoidanceForce.Normalize();

    FVector BlendedDirection = DesiredDirection * (1.0f - AvoidanceWeight) + 
                               AvoidanceForce * AvoidanceWeight;

    return BlendedDirection.GetSafeNormal();
}

void AXBSoldierCharacter::MoveToTarget(AActor* Target)
{
    if (!Target || !IsValid(Target))
    {
        return;
    }

    AAIController* AICtrl = Cast<AAIController>(GetController());
    if (!AICtrl)
    {
        return;
    }

    float AcceptanceRadius = bInitializedFromDataTable ? CachedTableRow.AttackRange * 0.9f : SoldierConfig.AttackRange * 0.9f;

    AICtrl->MoveToActor(
        Target,
        AcceptanceRadius,
        true,
        true,
        true,
        nullptr,
        true
    );

    UE_LOG(LogXBSoldier, VeryVerbose, TEXT("å£«å…µ %s è¿½è¸ªç›®æ ‡ %sï¼Œè·ç¦»: %.0f"), 
        *GetName(), *Target->GetName(), GetDistanceToTarget(Target));
}

void AXBSoldierCharacter::MoveToFormationPosition()
{
    // ğŸ”§ ä¿®æ”¹ - ä½¿ç”¨è·Ÿéšç»„ä»¶çš„æ’å€¼æ¨¡å¼
    if (FollowComponent)
    {
        FollowComponent->StartInterpolateToFormation();
    }
}

FVector AXBSoldierCharacter::GetFormationWorldPosition() const
{
    if (!FollowTarget.IsValid())
    {
        return GetActorLocation();
    }

    if (FollowComponent)
    {
        return FollowComponent->GetTargetPosition();
    }

    return FollowTarget->GetActorLocation();
}

FVector AXBSoldierCharacter::GetFormationWorldPositionSafe() const
{
    if (!FollowTarget.IsValid())
    {
        return FVector::ZeroVector;
    }
    
    AActor* Target = FollowTarget.Get();
    if (!Target || !IsValid(Target))
    {
        return FVector::ZeroVector;
    }
    
    if (!FollowComponent)
    {
        return Target->GetActorLocation();
    }
    
    FVector TargetPos = FollowComponent->GetTargetPosition();
    if (!TargetPos.IsZero() && !TargetPos.ContainsNaN())
    {
        return TargetPos;
    }
    
    return Target->GetActorLocation();
}


/**
 * @brief æ£€æŸ¥æ˜¯å¦åˆ°è¾¾ç¼–é˜Ÿä½ç½®
 * @note ğŸ”§ ä¿®æ”¹ - ä½¿ç”¨è·Ÿéšç»„ä»¶çš„åˆ¤æ–­
 */
bool AXBSoldierCharacter::IsAtFormationPosition() const
{
    if (FollowComponent)
    {
        return FollowComponent->IsAtFormationPosition();
    }
    
    // é™çº§ï¼šä½¿ç”¨æ—§é€»è¾‘
    FVector TargetPos = GetFormationWorldPosition();
    float ArrivalThreshold = GetArrivalThreshold();
    return FVector::Dist2D(GetActorLocation(), TargetPos) <= ArrivalThreshold;
}

/**
 * @brief å®‰å…¨æ£€æŸ¥æ˜¯å¦åˆ°è¾¾ç¼–é˜Ÿä½ç½®
 */
bool AXBSoldierCharacter::IsAtFormationPositionSafe() const
{
    if (!FollowTarget.IsValid() || FormationSlotIndex == INDEX_NONE)
    {
        return true;
    }
    
    if (FollowComponent)
    {
        return FollowComponent->IsAtFormationPosition();
    }
    
    return true;
}

// ==================== è·Ÿéšç³»ç»Ÿå®ç° ====================

void AXBSoldierCharacter::SetFollowTarget(AActor* NewLeader, int32 SlotIndex)
{
    FollowTarget = NewLeader;
    FormationSlotIndex = SlotIndex;

    if (FollowComponent)
    {
        FollowComponent->SetFollowTarget(NewLeader);
        FollowComponent->SetFormationSlotIndex(SlotIndex);
    }

    if (AAIController* AICtrl = Cast<AAIController>(GetController()))
    {
        if (UBlackboardComponent* BBComp = AICtrl->GetBlackboardComponent())
        {
            BBComp->SetValueAsObject(TEXT("Leader"), NewLeader);
            BBComp->SetValueAsInt(TEXT("FormationSlot"), SlotIndex);
        }
    }

    if (NewLeader)
    {
        SetSoldierState(EXBSoldierState::Following);
    }
    else
    {
        SetSoldierState(EXBSoldierState::Idle);
    }
}

AXBCharacterBase* AXBSoldierCharacter::GetLeaderCharacter() const
{
    return Cast<AXBCharacterBase>(FollowTarget.Get());
}

void AXBSoldierCharacter::SetFormationSlotIndex(int32 NewIndex)
{
    FormationSlotIndex = NewIndex;

    if (FollowComponent)
    {
        FollowComponent->SetFormationSlotIndex(NewIndex);
    }

    if (AAIController* AICtrl = Cast<AAIController>(GetController()))
    {
        if (UBlackboardComponent* BBComp = AICtrl->GetBlackboardComponent())
        {
            BBComp->SetValueAsInt(TEXT("FormationSlot"), NewIndex);
        }
    }
}

// ==================== çŠ¶æ€ç®¡ç†å®ç° ====================

void AXBSoldierCharacter::SetSoldierState(EXBSoldierState NewState)
{
    if (CurrentState == NewState)
    {
        return;
    }

    EXBSoldierState OldState = CurrentState;
    CurrentState = NewState;

    if (AAIController* AICtrl = Cast<AAIController>(GetController()))
    {
        if (UBlackboardComponent* BBComp = AICtrl->GetBlackboardComponent())
        {
            // ğŸ”§ ä¿®æ”¹ - ä½¿ç”¨ Int ç±»å‹
            BBComp->SetValueAsInt(TEXT("SoldierState"), static_cast<int32>(NewState));
        }
    }

    OnSoldierStateChanged.Broadcast(OldState, NewState);

    UE_LOG(LogXBSoldier, Log, TEXT("å£«å…µ %s çŠ¶æ€å˜åŒ–: %d -> %d"), 
        *GetName(), static_cast<int32>(OldState), static_cast<int32>(NewState));
}

// ==================== æˆ˜æ–—ç³»ç»Ÿå®ç° ====================

/**
 * @brief è¿›å…¥æˆ˜æ–—
 * @note ğŸ”§ ä¿®æ”¹ - é€šçŸ¥è·Ÿéšç»„ä»¶åˆ‡æ¢åˆ°è‡ªç”±æ¨¡å¼
 */
void AXBSoldierCharacter::EnterCombat()
{
    if (CurrentState == EXBSoldierState::Dead)
    {
        return;
    }

    if (!bIsRecruited)
    {
        return;
    }

    // ğŸ”§ ä¿®æ”¹ - é€šçŸ¥è·Ÿéšç»„ä»¶è¿›å…¥æˆ˜æ–—æ¨¡å¼
    if (FollowComponent)
    {
        FollowComponent->EnterCombatMode();
    }

    SetSoldierState(EXBSoldierState::Combat);
    CurrentAttackTarget = FindNearestEnemy();

    UE_LOG(LogXBCombat, Log, TEXT("å£«å…µ %s è¿›å…¥æˆ˜æ–—, ç›®æ ‡: %s"), 
        *GetName(), CurrentAttackTarget.IsValid() ? *CurrentAttackTarget->GetName() : TEXT("æ— "));
}

/**
 * @brief é€€å‡ºæˆ˜æ–—
 * @note ğŸ”§ ä¿®æ”¹ - é€šçŸ¥è·Ÿéšç»„ä»¶ä¼ é€å›ç¼–é˜Ÿä½ç½®
 */
void AXBSoldierCharacter::ExitCombat()
{
    if (CurrentState == EXBSoldierState::Dead)
    {
        return;
    }

    CurrentAttackTarget = nullptr;
    
    // ğŸ”§ ä¿®æ”¹ - é€šçŸ¥è·Ÿéšç»„ä»¶é€€å‡ºæˆ˜æ–—æ¨¡å¼
    if (FollowComponent)
    {
        FollowComponent->ExitCombatMode();
    }
    
    // åœæ­¢AIç§»åŠ¨
    if (AAIController* AICtrl = Cast<AAIController>(GetController()))
    {
        AICtrl->StopMovement();
    }

    SetSoldierState(EXBSoldierState::Following);

    UE_LOG(LogXBCombat, Log, TEXT("å£«å…µ %s é€€å‡ºæˆ˜æ–—"), *GetName());
}

float AXBSoldierCharacter::TakeSoldierDamage(float DamageAmount, AActor* DamageSource)
{
    if (CurrentState == EXBSoldierState::Dead)
    {
        return 0.0f;
    }

    float ActualDamage = FMath::Min(DamageAmount, CurrentHealth);
    CurrentHealth -= ActualDamage;

    UE_LOG(LogXBCombat, Log, TEXT("å£«å…µ %s å—åˆ° %.1f ä¼¤å®³, å‰©ä½™è¡€é‡: %.1f"), 
        *GetName(), ActualDamage, CurrentHealth);

    if (CurrentHealth <= 0.0f)
    {
        HandleDeath();
    }

    return ActualDamage;
}

bool AXBSoldierCharacter::PerformAttack(AActor* Target)
{
    if (!Target || !IsValid(Target) || !CanAttack())
    {
        return false;
    }

    float AttackInterval = bInitializedFromDataTable ? CachedTableRow.AttackInterval : SoldierConfig.AttackInterval;
    AttackCooldownTimer = AttackInterval;

    PlayAttackMontage();

    float Damage = bInitializedFromDataTable ? CachedTableRow.BaseDamage : SoldierConfig.BaseDamage;

    if (AXBSoldierCharacter* TargetSoldier = Cast<AXBSoldierCharacter>(Target))
    {
        TargetSoldier->TakeSoldierDamage(Damage, this);
    }

    UE_LOG(LogXBCombat, Log, TEXT("å£«å…µ %s æ”»å‡» %sï¼Œä¼¤å®³: %.1f"), 
        *GetName(), *Target->GetName(), Damage);

    return true;
}

bool AXBSoldierCharacter::PlayAttackMontage()
{
    UAnimMontage* AttackMontage = nullptr;

    if (bInitializedFromDataTable && !CachedTableRow.BasicAttack.AbilityMontage.IsNull())
    {
        AttackMontage = CachedTableRow.BasicAttack.AbilityMontage.LoadSynchronous();
    }

    if (!AttackMontage)
    {
        return false;
    }

    if (UAnimInstance* AnimInstance = GetMesh()->GetAnimInstance())
    {
        return AnimInstance->Montage_Play(AttackMontage) > 0.0f;
    }

    return false;
}

/**
 * @brief æ›´æ–°æˆ˜æ–—é€»è¾‘
 * @param DeltaTime å¸§æ—¶é—´
 * @note ğŸ”§ ä¿®æ”¹ - ä½¿ç”¨æ•°æ®è¡¨é…ç½®å’Œçƒå½¢æ£€æµ‹
 */
void AXBSoldierCharacter::UpdateCombat(float DeltaTime)
{
    // ==================== 1. è„±ç¦»æˆ˜æ–—æ£€æµ‹ ====================
    if (ShouldDisengage())
    {
        UE_LOG(LogXBCombat, Verbose, TEXT("å£«å…µ %s è„±ç¦»æˆ˜æ–—æ¡ä»¶æ»¡è¶³ï¼Œè¿”å›é˜Ÿåˆ—"), *GetName());
        ReturnToFormation();
        return;
    }

    // ==================== 2. ç›®æ ‡æœç´¢/æ›´æ–° ====================
    // ğŸ”§ ä¿®æ”¹ - ä»æ•°æ®è¡¨è¯»å–å¯»æ•Œé—´éš”
    float SearchInterval = bInitializedFromDataTable ? 
        CachedTableRow.AIConfig.TargetSearchInterval : 0.5f;

    TargetSearchTimer += DeltaTime;
    if (TargetSearchTimer >= SearchInterval || !CurrentAttackTarget.IsValid())
    {
        TargetSearchTimer = 0.0f;
        AActor* NewTarget = FindNearestEnemy();

        if (NewTarget)
        {
            CurrentAttackTarget = NewTarget;
            LastEnemySeenTime = GetWorld()->GetTimeSeconds();
        }
    }

    // ==================== 3. æ— ç›®æ ‡å¤„ç† ====================
    if (!CurrentAttackTarget.IsValid())
    {
        // ğŸ”§ ä¿®æ”¹ - ä»æ•°æ®è¡¨è¯»å–è¿”å›å»¶è¿Ÿ
        float ReturnDelayTime = GetReturnDelay();
        float TimeSinceLastEnemy = GetWorld()->GetTimeSeconds() - LastEnemySeenTime;
        if (TimeSinceLastEnemy > ReturnDelayTime)
        {
            UE_LOG(LogXBCombat, Verbose, TEXT("å£«å…µ %s é•¿æ—¶é—´æ— ç›®æ ‡ï¼Œè¿”å›é˜Ÿåˆ—"), *GetName());
            ReturnToFormation();
        }
        return;
    }

    AActor* Target = CurrentAttackTarget.Get();
    
    // âœ¨ æ–°å¢ - ç©ºæŒ‡é’ˆæ£€æŸ¥
    if (!Target || !IsValid(Target))
    {
        CurrentAttackTarget = nullptr;
        return;
    }

    float DistanceToEnemy = GetDistanceToTarget(Target);
    float AttackRange = bInitializedFromDataTable ? CachedTableRow.AttackRange : SoldierConfig.AttackRange;

    // ==================== 4. å¼“æ‰‹ç‰¹æ®Šé€»è¾‘ ====================
    if (SoldierType == EXBSoldierType::Archer && bInitializedFromDataTable)
    {
        if (CachedTableRow.ArcherConfig.bStationaryAttack && DistanceToEnemy <= AttackRange)
        {
            if (AAIController* AICtrl = Cast<AAIController>(GetController()))
            {
                AICtrl->StopMovement();
            }

            FaceTarget(Target, DeltaTime);

            if (CanAttack())
            {
                PerformAttack(Target);
            }

            UE_LOG(LogXBCombat, VeryVerbose, TEXT("å¼“æ‰‹ %s åŸåœ°æ”»å‡» %s"), *GetName(), *Target->GetName());
            return;
        }

        if (ShouldRetreat())
        {
            RetreatFromTarget(Target);
            return;
        }
    }

    // ==================== 5. è·ç¦»åˆ¤å®šä¸è¡ŒåŠ¨ ====================
    if (DistanceToEnemy > AttackRange)
    {
        MoveToTarget(Target);
    }
    else
    {
        if (AAIController* AICtrl = Cast<AAIController>(GetController()))
        {
            AICtrl->StopMovement();
        }

        FaceTarget(Target, DeltaTime);

        if (CanAttack())
        {
            PerformAttack(Target);
        }
    }
}

/**
 * @brief æ›´æ–°è·ŸéšçŠ¶æ€
 * @param DeltaTime å¸§æ—¶é—´
 * @note ğŸ”§ ä¿®æ”¹ - è·Ÿéšç»„ä»¶ä¼šè‡ªåŠ¨å¤„ç†ï¼Œè¿™é‡ŒåªåšçŠ¶æ€æ£€æŸ¥
 */
void AXBSoldierCharacter::UpdateFollowing(float DeltaTime)
{
    // è·Ÿéšç»„ä»¶ä¼šåœ¨è‡ªå·±çš„ Tick ä¸­å¤„ç†ä½ç½®æ›´æ–°
    // è¿™é‡Œåªæ£€æŸ¥æ˜¯å¦éœ€è¦è¿›å…¥æˆ˜æ–—
    
    // å¦‚æœå¯ç”¨äº†è‡ªåŠ¨æˆ˜æ–—æ£€æµ‹ï¼Œå¯ä»¥åœ¨è¿™é‡Œæ·»åŠ é€»è¾‘
    // ç›®å‰ç”±è¡Œä¸ºæ ‘æˆ–å¤–éƒ¨è§¦å‘æˆ˜æ–—
}

void AXBSoldierCharacter::UpdateReturning(float DeltaTime)
{
    // è·Ÿéšç»„ä»¶ä¼šå¤„ç†ä½ç½®æ›´æ–°
    // è¿™é‡Œæ£€æŸ¥æ˜¯å¦åˆ°è¾¾ç¼–é˜Ÿä½ç½®
    
    if (FollowComponent && FollowComponent->IsAtFormationPosition())
    {
        SetSoldierState(EXBSoldierState::Following);
    }
}

void AXBSoldierCharacter::FaceTarget(AActor* Target, float DeltaTime)
{
    if (!Target || !IsValid(Target))
    {
        return;
    }

    FVector Direction = (Target->GetActorLocation() - GetActorLocation()).GetSafeNormal2D();
    if (!Direction.IsNearlyZero())
    {
        FRotator TargetRotation = Direction.Rotation();
        FRotator CurrentRotation = GetActorRotation();
        float RotationSpeed = bInitializedFromDataTable ? CachedTableRow.RotationSpeed : 360.0f;
        FRotator NewRotation = FMath::RInterpTo(CurrentRotation, TargetRotation, DeltaTime, RotationSpeed / 90.0f);
        SetActorRotation(FRotator(0.0f, NewRotation.Yaw, 0.0f));
    }
}

// ==================== é€ƒè·‘ç³»ç»Ÿå®ç° ====================
/**
 * @brief è®¾ç½®é€ƒè·‘çŠ¶æ€
 * @param bEscaping æ˜¯å¦é€ƒè·‘
 * @note ğŸ”§ ä¿®æ”¹ - é€ƒè·‘æ—¶ä¼ é€å›ç¼–é˜Ÿä½ç½®
 */
void AXBSoldierCharacter::SetEscaping(bool bEscaping)
{
    bIsEscaping = bEscaping;

    if (bEscaping)
    {
        // ğŸ”§ ä¿®æ”¹ - é€ƒè·‘æ—¶é€€å‡ºæˆ˜æ–—çŠ¶æ€
        if (FollowComponent)
        {
            // è®¾ç½®æˆ˜æ–—çŠ¶æ€ä¸ºfalse
            FollowComponent->SetCombatState(false);
            
            if (CurrentState == EXBSoldierState::Combat)
            {
                CurrentAttackTarget = nullptr;
                SetSoldierState(EXBSoldierState::Following);
            }
            
            // ä½¿ç”¨æ’å€¼æ¨¡å¼å›åˆ°ç¼–é˜Ÿä½ç½®
            FollowComponent->StartInterpolateToFormation();
        }
        
        if (AAIController* AICtrl = Cast<AAIController>(GetController()))
        {
            AICtrl->StopMovement();
        }
    }

    // æ›´æ–°ç§»åŠ¨é€Ÿåº¦
    float BaseSpeed = bInitializedFromDataTable ? CachedTableRow.MoveSpeed : SoldierConfig.MoveSpeed;
    float SprintMultiplier = bInitializedFromDataTable ? CachedTableRow.SprintSpeedMultiplier : 2.0f;

    float NewSpeed = bEscaping ? BaseSpeed * SprintMultiplier : BaseSpeed;

    if (UCharacterMovementComponent* MovementComp = GetCharacterMovement())
    {
        MovementComp->MaxWalkSpeed = NewSpeed;
    }
}

// ==================== æ­»äº¡ç³»ç»Ÿå®ç° ====================

void AXBSoldierCharacter::HandleDeath()
{
    GetWorldTimerManager().ClearTimer(DelayedAIStartTimerHandle);
    
    SetSoldierState(EXBSoldierState::Dead);

    OnSoldierDied.Broadcast(this);

    if (AXBCharacterBase* LeaderCharacter = GetLeaderCharacter())
    {
        LeaderCharacter->OnSoldierDied(this);
    }

    if (UCapsuleComponent* Capsule = GetCapsuleComponent())
    {
        Capsule->SetCollisionEnabled(ECollisionEnabled::NoCollision);
    }

    if (AAIController* AICtrl = Cast<AAIController>(GetController()))
    {
        AICtrl->StopMovement();
    }

    if (UCharacterMovementComponent* MoveComp = GetCharacterMovement())
    {
        MoveComp->SetComponentTickEnabled(false);
    }

    if (bInitializedFromDataTable && !CachedTableRow.VisualConfig.DeathMontage.IsNull())
    {
        UAnimMontage* DeathMontage = CachedTableRow.VisualConfig.DeathMontage.LoadSynchronous();
        if (DeathMontage)
        {
            if (UAnimInstance* AnimInstance = GetMesh()->GetAnimInstance())
            {
                AnimInstance->Montage_Play(DeathMontage);
            }
        }
    }

    SetLifeSpan(2.0f);

    UE_LOG(LogXBSoldier, Log, TEXT("å£«å…µ %s æ­»äº¡"), *GetName());
}
