/* --- å®Œæ•´æ–‡ä»¶ä»£ç  --- */
// Source/XiaoBinDaTianXia/Private/AI/XBSoldierAIController.cpp

/**
 * @file XBSoldierAIController.cpp
 * @brief å£«å…µAIæ§åˆ¶å™¨å®ç°
 * 
 * @note ğŸ”§ ä¿®æ”¹è®°å½•:
 *       1. SoldierState ä½¿ç”¨ Int ç±»å‹æ›¿ä»£ Enum
 *       2. æ·»åŠ é»‘æ¿é”®ç±»å‹æ ¡éªŒ
 *       3. ä½¿ç”¨é¡¹ç›®ä¸“ç”¨æ—¥å¿—ç±»åˆ«
 *       4. å¢å¼ºç©ºæŒ‡é’ˆæ£€æŸ¥
 */

#include "AI/XBSoldierAIController.h"
#include "Utils/XBLogCategories.h"
#include "Utils/XBBlueprintFunctionLibrary.h"
#include "BehaviorTree/BehaviorTree.h"
#include "BehaviorTree/BehaviorTreeComponent.h"
#include "BehaviorTree/BlackboardComponent.h"
#include "BehaviorTree/Blackboard/BlackboardKeyType_Object.h"
#include "BehaviorTree/Blackboard/BlackboardKeyType_Vector.h"
#include "BehaviorTree/Blackboard/BlackboardKeyType_Int.h"
#include "BehaviorTree/Blackboard/BlackboardKeyType_Float.h"
#include "BehaviorTree/Blackboard/BlackboardKeyType_Bool.h"
#include "BehaviorTree/Blackboard/BlackboardKeyType_Enum.h"
#include "Soldier/XBSoldierCharacter.h"
#include "Character/XBCharacterBase.h"
#include "TimerManager.h"
#include "GameFramework/CharacterMovementComponent.h"

AXBSoldierAIController::AXBSoldierAIController()
{
    BehaviorTreeComp = CreateDefaultSubobject<UBehaviorTreeComponent>(TEXT("BehaviorTreeComponent"));
    BlackboardComp = CreateDefaultSubobject<UBlackboardComponent>(TEXT("BlackboardComponent"));
    
    PrimaryActorTick.bCanEverTick = true;
    PrimaryActorTick.bStartWithTickEnabled = false;
}

void AXBSoldierAIController::BeginPlay()
{
    Super::BeginPlay();
    
    UE_LOG(LogXBAI, Log, TEXT("å£«å…µAIæ§åˆ¶å™¨ %s BeginPlay"), *GetName());
}

void AXBSoldierAIController::OnPossess(APawn* InPawn)
{
    if (!InPawn)
    {
        UE_LOG(LogXBAI, Warning, TEXT("AIæ§åˆ¶å™¨ %s OnPossess: InPawn ä¸ºç©º"), *GetName());
        return;
    }
    
    AXBSoldierCharacter* Soldier = Cast<AXBSoldierCharacter>(InPawn);
    if (Soldier)
    {
        CachedSoldier = Soldier;
    }
    else
    {
        UE_LOG(LogXBAI, Warning, TEXT("AIæ§åˆ¶å™¨ %s: è¢«æ§åˆ¶çš„Pawnä¸æ˜¯å£«å…µç±»å‹: %s"), 
            *GetName(), *InPawn->GetName());
    }
    
    Super::OnPossess(InPawn);
    
    if (Soldier)
    {
        GetWorldTimerManager().SetTimerForNextTick(this, &AXBSoldierAIController::DelayedOnPossess);
        UE_LOG(LogXBAI, Log, TEXT("AIæ§åˆ¶å™¨ %s: Possess æˆåŠŸï¼Œå·²å®‰æ’å»¶è¿Ÿåˆå§‹åŒ–"), *GetName());
    }
}

void AXBSoldierAIController::DelayedOnPossess()
{
    if (!IsValid(this))
    {
        UE_LOG(LogXBAI, Warning, TEXT("DelayedOnPossess: æ§åˆ¶å™¨å·²æ— æ•ˆ"));
        return;
    }
    
    APawn* MyPawn = GetPawn();
    if (!MyPawn)
    {
        UE_LOG(LogXBAI, Warning, TEXT("DelayedOnPossess: Pawn ä¸ºç©º"));
        return;
    }
    
    if (!CachedSoldier.IsValid())
    {
        UE_LOG(LogXBAI, Warning, TEXT("DelayedOnPossess: ç¼“å­˜çš„å£«å…µå¼•ç”¨æ— æ•ˆ"));
        return;
    }
    
    AXBSoldierCharacter* Soldier = CachedSoldier.Get();
    if (!Soldier || !IsValid(Soldier))
    {
        UE_LOG(LogXBAI, Warning, TEXT("DelayedOnPossess: å£«å…µActoræ— æ•ˆ"));
        return;
    }
    
    if (Soldier->IsPendingKillPending())
    {
        UE_LOG(LogXBAI, Warning, TEXT("DelayedOnPossess: å£«å…µæ­£åœ¨é”€æ¯ä¸­"));
        return;
    }
    
    UBehaviorTree* BTToUse = nullptr;
    
    if (Soldier->BehaviorTreeAsset != nullptr)
    {
        BTToUse = Soldier->BehaviorTreeAsset;
        UE_LOG(LogXBAI, Log, TEXT("ä½¿ç”¨å£«å…µ %s é…ç½®çš„è¡Œä¸ºæ ‘: %s"), 
            *Soldier->GetName(), *BTToUse->GetName());
    }
    else if (DefaultBehaviorTree != nullptr)
    {
        BTToUse = DefaultBehaviorTree;
        UE_LOG(LogXBAI, Log, TEXT("ä½¿ç”¨é»˜è®¤è¡Œä¸ºæ ‘æ§åˆ¶å£«å…µ %s"), *Soldier->GetName());
    }
    
    if (BTToUse)
    {
        if (StartBehaviorTree(BTToUse))
        {
            bIsInitialized = true;
            SetActorTickEnabled(true);
            UE_LOG(LogXBAI, Log, TEXT("AIæ§åˆ¶å™¨ %s: è¡Œä¸ºæ ‘å¯åŠ¨æˆåŠŸï¼ŒTickå·²å¯ç”¨"), *GetName());
        }
        else
        {
            UE_LOG(LogXBAI, Error, TEXT("AIæ§åˆ¶å™¨ %s: è¡Œä¸ºæ ‘å¯åŠ¨å¤±è´¥"), *GetName());
        }
    }
    else
    {
        bIsInitialized = true;
        SetActorTickEnabled(true);
        UE_LOG(LogXBAI, Log, TEXT("å£«å…µ %s æ²¡æœ‰é…ç½®è¡Œä¸ºæ ‘ï¼Œä½¿ç”¨ç®€å•çŠ¶æ€æœº"), *Soldier->GetName());
    }
}

void AXBSoldierAIController::OnUnPossess()
{
    GetWorldTimerManager().ClearAllTimersForObject(this);
    StopBehaviorTreeLogic();
    SetActorTickEnabled(false);
    bIsInitialized = false;
    CachedSoldier.Reset();
    
    Super::OnUnPossess();
    
    UE_LOG(LogXBAI, Log, TEXT("AIæ§åˆ¶å™¨ %s: UnPossess å®Œæˆ"), *GetName());
}

void AXBSoldierAIController::Tick(float DeltaTime)
{
    Super::Tick(DeltaTime);
    
    if (!bIsInitialized)
    {
        return;
    }
    
    if (!CachedSoldier.IsValid())
    {
        return;
    }
    
    BlackboardUpdateTimer += DeltaTime;
    if (BlackboardUpdateTimer >= BlackboardUpdateInterval)
    {
        BlackboardUpdateTimer = 0.0f;
        UpdateDistanceValuesSafe();
    }
}

// ==================== è¡Œä¸ºæ ‘æ§åˆ¶å®ç° ====================

bool AXBSoldierAIController::StartBehaviorTree(UBehaviorTree* BehaviorTreeAsset)
{
    if (!BehaviorTreeAsset)
    {
        UE_LOG(LogXBAI, Error, TEXT("AIæ§åˆ¶å™¨ %s å¯åŠ¨è¡Œä¸ºæ ‘å¤±è´¥: è¡Œä¸ºæ ‘èµ„äº§ä¸ºç©º"), *GetName());
        return false;
    }
    
    if (!SetupSoldierBlackboard(BehaviorTreeAsset))
    {
        UE_LOG(LogXBAI, Error, TEXT("AIæ§åˆ¶å™¨ %s åˆå§‹åŒ–é»‘æ¿å¤±è´¥"), *GetName());
        return false;
    }
    
    // âœ¨ æ–°å¢ - æ ¡éªŒé»‘æ¿é”®ç±»å‹
    if (bValidateBlackboardKeys)
    {
        if (!ValidateAllBlackboardKeys())
        {
            UE_LOG(LogXBAI, Warning, TEXT("AIæ§åˆ¶å™¨ %s: é»‘æ¿é”®æ ¡éªŒå¤±è´¥ï¼Œéƒ¨åˆ†åŠŸèƒ½å¯èƒ½å¼‚å¸¸"), *GetName());
            // ä¸é˜»æ­¢å¯åŠ¨ï¼Œåªæ˜¯è­¦å‘Š
        }
    }
    
    RefreshBlackboardValuesSafe();
    
    BehaviorTreeComp->StartTree(*BehaviorTreeAsset);
    
    bool bSuccess = BehaviorTreeComp->IsRunning();
    
    if (bSuccess)
    {
        UE_LOG(LogXBAI, Log, TEXT("AIæ§åˆ¶å™¨ %s æˆåŠŸå¯åŠ¨è¡Œä¸ºæ ‘ %s"), 
            *GetName(), *BehaviorTreeAsset->GetName());
    }
    else
    {
        UE_LOG(LogXBAI, Error, TEXT("AIæ§åˆ¶å™¨ %s å¯åŠ¨è¡Œä¸ºæ ‘ %s å¤±è´¥"), 
            *GetName(), *BehaviorTreeAsset->GetName());
    }
    
    return bSuccess;
}

void AXBSoldierAIController::StopBehaviorTreeLogic()
{
    if (BehaviorTreeComp && BehaviorTreeComp->IsRunning())
    {
        BehaviorTreeComp->StopTree(EBTStopMode::Safe);
        UE_LOG(LogXBAI, Log, TEXT("AIæ§åˆ¶å™¨ %s åœæ­¢è¡Œä¸ºæ ‘"), *GetName());
    }
}

void AXBSoldierAIController::PauseBehaviorTree(bool bPause)
{
    if (BehaviorTreeComp)
    {
        if (bPause)
        {
            BehaviorTreeComp->PauseLogic(TEXT("Manual Pause"));
        }
        else
        {
            BehaviorTreeComp->ResumeLogic(TEXT("Manual Resume"));
        }
    }
}

bool AXBSoldierAIController::SetupSoldierBlackboard(UBehaviorTree* BT)
{
    if (!BT || !BT->BlackboardAsset)
    {
        UE_LOG(LogXBAI, Warning, TEXT("è¡Œä¸ºæ ‘æˆ–é»‘æ¿èµ„äº§ä¸ºç©º"));
        return false;
    }
    
    UBlackboardComponent* BBCompRaw = BlackboardComp.Get();
    if (UseBlackboard(BT->BlackboardAsset, BBCompRaw))
    {
        if (BBCompRaw != BlackboardComp.Get())
        {
            BlackboardComp = BBCompRaw;
        }
        return true;
    }
    
    UE_LOG(LogXBAI, Error, TEXT("UseBlackboard å¤±è´¥"));
    return false;
}

// ==================== é»‘æ¿é”®æ ¡éªŒå®ç° ====================

/**
 * @brief è·å–é»‘æ¿é”®çš„ç±»å‹
 * @param KeyName é”®å
 * @return é”®ç±»å‹
 * @note âœ¨ æ–°å¢
 */
EXBBlackboardKeyType AXBSoldierAIController::GetBlackboardKeyType(FName KeyName) const
{
    if (!BlackboardComp)
    {
        return EXBBlackboardKeyType::Unknown;
    }
    
    const UBlackboardData* BBAsset = BlackboardComp->GetBlackboardAsset();
    if (!BBAsset)
    {
        return EXBBlackboardKeyType::Unknown;
    }
    
    FBlackboard::FKey KeyID = BlackboardComp->GetKeyID(KeyName);
    if (KeyID == FBlackboard::InvalidKey)
    {
        return EXBBlackboardKeyType::Unknown;
    }
    
    TSubclassOf<UBlackboardKeyType> KeyType = BlackboardComp->GetKeyType(KeyID);
    if (!KeyType)
    {
        return EXBBlackboardKeyType::Unknown;
    }
    
    if (KeyType->IsChildOf(UBlackboardKeyType_Object::StaticClass()))
    {
        return EXBBlackboardKeyType::Object;
    }
    if (KeyType->IsChildOf(UBlackboardKeyType_Vector::StaticClass()))
    {
        return EXBBlackboardKeyType::Vector;
    }
    if (KeyType->IsChildOf(UBlackboardKeyType_Int::StaticClass()))
    {
        return EXBBlackboardKeyType::Int;
    }
    if (KeyType->IsChildOf(UBlackboardKeyType_Float::StaticClass()))
    {
        return EXBBlackboardKeyType::Float;
    }
    if (KeyType->IsChildOf(UBlackboardKeyType_Bool::StaticClass()))
    {
        return EXBBlackboardKeyType::Bool;
    }
    // ğŸ”§ ä¿®æ”¹ - Enum ç±»å‹ä¹Ÿæ¥å—ï¼ˆå‘åå…¼å®¹ï¼‰
    if (KeyType->IsChildOf(UBlackboardKeyType_Enum::StaticClass()))
    {
        return EXBBlackboardKeyType::Int; // Enum å¯ä»¥ç”¨ Int æ–¹å¼è®¾ç½®
    }
    
    return EXBBlackboardKeyType::Unknown;
}

bool AXBSoldierAIController::ValidateBlackboardKey(FName KeyName, EXBBlackboardKeyType ExpectedType) const
{
    if (!BlackboardComp)
    {
        UE_LOG(LogXBAI, Warning, TEXT("æ ¡éªŒé»‘æ¿é”®å¤±è´¥: é»‘æ¿ç»„ä»¶ä¸ºç©º"));
        return false;
    }
    
    EXBBlackboardKeyType ActualType = GetBlackboardKeyType(KeyName);
    
    if (ActualType == EXBBlackboardKeyType::Unknown)
    {
        UE_LOG(LogXBAI, Warning, TEXT("é»‘æ¿é”® '%s' ä¸å­˜åœ¨æˆ–ç±»å‹æœªçŸ¥"), *KeyName.ToString());
        return false;
    }
    
    if (ActualType != ExpectedType)
    {
        UE_LOG(LogXBAI, Warning, TEXT("é»‘æ¿é”® '%s' ç±»å‹ä¸åŒ¹é…: æœŸæœ› %d, å®é™… %d"), 
            *KeyName.ToString(), static_cast<int32>(ExpectedType), static_cast<int32>(ActualType));
        return false;
    }
    
    return true;
}

/**
 * @brief æ ¡éªŒæ‰€æœ‰å¿…éœ€çš„é»‘æ¿é”®
 * @return æ˜¯å¦æ‰€æœ‰é”®éƒ½æ ¡éªŒé€šè¿‡
 * @note âœ¨ æ–°å¢ - åœ¨åˆå§‹åŒ–æ—¶è°ƒç”¨ï¼Œè¾“å‡ºæ‰€æœ‰ä¸åŒ¹é…çš„é”®
 */
bool AXBSoldierAIController::ValidateAllBlackboardKeys() const
{
    if (!BlackboardComp)
    {
        UE_LOG(LogXBAI, Error, TEXT("æ ¡éªŒé»‘æ¿é”®å¤±è´¥: é»‘æ¿ç»„ä»¶ä¸ºç©º"));
        return false;
    }
    
    bool bAllValid = true;
    
    // å®šä¹‰éœ€è¦æ ¡éªŒçš„é”®åŠå…¶æœŸæœ›ç±»å‹
    struct FKeyValidation
    {
        FName KeyName;
        EXBBlackboardKeyType ExpectedType;
        bool bRequired; // æ˜¯å¦å¿…éœ€
    };
    
    TArray<FKeyValidation> KeysToValidate = {
        // å¯¹è±¡ç±»å‹
        { XBSoldierBBKeys::Leader,          EXBBlackboardKeyType::Object, true },
        { XBSoldierBBKeys::CurrentTarget,   EXBBlackboardKeyType::Object, true },
        { XBSoldierBBKeys::Self,            EXBBlackboardKeyType::Object, true },
        
        // ä½ç½®ç±»å‹
        { XBSoldierBBKeys::TargetLocation,      EXBBlackboardKeyType::Vector, true },
        { XBSoldierBBKeys::FormationPosition,   EXBBlackboardKeyType::Vector, true },
        
        // ğŸ”§ ä¿®æ”¹ - æ•´æ•°ç±»å‹ï¼ˆSoldierState ä½¿ç”¨ Intï¼‰
        { XBSoldierBBKeys::SoldierState,    EXBBlackboardKeyType::Int, true },
        { XBSoldierBBKeys::FormationSlot,   EXBBlackboardKeyType::Int, true },
        
        // æµ®ç‚¹ç±»å‹
        { XBSoldierBBKeys::AttackRange,         EXBBlackboardKeyType::Float, true },
        { XBSoldierBBKeys::DetectionRange,      EXBBlackboardKeyType::Float, false },
        { XBSoldierBBKeys::VisionRange,         EXBBlackboardKeyType::Float, false },
        { XBSoldierBBKeys::DistanceToTarget,    EXBBlackboardKeyType::Float, true },
        { XBSoldierBBKeys::DistanceToLeader,    EXBBlackboardKeyType::Float, true },
        
        // å¸ƒå°”ç±»å‹
        { XBSoldierBBKeys::HasTarget,       EXBBlackboardKeyType::Bool, true },
        { XBSoldierBBKeys::IsInCombat,      EXBBlackboardKeyType::Bool, true },
        { XBSoldierBBKeys::ShouldRetreat,   EXBBlackboardKeyType::Bool, false },
        { XBSoldierBBKeys::IsAtFormation,   EXBBlackboardKeyType::Bool, false },
        { XBSoldierBBKeys::CanAttack,       EXBBlackboardKeyType::Bool, true },
    };
    
    int32 FailCount = 0;
    
    for (const FKeyValidation& Validation : KeysToValidate)
    {
        if (!ValidateBlackboardKey(Validation.KeyName, Validation.ExpectedType))
        {
            if (Validation.bRequired)
            {
                FailCount++;
                bAllValid = false;
            }
        }
    }
    
    if (FailCount > 0)
    {
        UE_LOG(LogXBAI, Warning, TEXT("é»‘æ¿é”®æ ¡éªŒå®Œæˆ: %d ä¸ªå¿…éœ€é”®æ ¡éªŒå¤±è´¥"), FailCount);
    }
    else
    {
        UE_LOG(LogXBAI, Log, TEXT("é»‘æ¿é”®æ ¡éªŒå®Œæˆ: æ‰€æœ‰å¿…éœ€é”®æ ¡éªŒé€šè¿‡"));
    }
    
    return bAllValid;
}

// ==================== é»‘æ¿å€¼æ›´æ–°å®ç° ====================

void AXBSoldierAIController::SetTargetActor(AActor* Target)
{
    if (!BlackboardComp)
    {
        return;
    }
    
    BlackboardComp->SetValueAsObject(XBSoldierBBKeys::CurrentTarget, Target);
    BlackboardComp->SetValueAsBool(XBSoldierBBKeys::HasTarget, Target != nullptr);
    
    if (Target && IsValid(Target))
    {
        BlackboardComp->SetValueAsVector(XBSoldierBBKeys::TargetLocation, Target->GetActorLocation());
    }
}

void AXBSoldierAIController::SetLeader(AActor* Leader)
{
    if (!BlackboardComp)
    {
        return;
    }
    
    BlackboardComp->SetValueAsObject(XBSoldierBBKeys::Leader, Leader);
}

/**
 * @brief è®¾ç½®å£«å…µçŠ¶æ€
 * @param NewState æ–°çŠ¶æ€
 * @note ğŸ”§ ä¿®æ”¹ - ä½¿ç”¨ SetValueAsInt æ›¿ä»£ SetValueAsEnum
 *       è“å›¾ä¸­å°†é»‘æ¿é”®é…ç½®ä¸º Int ç±»å‹
 */
void AXBSoldierAIController::SetSoldierState(uint8 NewState)
{
    if (!BlackboardComp)
    {
        return;
    }
    
    // ğŸ”§ ä¿®æ”¹ - ä½¿ç”¨ Int ç±»å‹
    BlackboardComp->SetValueAsInt(XBSoldierBBKeys::SoldierState, static_cast<int32>(NewState));
    
    bool bInCombat = (NewState == static_cast<uint8>(EXBSoldierState::Combat));
    BlackboardComp->SetValueAsBool(XBSoldierBBKeys::IsInCombat, bInCombat);
}

void AXBSoldierAIController::SetFormationPosition(const FVector& Position)
{
    if (!BlackboardComp)
    {
        return;
    }
    
    BlackboardComp->SetValueAsVector(XBSoldierBBKeys::FormationPosition, Position);
}

void AXBSoldierAIController::SetAttackRange(float Range)
{
    if (!BlackboardComp)
    {
        return;
    }
    
    BlackboardComp->SetValueAsFloat(XBSoldierBBKeys::AttackRange, Range);
}

void AXBSoldierAIController::SetVisionRange(float Range)
{
    if (!BlackboardComp)
    {
        return;
    }
    
    BlackboardComp->SetValueAsFloat(XBSoldierBBKeys::VisionRange, Range);
    // åŒæ—¶è®¾ç½® DetectionRange ä¿æŒå‘åå…¼å®¹
    BlackboardComp->SetValueAsFloat(XBSoldierBBKeys::DetectionRange, Range);
}

void AXBSoldierAIController::UpdateCombatState(bool bInCombat)
{
    if (!BlackboardComp)
    {
        return;
    }
    
    BlackboardComp->SetValueAsBool(XBSoldierBBKeys::IsInCombat, bInCombat);
}

void AXBSoldierAIController::RefreshBlackboardValuesSafe()
{
    if (!BlackboardComp)
    {
        UE_LOG(LogXBAI, Warning, TEXT("RefreshBlackboardValuesSafe: BlackboardComp ä¸ºç©º"));
        return;
    }
    
    if (!CachedSoldier.IsValid())
    {
        UE_LOG(LogXBAI, Warning, TEXT("RefreshBlackboardValuesSafe: CachedSoldier æ— æ•ˆ"));
        return;
    }
    
    AXBSoldierCharacter* Soldier = CachedSoldier.Get();
    if (!Soldier || !IsValid(Soldier))
    {
        return;
    }
    
    if (Soldier->IsPendingKillPending())
    {
        return;
    }
    
    BlackboardComp->SetValueAsObject(XBSoldierBBKeys::Self, Soldier);
    
    AActor* Leader = Soldier->GetFollowTarget();
    SetLeader(Leader);
    
    // ğŸ”§ ä¿®æ”¹ - ä½¿ç”¨ Int ç±»å‹è®¾ç½®çŠ¶æ€
    SetSoldierState(static_cast<uint8>(Soldier->GetSoldierState()));
    
    int32 SlotIndex = Soldier->GetFormationSlotIndex();
    BlackboardComp->SetValueAsInt(XBSoldierBBKeys::FormationSlot, SlotIndex);
    
    FVector CurrentPosition = Soldier->GetActorLocation();
    SetFormationPosition(CurrentPosition);
    
    // ä»æ•°æ®è¡¨è·å–é…ç½®
    const FXBSoldierConfig& Config = Soldier->GetSoldierConfig();
    SetAttackRange(Config.AttackRange);
    
    // âœ¨ æ–°å¢ - è®¾ç½®è§†é‡èŒƒå›´ï¼ˆä»æ•°æ®è¡¨è¯»å–ï¼‰
    // è¿™é‡Œä½¿ç”¨ Config ä¸­çš„æ•°æ®ï¼Œå¦‚æœæœ‰ CachedTableRow åˆ™ä¼˜å…ˆä½¿ç”¨
    float VisionRange = 800.0f; // é»˜è®¤å€¼
    // åç»­å¯ä»¥ä» CachedTableRow.AIConfig.VisionRange è¯»å–
    SetVisionRange(VisionRange);
    
    BlackboardComp->SetValueAsBool(XBSoldierBBKeys::CanAttack, true);
    BlackboardComp->SetValueAsBool(XBSoldierBBKeys::IsAtFormation, true);
    BlackboardComp->SetValueAsFloat(XBSoldierBBKeys::DistanceToTarget, MAX_FLT);
    BlackboardComp->SetValueAsFloat(XBSoldierBBKeys::DistanceToLeader, 0.0f);
    BlackboardComp->SetValueAsBool(XBSoldierBBKeys::ShouldRetreat, false);
    BlackboardComp->SetValueAsBool(XBSoldierBBKeys::HasTarget, false);
    
    UE_LOG(LogXBAI, Verbose, TEXT("AIæ§åˆ¶å™¨ %s: é»‘æ¿å€¼å®‰å…¨åˆ·æ–°å®Œæˆ"), *GetName());
}

void AXBSoldierAIController::RefreshBlackboardValues()
{
    RefreshBlackboardValuesSafe();
}

void AXBSoldierAIController::UpdateDistanceValuesSafe()
{
    if (!BlackboardComp)
    {
        return;
    }
    
    if (!CachedSoldier.IsValid())
    {
        return;
    }
    
    AXBSoldierCharacter* Soldier = CachedSoldier.Get();
    if (!Soldier || !IsValid(Soldier) || Soldier->IsPendingKillPending())
    {
        return;
    }
    
    FVector SoldierLocation = Soldier->GetActorLocation();
    
    // æ›´æ–°åˆ°ç›®æ ‡çš„è·ç¦»
    UObject* TargetObj = BlackboardComp->GetValueAsObject(XBSoldierBBKeys::CurrentTarget);
    if (AActor* Target = Cast<AActor>(TargetObj))
    {
        if (IsValid(Target) && !Target->IsPendingKillPending())
        {
            float DistToTarget = FVector::Dist(SoldierLocation, Target->GetActorLocation());
            BlackboardComp->SetValueAsFloat(XBSoldierBBKeys::DistanceToTarget, DistToTarget);
            BlackboardComp->SetValueAsVector(XBSoldierBBKeys::TargetLocation, Target->GetActorLocation());
        }
        else
        {
            BlackboardComp->SetValueAsFloat(XBSoldierBBKeys::DistanceToTarget, MAX_FLT);
            BlackboardComp->SetValueAsObject(XBSoldierBBKeys::CurrentTarget, nullptr);
            BlackboardComp->SetValueAsBool(XBSoldierBBKeys::HasTarget, false);
        }
    }
    else
    {
        BlackboardComp->SetValueAsFloat(XBSoldierBBKeys::DistanceToTarget, MAX_FLT);
    }
    
    // æ›´æ–°åˆ°å°†é¢†çš„è·ç¦»
    UObject* LeaderObj = BlackboardComp->GetValueAsObject(XBSoldierBBKeys::Leader);
    if (AActor* Leader = Cast<AActor>(LeaderObj))
    {
        if (IsValid(Leader) && !Leader->IsPendingKillPending())
        {
            float DistToLeader = FVector::Dist(SoldierLocation, Leader->GetActorLocation());
            BlackboardComp->SetValueAsFloat(XBSoldierBBKeys::DistanceToLeader, DistToLeader);
            
            // ä»æ•°æ®è¡¨è¯»å–è„±ç¦»è·ç¦»
            float DisengageDistance = 1000.0f; // é»˜è®¤å€¼
            // åç»­å¯ä»¥ä» Soldier çš„ CachedTableRow è¯»å–
            BlackboardComp->SetValueAsBool(XBSoldierBBKeys::ShouldRetreat, DistToLeader > DisengageDistance);
        }
    }
    
    BlackboardComp->SetValueAsBool(XBSoldierBBKeys::CanAttack, Soldier->CanAttack());
    
    FVector FormationPos = Soldier->GetFormationWorldPositionSafe();
    if (!FormationPos.IsZero() && !FormationPos.ContainsNaN())
    {
        SetFormationPosition(FormationPos);
        
        float DistToFormation = FVector::Dist2D(SoldierLocation, FormationPos);
        // ä»æ•°æ®è¡¨è¯»å–åˆ°è¾¾é˜ˆå€¼
        float ArrivalThreshold = 50.0f; // é»˜è®¤å€¼
        BlackboardComp->SetValueAsBool(XBSoldierBBKeys::IsAtFormation, DistToFormation <= ArrivalThreshold);
    }
    
    // ğŸ”§ ä¿®æ”¹ - ä½¿ç”¨ Int ç±»å‹
    SetSoldierState(static_cast<uint8>(Soldier->GetSoldierState()));
}

AXBSoldierCharacter* AXBSoldierAIController::GetSoldierActor() const
{
    return CachedSoldier.Get();
}
