/* --- å®Œæ•´æ–‡ä»¶ä»£ç  --- */
// Source/XiaoBinDaTianXia/Private/Character/Components/XBFormationComponent.cpp

/**
 * @file XBFormationComponent.cpp
 * @brief ç¼–é˜Ÿç»„ä»¶å®ç°
 * 
 * @note ğŸ”§ ä¿®æ”¹è®°å½•:
 *       1. æ–°å¢ CompactSlots() å®ç°æ§½ä½å‹ç¼©
 *       2. æ–°å¢ GetNextSlotIndex() å’Œ GetOccupiedSlotCount()
 *       3. ä¼˜åŒ–æ§½ä½åˆ†é…é€»è¾‘ç¡®ä¿é¡ºåºæ€§
 */

#include "Character/Components/XBFormationComponent.h"
#include "Soldier/XBSoldierCharacter.h"
#include "DrawDebugHelpers.h"
#include "Engine/World.h"

UXBFormationComponent::UXBFormationComponent()
{
    PrimaryComponentTick.bCanEverTick = true;
    PrimaryComponentTick.bStartWithTickEnabled = true;
}

void UXBFormationComponent::BeginPlay()
{
    Super::BeginPlay();

    if (ManualSlotCount > 0)
    {
        UE_LOG(LogTemp, Warning, TEXT("=== ä½¿ç”¨æ‰‹åŠ¨æ§½ä½æ•°é‡: %d ==="), ManualSlotCount);
        RegenerateFormation(ManualSlotCount);
    }

    UE_LOG(LogTemp, Warning, TEXT("=== ç¼–é˜Ÿç»„ä»¶åˆå§‹åŒ–: %sï¼Œæ§½ä½æ•°: %dï¼Œè°ƒè¯•: %s ==="), 
        *GetOwner()->GetName(), 
        FormationSlots.Num(),
        bDrawDebug ? TEXT("å¯ç”¨") : TEXT("ç¦ç”¨"));
}

void UXBFormationComponent::TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction)
{
    Super::TickComponent(DeltaTime, TickType, ThisTickFunction);

    if (bDrawDebug)
    {
        DrawDebugFormation(0.0f);
    }
}

void UXBFormationComponent::SetFormationSlotCount(int32 Count)
{
    if (Count < 0)
    {
        UE_LOG(LogTemp, Warning, TEXT("æ§½ä½æ•°é‡ä¸èƒ½ä¸ºè´Ÿæ•°: %d"), Count);
        return;
    }

    ManualSlotCount = Count;
    RegenerateFormation(Count);

    UE_LOG(LogTemp, Warning, TEXT("â˜…â˜…â˜… æ‰‹åŠ¨è®¾ç½®æ§½ä½æ•°é‡: %d â˜…â˜…â˜…"), Count);
}

// ==================== âœ¨ æ–°å¢ï¼šæ§½ä½ç®¡ç†æ–¹æ³• ====================

/**
 * @brief è·å–ä¸‹ä¸€ä¸ªåº”åˆ†é…çš„æ§½ä½ç´¢å¼•
 * @param CurrentSoldierCount å½“å‰å£«å…µæ•°é‡
 * @return åº”åˆ†é…çš„æ§½ä½ç´¢å¼•
 * @note æ–°å£«å…µæ€»æ˜¯åˆ†é…åˆ°é˜Ÿå°¾ï¼Œç´¢å¼•ç­‰äºå½“å‰æ•°é‡ï¼ˆä»0å¼€å§‹ï¼‰
 */
int32 UXBFormationComponent::GetNextSlotIndex(int32 CurrentSoldierCount) const
{
    // æ–°å£«å…µçš„æ§½ä½ç´¢å¼• = å½“å‰å£«å…µæ•°é‡ï¼ˆå› ä¸ºç´¢å¼•ä»0å¼€å§‹ï¼‰
    // ä¾‹å¦‚ï¼šå½“å‰æœ‰0ä¸ªå£«å…µï¼Œæ–°å£«å…µè·å¾—æ§½ä½0
    //       å½“å‰æœ‰1ä¸ªå£«å…µï¼Œæ–°å£«å…µè·å¾—æ§½ä½1
    return CurrentSoldierCount;
}

/**
 * @brief è·å–å·²å ç”¨çš„æ§½ä½æ•°é‡
 * @return å·²å ç”¨æ§½ä½æ•°
 */
int32 UXBFormationComponent::GetOccupiedSlotCount() const
{
    int32 Count = 0;
    for (const FXBFormationSlot& Slot : FormationSlots)
    {
        if (Slot.bOccupied)
        {
            Count++;
        }
    }
    return Count;
}

/**
 * @brief å‹ç¼©æ§½ä½æ•°ç»„ï¼Œç§»é™¤ä¸­é—´çš„ç©ºæ§½
 * @param Soldiers å½“å‰å£«å…µæ•°ç»„å¼•ç”¨
 * @note âœ¨ æ ¸å¿ƒé€»è¾‘ï¼š
 *       1. éå†å£«å…µæ•°ç»„ï¼ŒæŒ‰æ•°ç»„é¡ºåºé‡æ–°åˆ†é…æ§½ä½ç´¢å¼•
 *       2. æ•°ç»„ä¸­çš„ç¬¬iä¸ªå£«å…µè·å¾—æ§½ä½i
 *       3. é€šçŸ¥æ¯ä¸ªè¢«ç§»åŠ¨çš„å£«å…µæ›´æ–°å…¶æ§½ä½ç´¢å¼•
 *       4. é‡æ–°ç”Ÿæˆç¼–é˜Ÿæ§½ä½
 */
void UXBFormationComponent::CompactSlots(const TArray<AXBSoldierCharacter*>& Soldiers)
{
    UE_LOG(LogTemp, Log, TEXT("å¼€å§‹å‹ç¼©æ§½ä½ï¼Œå½“å‰å£«å…µæ•°: %d"), Soldiers.Num());

    // é‡æ–°ç”Ÿæˆæ­£ç¡®æ•°é‡çš„æ§½ä½
    RegenerateFormation(Soldiers.Num());

    // æŒ‰æ•°ç»„é¡ºåºé‡æ–°åˆ†é…æ§½ä½
    for (int32 i = 0; i < Soldiers.Num(); ++i)
    {
        AXBSoldierCharacter* Soldier = Soldiers[i];
        if (!Soldier || !IsValid(Soldier))
        {
            continue;
        }

        int32 OldSlotIndex = Soldier->GetFormationSlotIndex();
        int32 NewSlotIndex = i;

        // å¦‚æœæ§½ä½å‘ç”Ÿå˜åŒ–ï¼Œæ›´æ–°å£«å…µå¹¶å¹¿æ’­äº‹ä»¶
        if (OldSlotIndex != NewSlotIndex)
        {
            UE_LOG(LogTemp, Log, TEXT("å£«å…µ %s æ§½ä½å˜åŒ–: %d -> %d"), 
                *Soldier->GetName(), OldSlotIndex, NewSlotIndex);

            // æ›´æ–°å£«å…µçš„æ§½ä½ç´¢å¼•
            Soldier->SetFormationSlotIndex(NewSlotIndex);

            // å¹¿æ’­æ§½ä½å˜åŒ–äº‹ä»¶
            OnSlotReassigned.Broadcast(OldSlotIndex, NewSlotIndex);
        }

        // æ ‡è®°æ§½ä½ä¸ºå·²å ç”¨
        if (FormationSlots.IsValidIndex(NewSlotIndex))
        {
            FormationSlots[NewSlotIndex].bOccupied = true;
            FormationSlots[NewSlotIndex].OccupantSoldierId = Soldier->GetUniqueID();
        }
    }

    // å¹¿æ’­ç¼–é˜Ÿæ›´æ–°äº‹ä»¶
    OnFormationUpdated.Broadcast();

    UE_LOG(LogTemp, Log, TEXT("æ§½ä½å‹ç¼©å®Œæˆï¼Œæœ€ç»ˆæ§½ä½æ•°: %d"), FormationSlots.Num());
}

void UXBFormationComponent::SetDebugDrawEnabled(bool bEnabled)
{
    bDrawDebug = bEnabled;

    if (bEnabled)
    {
        UE_LOG(LogTemp, Error, TEXT("============================================="));
        UE_LOG(LogTemp, Error, TEXT("ç¼–é˜Ÿè°ƒè¯•ç»˜åˆ¶å·²å¯ç”¨: %s"), *GetOwner()->GetName());
        UE_LOG(LogTemp, Error, TEXT("å½“å‰æ§½ä½æ•°é‡: %d"), FormationSlots.Num());
        UE_LOG(LogTemp, Error, TEXT("æ‰‹åŠ¨æ§½ä½æ•°é‡: %d"), ManualSlotCount);
        UE_LOG(LogTemp, Error, TEXT("============================================="));

        DrawDebugFormation(10.0f);
    }
    else
    {
        UE_LOG(LogTemp, Warning, TEXT("ç¼–é˜Ÿè°ƒè¯•ç»˜åˆ¶å·²ç¦ç”¨: %s"), *GetOwner()->GetName());
    }
}

void UXBFormationComponent::DrawDebugFormation(float Duration)
{
    UWorld* World = GetWorld();
    AActor* Owner = GetOwner();

    if (!World || !Owner)
    {
        return;
    }

    if (FormationSlots.Num() == 0)
    {
        UE_LOG(LogTemp, Verbose, TEXT("æ§½ä½æ•°é‡ä¸º 0ï¼Œè·³è¿‡ç»˜åˆ¶"));
        return;
    }

    FVector LeaderLocation = Owner->GetActorLocation();
    FRotator LeaderRotation = Owner->GetActorRotation();

    // ==================== ç»˜åˆ¶å°†é¢†æ ‡è®° ====================

    DrawDebugCircle(
        World,
        LeaderLocation,
        DebugLeaderRadius,
        32,
        DebugLeaderColor,
        false,
        Duration,
        0,
        5.0f,
        FVector(0, 0, 1),
        FVector(1, 0, 0)
    );

    DrawDebugSphere(
        World,
        LeaderLocation + FVector(0, 0, 100.0f),
        30.0f,
        16,
        DebugLeaderColor,
        false,
        Duration,
        0,
        3.0f
    );

    DrawDebugString(
        World,
        LeaderLocation + FVector(0, 0, 150.0f),
        FString::Printf(TEXT("å°†é¢†\næ§½ä½æ•°: %d"), FormationSlots.Num()),
        nullptr,
        FColor::White,
        Duration,
        true,
        2.0f
    );

    // ==================== ç»˜åˆ¶æ‰€æœ‰æ§½ä½ ====================

    for (int32 i = 0; i < FormationSlots.Num(); ++i)
    {
        const FXBFormationSlot& Slot = FormationSlots[i];

        FVector LocalOffset3D(Slot.LocalOffset.X, Slot.LocalOffset.Y, 0.0f);
        FVector WorldOffset = LeaderRotation.RotateVector(LocalOffset3D);
        FVector SlotWorldPos = LeaderLocation + WorldOffset;

        FColor SlotColor = Slot.bOccupied ? DebugOccupiedSlotColor : DebugFreeSlotColor;

        DrawDebugCircle(
            World,
            SlotWorldPos,
            DebugSlotRadius,
            24,
            SlotColor,
            false,
            Duration,
            0,
            4.0f,
            FVector(1, 0, 0),
            FVector(0, 1, 0)
        );

        float CrossSize = DebugSlotRadius * 0.5f;
        DrawDebugLine(
            World,
            SlotWorldPos + FVector(-CrossSize, 0, 1),
            SlotWorldPos + FVector(CrossSize, 0, 1),
            SlotColor,
            false,
            Duration,
            0,
            3.0f
        );

        DrawDebugLine(
            World,
            SlotWorldPos + FVector(0, -CrossSize, 1),
            SlotWorldPos + FVector(0, CrossSize, 1),
            SlotColor,
            false,
            Duration,
            0,
            3.0f
        );

        FString SlotText = FString::Printf(TEXT("%d"), Slot.SlotIndex);
        DrawDebugString(
            World,
            SlotWorldPos + FVector(0, 0, DebugTextHeightOffset),
            SlotText,
            nullptr,
            DebugTextColor,
            Duration,
            true,
            1.8f
        );

        DrawDebugLine(
            World,
            LeaderLocation + FVector(0, 0, 10),
            SlotWorldPos + FVector(0, 0, 10),
            DebugLineColor,
            false,
            Duration,
            0,
            2.0f
        );

        if (Slot.bOccupied && Slot.OccupantSoldierId != INDEX_NONE)
        {
            FString OccupantText = FString::Printf(TEXT("ID:%d"), Slot.OccupantSoldierId);
            DrawDebugString(
                World,
                SlotWorldPos + FVector(0, 0, DebugTextHeightOffset + 30.0f),
                OccupantText,
                nullptr,
                FColor::Cyan,
                Duration,
                true,
                1.3f
            );
        }
    }
}

void UXBFormationComponent::DrawDebugSlot(const FXBFormationSlot& Slot, const FVector& LeaderLocation, 
    const FRotator& LeaderRotation, float Duration)
{
    // å·²æ•´åˆåˆ° DrawDebugFormation
}

// ==================== ä»¥ä¸‹æ–¹æ³•ä¿æŒä¸å˜ ====================

void UXBFormationComponent::CalculateFormationDimensions(int32 SoldierCount, int32& OutColumns, int32& OutRows) const
{
    if (SoldierCount <= 0)
    {
        OutColumns = 0;
        OutRows = 0;
        return;
    }

    if (SoldierCount < 4)
    {
        OutColumns = SoldierCount;
        OutRows = 1;
        return;
    }

    OutRows = 2;
    OutColumns = 4;

    while (OutColumns * OutRows < SoldierCount)
    {
        OutRows++;
        OutColumns = OutRows * 2;

        if (OutRows > 100)
        {
            break;
        }
    }

    OutColumns = FMath::Min(OutColumns, FormationConfig.MaxColumns);

    if (OutColumns > 0)
    {
        OutRows = FMath::CeilToInt(static_cast<float>(SoldierCount) / OutColumns);
    }
}

FVector2D UXBFormationComponent::CalculateSlotLocalOffset(int32 SlotIndex, int32 TotalSoldiers, int32 Columns, int32 Rows) const
{
    if (Columns <= 0 || SlotIndex < 0)
    {
        return FVector2D::ZeroVector;
    }

    int32 Row = SlotIndex / Columns;
    int32 Column = SlotIndex % Columns;

    int32 SoldiersInThisRow = (Row == Rows - 1) ? 
        (TotalSoldiers - Row * Columns) : Columns;

    float HalfWidth = (SoldiersInThisRow - 1) * FormationConfig.HorizontalSpacing * 0.5f;

    float OffsetX = -(FormationConfig.MinDistanceToLeader + Row * FormationConfig.VerticalSpacing);
    float OffsetY = Column * FormationConfig.HorizontalSpacing - HalfWidth;

    return FVector2D(OffsetX, OffsetY);
}

void UXBFormationComponent::RegenerateFormation(int32 SoldierCount)
{
    int32 ActualSlotCount = (ManualSlotCount > 0) ? FMath::Max(ManualSlotCount, SoldierCount) : SoldierCount;

    FormationSlots.Empty();

    if (ActualSlotCount <= 0)
    {
        OnFormationUpdated.Broadcast();
        return;
    }

    int32 Columns, Rows;
    CalculateFormationDimensions(ActualSlotCount, Columns, Rows);

    FormationSlots.Reserve(ActualSlotCount);

    for (int32 i = 0; i < ActualSlotCount; ++i)
    {
        FXBFormationSlot Slot;
        Slot.SlotIndex = i;
        Slot.LocalOffset = CalculateSlotLocalOffset(i, ActualSlotCount, Columns, Rows);
        Slot.bOccupied = false;  // ğŸ”§ ä¿®æ”¹ - åˆå§‹åŒ–æ—¶ä¸æ ‡è®°å ç”¨ï¼Œç”±å¤–éƒ¨è°ƒç”¨æ—¶è®¾ç½®
        Slot.OccupantSoldierId = INDEX_NONE;
        FormationSlots.Add(Slot);
    }

    OnFormationUpdated.Broadcast();

    UE_LOG(LogTemp, Log, TEXT("ç¼–é˜Ÿç”Ÿæˆ: æ§½ä½æ•°=%d (%dx%d)"), 
        ActualSlotCount, Columns, Rows);
}

FVector UXBFormationComponent::GetSlotWorldPosition(int32 SlotIndex) const
{
    AActor* Owner = GetOwner();
    if (!Owner)
    {
        return FVector::ZeroVector;
    }

    FVector LeaderLocation = Owner->GetActorLocation();
    
    if (!FormationSlots.IsValidIndex(SlotIndex))
    {
        return LeaderLocation;
    }

    const FXBFormationSlot& Slot = FormationSlots[SlotIndex];

    FVector LocalOffset3D(Slot.LocalOffset.X, Slot.LocalOffset.Y, 0.0f);
    FVector WorldOffset = Owner->GetActorRotation().RotateVector(LocalOffset3D);
    
    FVector TargetXY = LeaderLocation + WorldOffset;
    
    UWorld* World = GetWorld();
    if (World)
    {
        FHitResult HitResult;
        
        FVector TraceStart = FVector(TargetXY.X, TargetXY.Y, LeaderLocation.Z + 500.0f);
        FVector TraceEnd = FVector(TargetXY.X, TargetXY.Y, LeaderLocation.Z - 1000.0f);

        FCollisionQueryParams QueryParams;
        QueryParams.AddIgnoredActor(Owner);

        bool bHit = World->LineTraceSingleByChannel(
            HitResult,
            TraceStart,
            TraceEnd,
            ECC_WorldStatic,
            QueryParams
        );

        if (bHit)
        {
            return HitResult.Location; 
        }
    }

    return FVector(TargetXY.X, TargetXY.Y, LeaderLocation.Z);
}

int32 UXBFormationComponent::GetFirstAvailableSlot() const
{
    for (int32 i = 0; i < FormationSlots.Num(); ++i)
    {
        if (!FormationSlots[i].bOccupied)
        {
            return i;
        }
    }
    return INDEX_NONE;
}

bool UXBFormationComponent::OccupySlot(int32 SlotIndex, int32 SoldierId)
{
    if (!FormationSlots.IsValidIndex(SlotIndex))
    {
        return false;
    }

    FXBFormationSlot& Slot = FormationSlots[SlotIndex];
    if (Slot.bOccupied)
    {
        return false;
    }

    Slot.bOccupied = true;
    Slot.OccupantSoldierId = SoldierId;
    return true;
}

bool UXBFormationComponent::ReleaseSlot(int32 SlotIndex)
{
    if (!FormationSlots.IsValidIndex(SlotIndex))
    {
        return false;
    }

    FXBFormationSlot& Slot = FormationSlots[SlotIndex];
    Slot.bOccupied = false;
    Slot.OccupantSoldierId = INDEX_NONE;
    return true;
}

void UXBFormationComponent::ReleaseAllSlots()
{
    for (FXBFormationSlot& Slot : FormationSlots)
    {
        Slot.bOccupied = false;
        Slot.OccupantSoldierId = INDEX_NONE;
    }
}

/**
 * @brief ä¸ºå£«å…µåˆ†é…æ§½ä½
 * @param Soldier å£«å…µ
 * @return åˆ†é…çš„æ§½ä½ç´¢å¼•
 * @note ğŸ”§ ä¿®æ”¹ - ä¼˜åŒ–åˆ†é…é€»è¾‘ï¼Œç¡®ä¿é¡ºåºåˆ†é…
 */
int32 UXBFormationComponent::AssignSlotToSoldier(AXBSoldierCharacter* Soldier)
{
    if (!Soldier)
    {
        return INDEX_NONE;
    }

    // ğŸ”§ ä¿®æ”¹ - ä¼˜å…ˆä½¿ç”¨ GetFirstAvailableSlot ç¡®ä¿ä»å¤´å¼€å§‹åˆ†é…
    int32 SlotIndex = GetFirstAvailableSlot();
    
    if (SlotIndex == INDEX_NONE)
    {
        // æ²¡æœ‰å¯ç”¨æ§½ä½ï¼Œæ‰©å±•
        int32 NewSlotCount = FormationSlots.Num() + 1;
        RegenerateFormation(NewSlotCount);
        SlotIndex = FormationSlots.Num() - 1;
    }

    if (OccupySlot(SlotIndex, Soldier->GetUniqueID()))
    {
        Soldier->SetFormationSlotIndex(SlotIndex);
        
        UE_LOG(LogTemp, Log, TEXT("å£«å…µ %s åˆ†é…åˆ°æ§½ä½ %d"), *Soldier->GetName(), SlotIndex);
        return SlotIndex;
    }

    return INDEX_NONE;
}

void UXBFormationComponent::RemoveSoldierFromSlot(AXBSoldierCharacter* Soldier)
{
    if (!Soldier)
    {
        return;
    }

    int32 SlotIndex = Soldier->GetFormationSlotIndex();
    if (SlotIndex != INDEX_NONE)
    {
        ReleaseSlot(SlotIndex);
    }
}

/**
 * @brief é‡æ–°åˆ†é…æ‰€æœ‰æ§½ä½
 * @param Soldiers å£«å…µæ•°ç»„
 * @note ğŸ”§ ä¿®æ”¹ - è°ƒç”¨ CompactSlots ç¡®ä¿æ§½ä½è¿ç»­
 */
void UXBFormationComponent::ReassignAllSlots(const TArray<AXBSoldierCharacter*>& Soldiers)
{
    ReleaseAllSlots();
    CompactSlots(Soldiers);

    UE_LOG(LogTemp, Warning, TEXT("â˜…â˜…â˜… ç¼–é˜Ÿé‡æ–°åˆ†é…: %dä¸ªå£«å…µ â˜…â˜…â˜…"), Soldiers.Num());
}

void UXBFormationComponent::SetFormationConfig(const FXBFormationConfig& NewConfig)
{
    FormationConfig = NewConfig;

    if (FormationSlots.Num() > 0)
    {
        RegenerateFormation(FormationSlots.Num());
    }
}
