/* --- å®Œæ•´æ–‡ä»¶ä»£ç  --- */
// Source/XiaoBinDaTianXia/Private/Combat/XBProjectile.cpp

/**
 * @file XBProjectile.cpp
 * @brief è¿œç¨‹æŠ•å°„ç‰©åŸºç±»å®ç° - æ”¯æŒç›´çº¿ä¸æŠ›å°„æ¨¡å¼
 * 
 * @note âœ¨ æ–°å¢æ–‡ä»¶
 */

#include "Combat/XBProjectile.h"
#include "AbilitySystemComponent.h"
#include "AbilitySystemGlobals.h"
#include "Components/CapsuleComponent.h"
#include "Components/StaticMeshComponent.h"
#include "GameFramework/ProjectileMovementComponent.h"
#include "Combat/XBProjectilePoolSubsystem.h"
#include "GAS/XBAttributeSet.h"
#include "Soldier/XBSoldierCharacter.h"
#include "Character/XBCharacterBase.h"
#include "Utils/XBBlueprintFunctionLibrary.h"
#include "Utils/XBLogCategories.h"
#include "XBCollisionChannels.h"

AXBProjectile::AXBProjectile()
{
    PrimaryActorTick.bCanEverTick = false;

    CollisionComponent = CreateDefaultSubobject<UCapsuleComponent>(TEXT("CollisionComponent"));
    CollisionComponent->InitCapsuleSize(12.0f, 24.0f);
    CollisionComponent->SetCollisionEnabled(ECollisionEnabled::QueryOnly);
    CollisionComponent->SetCollisionObjectType(ECC_WorldDynamic);
    CollisionComponent->SetCollisionResponseToAllChannels(ECR_Ignore);
    CollisionComponent->SetCollisionResponseToChannel(XBCollision::Soldier, ECR_Overlap);
    CollisionComponent->SetCollisionResponseToChannel(XBCollision::Leader, ECR_Overlap);
    CollisionComponent->SetGenerateOverlapEvents(true);
    RootComponent = CollisionComponent;

    MeshComponent = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("MeshComponent"));
    MeshComponent->SetupAttachment(CollisionComponent);
    MeshComponent->SetCollisionEnabled(ECollisionEnabled::NoCollision);

    ProjectileMovementComponent = CreateDefaultSubobject<UProjectileMovementComponent>(TEXT("ProjectileMovementComponent"));
    ProjectileMovementComponent->InitialSpeed = LinearSpeed;
    ProjectileMovementComponent->MaxSpeed = LinearSpeed;
    ProjectileMovementComponent->bRotationFollowsVelocity = true;
    ProjectileMovementComponent->ProjectileGravityScale = 0.0f;

    DamageTag = FGameplayTag::RequestGameplayTag(FName("Data.Damage"), false);
}

void AXBProjectile::BeginPlay()
{
    Super::BeginPlay();

    if (CollisionComponent)
    {
        CollisionComponent->OnComponentBeginOverlap.AddDynamic(this, &AXBProjectile::OnProjectileOverlap);
    }
}

void AXBProjectile::InitializeProjectile(AActor* InSourceActor, float InDamage, const FVector& ShootDirection, float InSpeed, bool bInUseArc)
{
    SourceActor = InSourceActor;
    Damage = InDamage;
    bUseArc = bInUseArc;

    const float FinalSpeed = InSpeed > 0.0f ? InSpeed : LinearSpeed;
    ProjectileMovementComponent->InitialSpeed = FinalSpeed;
    ProjectileMovementComponent->MaxSpeed = FinalSpeed;

    // ğŸ”§ ä¿®æ”¹ - ä½¿ç”¨ç›®æ ‡æ–¹å‘è®¡ç®—é€Ÿåº¦ï¼Œå¹¶åŒæ­¥æ—‹è½¬ï¼Œä¿è¯èƒ¶å›Šä½“æœé£è¡Œæ–¹å‘å¯¹é½
    FVector Velocity = ShootDirection.GetSafeNormal() * FinalSpeed;
    if (bUseArc)
    {
        ProjectileMovementComponent->ProjectileGravityScale = ArcGravityScale;
        Velocity.Z += ArcLaunchSpeed;
    }
    else
    {
        ProjectileMovementComponent->ProjectileGravityScale = 0.0f;
    }

    ProjectileMovementComponent->Velocity = Velocity;

    // ğŸ”§ ä¿®æ”¹ - ä»¥é£è¡Œæ–¹å‘æ›´æ–°Actoræ—‹è½¬ï¼Œé¿å…èƒ¶å›Šä½“ä¸é€Ÿåº¦æ–¹å‘ä¸ä¸€è‡´
    SetActorRotation(Velocity.Rotation());

    UE_LOG(LogXBCombat, Log, TEXT("æŠ•å°„ç‰©åˆå§‹åŒ–: æ¥æº=%s ä¼¤å®³=%.1f æ¨¡å¼=%s é€Ÿåº¦=%.1f"),
        InSourceActor ? *InSourceActor->GetName() : TEXT("æ— "),
        Damage,
        bUseArc ? TEXT("æŠ›å°„") : TEXT("ç›´çº¿"),
        FinalSpeed);
}

void AXBProjectile::ActivateFromPool(const FVector& SpawnLocation, const FRotator& SpawnRotation)
{
    SetActorHiddenInGame(false);
    SetActorEnableCollision(true);
    SetActorLocation(SpawnLocation);
    SetActorRotation(SpawnRotation);

    if (ProjectileMovementComponent)
    {
        ProjectileMovementComponent->StopMovementImmediately();
    }
}

void AXBProjectile::ResetForPooling()
{
    if (ProjectileMovementComponent)
    {
        ProjectileMovementComponent->StopMovementImmediately();
    }

    SetActorEnableCollision(false);
    SetActorHiddenInGame(true);

    SourceActor = nullptr;

    UE_LOG(LogXBCombat, Verbose, TEXT("æŠ•å°„ç‰© %s å·²é‡ç½®å¹¶è¿›å…¥æ± åŒ–ä¼‘çœ "), *GetName());
}

void AXBProjectile::OnProjectileOverlap(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor,
    UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult)
{
    if (!OtherActor || OtherActor == this)
    {
        return;
    }

    if (SourceActor.IsValid() && OtherActor == SourceActor.Get())
    {
        return;
    }

    ApplyDamageToTarget(OtherActor, SweepResult);

    if (bDestroyOnHit)
    {
        if (bUsePooling)
        {
            if (UWorld* World = GetWorld())
            {
                if (UXBProjectilePoolSubsystem* PoolSubsystem = World->GetSubsystem<UXBProjectilePoolSubsystem>())
                {
                    PoolSubsystem->ReleaseProjectile(this);
                    return;
                }
            }
        }

        Destroy();
    }
}

void AXBProjectile::ApplyDamageToTarget(AActor* TargetActor, const FHitResult& HitResult)
{
    if (!TargetActor)
    {
        return;
    }

    AActor* Source = SourceActor.Get();
    if (!Source)
    {
        UE_LOG(LogXBCombat, Warning, TEXT("æŠ•å°„ç‰©å‘½ä¸­ %sï¼Œä½†æ²¡æœ‰æœ‰æ•ˆçš„æ¥æº"), *TargetActor->GetName());
        return;
    }

    EXBFaction SourceFaction = EXBFaction::Neutral;
    if (AXBSoldierCharacter* SourceSoldier = Cast<AXBSoldierCharacter>(Source))
    {
        SourceFaction = SourceSoldier->GetFaction();
    }
    else if (AXBCharacterBase* SourceLeader = Cast<AXBCharacterBase>(Source))
    {
        SourceFaction = SourceLeader->GetFaction();
    }

    EXBFaction TargetFaction = EXBFaction::Neutral;
    if (!GetTargetFaction(TargetActor, TargetFaction))
    {
        return;
    }

    if (!UXBBlueprintFunctionLibrary::AreFactionsHostile(SourceFaction, TargetFaction))
    {
        // ğŸ”§ ä¿®æ”¹ - åªå¯¹æ•Œäººç”Ÿæ•ˆï¼Œå‹å†›ç›´æ¥å¿½ç•¥
        UE_LOG(LogXBCombat, Verbose, TEXT("æŠ•å°„ç‰©å¿½ç•¥å‹å†›: %s -> %s"), *Source->GetName(), *TargetActor->GetName());
        return;
    }

    if (AXBSoldierCharacter* TargetSoldier = Cast<AXBSoldierCharacter>(TargetActor))
    {
        float ActualDamage = TargetSoldier->TakeSoldierDamage(Damage, Source);
        UE_LOG(LogXBCombat, Log, TEXT("æŠ•å°„ç‰©å‘½ä¸­å£«å…µ: %s, ä¼¤å®³: %.1f, å®é™…: %.1f"),
            *TargetActor->GetName(), Damage, ActualDamage);
        return;
    }

    AXBCharacterBase* TargetLeader = Cast<AXBCharacterBase>(TargetActor);
    if (!TargetLeader)
    {
        return;
    }

    if (AXBCharacterBase* SourceLeader = Cast<AXBCharacterBase>(Source))
    {
        SourceLeader->OnAttackHit(TargetLeader);
    }

    UAbilitySystemComponent* SourceASC = UAbilitySystemGlobals::GetAbilitySystemComponentFromActor(Source);
    UAbilitySystemComponent* TargetASC = UAbilitySystemGlobals::GetAbilitySystemComponentFromActor(TargetActor);

    if (!TargetASC)
    {
        UE_LOG(LogXBCombat, Warning, TEXT("æŠ•å°„ç‰©å‘½ä¸­ %sï¼Œä½†ç›®æ ‡æ²¡æœ‰ASC"), *TargetActor->GetName());
        return;
    }

    if (DamageEffectClass && SourceASC)
    {
        FGameplayEffectContextHandle ContextHandle = SourceASC->MakeEffectContext();
        ContextHandle.AddSourceObject(Source);
        ContextHandle.AddHitResult(HitResult);

        FGameplayEffectSpecHandle SpecHandle = SourceASC->MakeOutgoingSpec(DamageEffectClass, 1.0f, ContextHandle);
        if (SpecHandle.IsValid())
        {
            if (DamageTag.IsValid())
            {
                SpecHandle.Data->SetSetByCallerMagnitude(DamageTag, Damage);
            }
            else
            {
                UE_LOG(LogXBCombat, Warning, TEXT("æŠ•å°„ç‰©ä¼¤å®³Tagæ— æ•ˆ(Data.Damage)ï¼Œç›®æ ‡=%s"), *TargetActor->GetName());
            }

            SourceASC->ApplyGameplayEffectSpecToTarget(*SpecHandle.Data, TargetASC);

            UE_LOG(LogXBCombat, Log, TEXT("æŠ•å°„ç‰©å‘½ä¸­å°†é¢†: %s, ä¼¤å®³: %.1f (GAS)"),
                *TargetActor->GetName(), Damage);
        }
    }
    else
    {
        TargetASC->SetNumericAttributeBase(UXBAttributeSet::GetIncomingDamageAttribute(), Damage);
        UE_LOG(LogXBCombat, Log, TEXT("æŠ•å°„ç‰©å‘½ä¸­å°†é¢†: %s, ä¼¤å®³: %.1f (ç›´æ¥å±æ€§)"),
            *TargetActor->GetName(), Damage);
    }
}

bool AXBProjectile::GetTargetFaction(AActor* TargetActor, EXBFaction& OutFaction) const
{
    if (AXBSoldierCharacter* TargetSoldier = Cast<AXBSoldierCharacter>(TargetActor))
    {
        OutFaction = TargetSoldier->GetFaction();
        return true;
    }

    if (AXBCharacterBase* TargetLeader = Cast<AXBCharacterBase>(TargetActor))
    {
        OutFaction = TargetLeader->GetFaction();
        return true;
    }

    return false;
}
