/* --- å®Œæ•´æ–‡ä»¶ä»£ç  --- */
// Source/XiaoBinDaTianXia/Private/Soldier/Component/XBSoldierFollowComponent.cpp

/**
 * @file XBSoldierFollowComponent.cpp
 * @brief å£«å…µè·Ÿéšç»„ä»¶å®ç° - å®æ—¶é”å®šæ§½ä½
 *
 * @note ğŸ”§ ä¿®æ”¹è®°å½•:
 *       1. ğŸ”§ ä¿®å¤ GhostRotationInterpSpeed è¿‡ä½å¯¼è‡´çš„æŠ–åŠ¨ï¼š
 *          - æ§½ä½ä½ç½®è®¡ç®—é»˜è®¤ä½¿ç”¨ä¸»å°†å³æ—¶Yawï¼ˆæ— æ—‹è½¬å»¶è¿Ÿï¼‰
 *          - å¹½çµYawé‡‡ç”¨è§’åº¦å®‰å…¨çš„æŒ‡æ•°å¹³æ»‘æ’å€¼ï¼ˆé¿å… 0/360 æŠ–åŠ¨ï¼‰
 *       2. ğŸ”§ é”å®šæ¨¡å¼ç»Ÿä¸€ä½¿ç”¨ AddMovementInputï¼Œå‡å°‘è¾“å…¥å‘é‡å·®å¼‚å¯¼è‡´çš„æ‘†åŠ¨
 */

#include "Soldier/Component/XBSoldierFollowComponent.h"
#include "Utils/XBLogCategories.h"
#include "Character/XBCharacterBase.h"
#include "Character/Components/XBFormationComponent.h"
#include "Soldier/XBSoldierCharacter.h"
#include "GameFramework/Character.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "Components/CapsuleComponent.h"

UXBSoldierFollowComponent::UXBSoldierFollowComponent()
{
    PrimaryComponentTick.bCanEverTick = true;
    PrimaryComponentTick.bStartWithTickEnabled = true;
}

void UXBSoldierFollowComponent::BeginPlay()
{
    Super::BeginPlay();

    GetCachedMovementComponent();
    GetCachedCapsuleComponent();

    if (AActor* Owner = GetOwner())
    {
        LastFrameLocation = Owner->GetActorLocation();
        LastPositionForStuckCheck = LastFrameLocation;
    }

    SetMovementMode(true);

    UE_LOG(LogXBSoldier, Log, TEXT("è·Ÿéšç»„ä»¶åˆå§‹åŒ–å®Œæˆï¼šè¿½èµ¶è¡¥å¿å€ç‡=%.2fï¼Œæ§½ä½å³æ—¶Yaw=%s"),
        CatchUpSpeedMultiplier,
        bUseInstantLeaderYawForSlot ? TEXT("å¯ç”¨") : TEXT("ç¦ç”¨"));
}

void UXBSoldierFollowComponent::TickComponent(float DeltaTime, ELevelTick TickType,
    FActorComponentTickFunction* ThisTickFunction)
{
    Super::TickComponent(DeltaTime, TickType, ThisTickFunction);

    AActor* Owner = GetOwner();
    if (!Owner)
    {
        CurrentMoveSpeed = 0.0f;
        return;
    }

    // æ£€æŸ¥å£«å…µæ˜¯å¦å·²æ­»äº¡ï¼Œæ­»äº¡åˆ™ä¸æ›´æ–°
    if (AXBSoldierCharacter* Soldier = Cast<AXBSoldierCharacter>(Owner))
    {
        if (Soldier->IsDead())
        {
            CurrentMoveSpeed = 0.0f;
            return;
        }
    }

    // è‡ªç”±æ¨¡å¼ï¼šæˆ˜æ–—ä¸­ï¼Œä¸æ§åˆ¶ä½ç½®
    if (CurrentMode == EXBFollowMode::Free)
    {
        if (UCharacterMovementComponent* MoveComp = GetCachedMovementComponent())
        {
            FVector Velocity = MoveComp->Velocity;
            Velocity.Z = 0.0f;
            CurrentMoveSpeed = Velocity.Size();
        }
        LastFrameLocation = Owner->GetActorLocation();
        return;
    }

    // æ²¡æœ‰è·Ÿéšç›®æ ‡
    if (!FollowTargetRef.IsValid())
    {
        CurrentMoveSpeed = 0.0f;
        LastFrameLocation = Owner->GetActorLocation();
        return;
    }

    // æ›´æ–°å¹½çµç›®æ ‡ï¼ˆä½ç½®ä¸Yawï¼‰ï¼Œç”¨äºå¹³æ»‘ç¼–é˜Ÿ
    UpdateGhostTarget(DeltaTime);

    // æ¯å¸§æ›´æ–°å°†é¢†é€Ÿåº¦ç¼“å­˜ï¼ˆç”¨äºæ‹›å‹Ÿè¿‡æ¸¡æ¨¡å¼ï¼‰
    if (bSyncLeaderSprint && CurrentMode == EXBFollowMode::RecruitTransition)
    {
        CachedLeaderSpeed = GetLeaderCurrentSpeed();

        if (CachedLeaderCharacter.IsValid())
        {
            bLeaderIsSprinting = CachedLeaderCharacter->IsSprinting();
        }
    }

    FVector PreUpdateLocation = Owner->GetActorLocation();

    switch (CurrentMode)
    {
    case EXBFollowMode::Locked:
        UpdateLockedMode(DeltaTime);
        break;

    case EXBFollowMode::RecruitTransition:
        UpdateRecruitTransitionMode(DeltaTime);
        break;

    default:
        break;
    }

    // è®¡ç®—å®é™…ç§»åŠ¨é€Ÿåº¦ï¼ˆç”¨äºåŠ¨ç”»ç­‰ï¼‰
    if (DeltaTime > KINDA_SMALL_NUMBER)
    {
        FVector CurrentLocation = Owner->GetActorLocation();
        FVector Delta = CurrentLocation - PreUpdateLocation;
        Delta.Z = 0.0f;
        CurrentMoveSpeed = Delta.Size() / DeltaTime;
    }

    LastFrameLocation = Owner->GetActorLocation();
}

void UXBSoldierFollowComponent::SyncLeaderSprintState(bool bLeaderSprinting, float LeaderCurrentSpeed)
{
    bLeaderIsSprinting = bLeaderSprinting;
    CachedLeaderSpeed = LeaderCurrentSpeed;

    UE_LOG(LogXBSoldier, Log, TEXT("è·Ÿéšç»„ä»¶ï¼šåŒæ­¥å°†é¢†çŠ¶æ€ï¼Œå†²åˆº=%sï¼Œé€Ÿåº¦=%.1f"),
        bLeaderSprinting ? TEXT("æ˜¯") : TEXT("å¦"),
        LeaderCurrentSpeed);
}

float UXBSoldierFollowComponent::GetLeaderCurrentSpeed() const
{
    if (!CachedLeaderCharacter.IsValid())
    {
        return 0.0f;
    }

    AXBCharacterBase* Leader = CachedLeaderCharacter.Get();
    if (!Leader || !IsValid(Leader))
    {
        return 0.0f;
    }

    return Leader->GetCurrentMoveSpeed();
}

float UXBSoldierFollowComponent::CalculateRecruitTransitionSpeed(float DistanceToTarget) const
{
    float LeaderSpeed = CachedLeaderSpeed;
    if (LeaderSpeed < KINDA_SMALL_NUMBER && CachedLeaderCharacter.IsValid())
    {
        LeaderSpeed = GetLeaderCurrentSpeed();
    }

    if (CloseSlowdownDistance > 0.0f && DistanceToTarget <= CloseSlowdownDistance)
    {
        float CloseAlpha = 1.0f - FMath::Clamp(DistanceToTarget / CloseSlowdownDistance, 0.0f, 1.0f);

        float TargetSpeed = FMath::Max(LeaderSpeed, MinTransitionSpeed);

        float BaseApproachSpeed = RecruitTransitionSpeed;
        float FinalSpeed = FMath::Lerp(BaseApproachSpeed, TargetSpeed, CloseAlpha);

        FinalSpeed = FMath::Max(FinalSpeed, MinTransitionSpeed);

        if (DistanceToTarget < 50.0f && LeaderSpeed > KINDA_SMALL_NUMBER)
        {
            FinalSpeed = FMath::Min(FinalSpeed, LeaderSpeed * 1.1f);
        }

        return FinalSpeed;
    }

    const float NormalizedDistance = FMath::Clamp(DistanceToTarget / FMath::Max(ArrivalThreshold, 1.0f), 0.0f, 10.0f);
    float DistanceMultiplier = 1.0f + NormalizedDistance * DistanceSpeedMultiplier;
    DistanceMultiplier = FMath::Max(DistanceMultiplier, 1.0f);
    float DistanceBasedSpeed = RecruitTransitionSpeed * DistanceMultiplier;

    float LeaderBasedSpeed = 0.0f;
    if (bSyncLeaderSprint && LeaderSpeed > KINDA_SMALL_NUMBER)
    {
        LeaderBasedSpeed = LeaderSpeed * CatchUpSpeedMultiplier;

        if (bLeaderIsSprinting)
        {
            LeaderBasedSpeed *= 1.2f;
        }
    }

    float FinalSpeed = FMath::Max(DistanceBasedSpeed, LeaderBasedSpeed);
    FinalSpeed = FMath::Clamp(FinalSpeed, MinTransitionSpeed, MaxTransitionSpeed);

    return FinalSpeed;
}

bool UXBSoldierFollowComponent::IsRotationAligned(const FRotator& TargetRotation, float ToleranceDegrees) const
{
    AActor* Owner = GetOwner();
    if (!Owner)
    {
        return true;
    }

    FRotator CurrentRotation = Owner->GetActorRotation();
    float YawDiff = FMath::Abs(FRotator::NormalizeAxis(CurrentRotation.Yaw - TargetRotation.Yaw));
    return YawDiff <= ToleranceDegrees;
}

/**
 * @brief æ›´æ–°é”å®šæ¨¡å¼
 * @param DeltaTime å¸§é—´éš”
 * @note  ğŸ”§ ä¿®å¤ç‚¹ï¼š
 *        1) ä¸å†ä½¿ç”¨ SetActorLocation æ­¥è¿›ï¼ˆé‚£ä¼šè®©ç§»åŠ¨ç»„ä»¶é€Ÿåº¦ä¸º0ï¼Œçœ‹èµ·æ¥åƒç²˜ä½ä¸»å°†ï¼‰
 *        2) æ”¹ç”¨ AddMovementInput é©±åŠ¨ CharacterMovementï¼Œä¿è¯æœ‰çœŸå®é€Ÿåº¦/åŠ é€Ÿåº¦
 *        3) ä½¿ç”¨â€œæ­»åŒº + è¾“å…¥æŒ‰è¯¯å·®ç¼©æ”¾ + MaxWalkSpeed æ’å€¼â€é¿å…å¾®æŠ–ä¸æŒ¤å‹
 */
void UXBSoldierFollowComponent::UpdateLockedMode(float DeltaTime)
{
   AActor* Owner = GetOwner();
    AActor* Leader = FollowTargetRef.Get();

    if (!Owner || !Leader || !IsValid(Leader))
    {
        return;
    }

    ACharacter* CharOwner = Cast<ACharacter>(Owner);
    UCharacterMovementComponent* MoveComp = GetCachedMovementComponent();
    if (!CharOwner || !MoveComp)
    {
        return;
    }

    const FVector TargetPosition = GetSmoothedFormationTarget();
    const FVector CurrentPosition = Owner->GetActorLocation();
    const float DistanceToSlot = FVector::Dist2D(CurrentPosition, TargetPosition);

    // ========== é€Ÿåº¦ç­–ç•¥ ==========
    float LeaderSpeed = 0.0f;
    if (CachedLeaderCharacter.IsValid())
    {
        LeaderSpeed = CachedLeaderCharacter->GetCurrentMoveSpeed();
    }

    // ğŸ”§ ä¿®æ”¹ - ç›®æ ‡é€Ÿåº¦ï¼šè‡³å°‘ä¸ä½äº LockedFollowMoveSpeedï¼Œå¹¶å…è®¸ä¸€å®šè¿½èµ¶ä½™é‡ï¼ˆä¿æŒè·Ÿéšæ„Ÿä½†ä¸â€œè´´æ­»â€ï¼‰
    const float DesiredSpeed = FMath::Max(LockedFollowMoveSpeed, LeaderSpeed + LockedCatchUpExtraSpeed);

    // é€Ÿåº¦æ’å€¼ï¼šé¿å…é€Ÿåº¦çªè·³äº§ç”Ÿé¡¿æŒ«
    const float NewMaxSpeed = (LockedSpeedInterpRate > 0.0f)
        ? FMath::FInterpTo(MoveComp->MaxWalkSpeed, DesiredSpeed, DeltaTime, LockedSpeedInterpRate)
        : DesiredSpeed;

    MoveComp->MaxWalkSpeed = NewMaxSpeed;

    // ========== è¯¯å·®é©±åŠ¨ç§»åŠ¨ï¼šæ­»åŒº + è¾“å…¥ç¼©æ”¾ ==========
    if (DistanceToSlot > LockedDeadzoneDistance)
    {
        const FVector MoveDir = (TargetPosition - CurrentPosition).GetSafeNormal2D();
        if (!MoveDir.IsNearlyZero())
        {
            // ä¸ºä»€ä¹ˆæŒ‰è¯¯å·®ç¼©æ”¾è¾“å…¥ï¼šè¯¯å·®è¶Šå°è¶Šä¸æŠ¢ä½ï¼Œå‡å°‘â€œæŒ¤æˆå›¢â€å’ŒæŠ–è…¿
            const float InputAlpha = FMath::Clamp(DistanceToSlot / FMath::Max(LockedFullInputDistance, 1.0f), 0.0f, 1.0f);
            CharOwner->AddMovementInput(MoveDir, InputAlpha);
        }
    }

    // ========== æœå‘ï¼šé”å®šæ¨¡å¼å§‹ç»ˆé¢å‘é˜Ÿä¼å‰æ–¹ ==========
    if (bFollowRotation)
    {
        const FRotator TargetRotation = CalculateFormationWorldRotation();
        const FRotator NewRotation = FMath::RInterpTo(
            Owner->GetActorRotation(),
            TargetRotation,
            DeltaTime,
            LockedRotationInterpSpeed
        );
        Owner->SetActorRotation(FRotator(0.0f, NewRotation.Yaw, 0.0f));
    }
}
/**
 * @brief æ›´æ–°æ‹›å‹Ÿè¿‡æ¸¡æ¨¡å¼
 * @param DeltaTime å¸§é—´éš”
 * @note  ğŸ”§ ä¿®å¤ç‚¹ï¼š
 *        1) å–æ¶ˆâ€œæ¥è¿‘æ§½ä½ç«‹å³åˆ‡çŠ¶æ€â€çš„ç¡¬åˆ‡ï¼Œæ”¹ä¸ºåˆ°è¾¾ç¡®è®¤æ—¶é—´ï¼ˆæ»å›ï¼‰ï¼Œæ¶ˆé™¤é¡¿æŒ«
 *        2) æ—‹è½¬é‡‡ç”¨â€œç§»åŠ¨æ–¹å‘ -> é˜Ÿä¼å‰æ–¹â€çš„è·ç¦»æ¸å˜æ··åˆï¼Œé¿å…ä¸´ç•Œç‚¹çªç„¶è½¬å‘
 *        3) ä½ç§»ç”± CharacterMovement é©±åŠ¨ï¼Œé€Ÿåº¦ç”¨æ’å€¼å¹³æ»‘ï¼Œè§†è§‰æ›´ä¸æ»‘ä¸”æœ‰é€Ÿåº¦æ„Ÿ
 */
void UXBSoldierFollowComponent::UpdateRecruitTransitionMode(float DeltaTime)
{
    AActor* Owner = GetOwner();
    AActor* Leader = FollowTargetRef.Get();

    if (!Owner || !Leader || !IsValid(Leader))
    {
        return;
    }

    if (!bRecruitMovementActive)
    {
        return;
    }

    ACharacter* CharOwner = Cast<ACharacter>(Owner);
    UCharacterMovementComponent* MoveComp = GetCachedMovementComponent();
    if (!CharOwner || !MoveComp)
    {
        return;
    }

    const FVector TargetPosition = GetSmoothedFormationTarget();
    const FVector CurrentPosition = Owner->GetActorLocation();
    const float Distance = FVector::Dist2D(CurrentPosition, TargetPosition);

    // ========= åˆ°è¾¾é˜ˆå€¼åŠ¨æ€è°ƒæ•´ï¼ˆä¸»å°†ç§»åŠ¨æ—¶æ”¾å®½ï¼‰=========
    float EffectiveArrivalThreshold = ArrivalThreshold;

    float LeaderSpeed = 0.0f;
    if (CachedLeaderCharacter.IsValid())
    {
        LeaderSpeed = CachedLeaderCharacter->GetCurrentMoveSpeed();
    }

    if (LeaderSpeed > 50.0f)
    {
        EffectiveArrivalThreshold = ArrivalThreshold * 1.5f;
    }

    // ========= è¿½èµ¶é€Ÿåº¦è®¡ç®— + å¹³æ»‘ =========
    float DesiredSpeed = CalculateRecruitTransitionSpeed(Distance);
    DesiredSpeed = FMath::Clamp(DesiredSpeed, MinTransitionSpeed, MaxTransitionSpeed);

    if (SmoothedSpeedCache <= KINDA_SMALL_NUMBER)
    {
        SmoothedSpeedCache = DesiredSpeed;
    }

    if (bUseSpeedSmoothing && SpeedSmoothingRate > 0.0f)
    {
        SmoothedSpeedCache = FMath::FInterpTo(SmoothedSpeedCache, DesiredSpeed, DeltaTime, SpeedSmoothingRate);
        DesiredSpeed = SmoothedSpeedCache;
    }

    // ğŸ”§ ä¿®æ”¹ - å†å¯¹ MaxWalkSpeed åšä¸€æ¬¡æ’å€¼ï¼Œå‡å°‘â€œå³å°†åˆ°ä½æ—¶é€Ÿåº¦å˜åŒ–â€çš„é¡¿æŒ«
    const float NewMaxSpeed = FMath::FInterpTo(MoveComp->MaxWalkSpeed, DesiredSpeed, DeltaTime, 12.0f);
    MoveComp->MaxWalkSpeed = NewMaxSpeed;

    // ========= ä½ç§»ä¸æ—‹è½¬ =========
    if (Distance > EffectiveArrivalThreshold)
    {
        ArrivedTimeAccumulator = 0.0f;

        const FVector MoveDirection = (TargetPosition - CurrentPosition).GetSafeNormal2D();
        if (!MoveDirection.IsNearlyZero())
        {
            CharOwner->AddMovementInput(MoveDirection, 1.0f);

            // ========= æ—‹è½¬ï¼šç§»åŠ¨æ–¹å‘ -> é˜Ÿä¼å‰æ–¹ æ¸å˜æ··åˆ =========
            if (bFollowRotation)
            {
                const float BlendDist = FMath::Max(RecruitRotationBlendDistance, 1.0f);

                // BlendAlphaï¼šè¶Šæ¥è¿‘æ§½ä½è¶Šè¶‹å‘é˜Ÿä¼å‰æ–¹
                const float BlendAlpha = 1.0f - FMath::Clamp(Distance / BlendDist, 0.0f, 1.0f);

                const float MoveYaw = MoveDirection.Rotation().Yaw;
                const float FormationYaw = CalculateFormationWorldRotation().Yaw;

                // è§’åº¦å®‰å…¨æ··åˆï¼šé¿å… 179->-179 æŠ–åŠ¨
                const float YawDelta = FMath::FindDeltaAngleDegrees(MoveYaw, FormationYaw);
                const float BlendedYaw = FRotator::NormalizeAxis(MoveYaw + YawDelta * BlendAlpha);

                const FRotator TargetRot(0.0f, BlendedYaw, 0.0f);

                // è½¬å‘é€Ÿåº¦ä¹Ÿåšæ¸å˜ï¼šè¿œå¤„æ›´å¿«æœç§»åŠ¨æ–¹å‘ï¼Œè¿‘å¤„æ›´æŸ”å’Œå¯¹é½é˜Ÿä¼å‰æ–¹
                const float RotSpeed = FMath::Lerp(MoveDirectionRotationSpeed, AlignmentRotationSpeed, BlendAlpha);

                const FRotator NewRot = FMath::RInterpTo(Owner->GetActorRotation(), TargetRot, DeltaTime, RotSpeed);
                Owner->SetActorRotation(FRotator(0.0f, NewRot.Yaw, 0.0f));
            }
        }
    }
    else
    {
        // åœ¨åˆ°è¾¾é˜ˆå€¼å†…ï¼šç´¯è®¡ç¡®è®¤æ—¶é—´ï¼ˆæ»å›ï¼‰ï¼Œé¿å…è¾¹ç•ŒæŠ–åŠ¨å¯¼è‡´â€œé¡¿æŒ«/æ‰å¸§æ„Ÿâ€
        ArrivedTimeAccumulator += DeltaTime;

        // å°å¹…è¡¥ä½ï¼ˆä¸»å°†ä»åœ¨ç§»åŠ¨/æ—‹è½¬æ—¶é¿å…æ…¢æ…¢åç¦»ï¼‰
        const FVector MicroDir = (TargetPosition - CurrentPosition).GetSafeNormal2D();
        if (!MicroDir.IsNearlyZero())
        {
            CharOwner->AddMovementInput(MicroDir, 0.25f);
        }

        // æŒç»­å¯¹é½é˜Ÿä¼å‰æ–¹ï¼ˆå¹³æ»‘ï¼‰
        if (bFollowRotation)
        {
            const FRotator FormationRot = CalculateFormationWorldRotation();
            const FRotator NewRot = FMath::RInterpTo(Owner->GetActorRotation(), FormationRot, DeltaTime, AlignmentRotationSpeed);
            Owner->SetActorRotation(FRotator(0.0f, NewRot.Yaw, 0.0f));
        }

        // è¾¾åˆ°ç¡®è®¤æ—¶é—´ + æœå‘å¯¹é½åï¼Œåˆ‡åˆ° Lockedï¼ˆæ— ç¡¬åˆ‡é¡¿æŒ«ï¼‰
        if (ArrivedTimeAccumulator >= ArriveConfirmTime &&
            IsRotationAligned(CalculateFormationWorldRotation(), AlignmentToleranceDegrees))
        {
            UE_LOG(LogXBSoldier, Log, TEXT("è·Ÿéšç»„ä»¶ï¼šæ‹›å‹Ÿè¿‡æ¸¡å®Œæˆï¼ˆç¡®è®¤%.2fsï¼‰ï¼Œåˆ‡æ¢åˆ°é”å®šæ¨¡å¼"), ArriveConfirmTime);

            bRecruitMovementActive = false;
            ArrivedTimeAccumulator = 0.0f;

            SetFollowMode(EXBFollowMode::Locked);
            OnRecruitTransitionCompleted.Broadcast();

            bLeaderIsSprinting = false;
            CachedLeaderSpeed = 0.0f;
        }
    }

    // ========= å¡ä½æ£€æµ‹ï¼ˆä¿æŒä½ åŸé€»è¾‘ï¼‰=========
    const FVector NewPosition = Owner->GetActorLocation();
    const float MovedDistance = FVector::Dist2D(NewPosition, LastPositionForStuckCheck);

    if (DeltaTime > KINDA_SMALL_NUMBER)
    {
        const float InstantSpeed = MovedDistance / DeltaTime;

        if (InstantSpeed < StuckSpeedThreshold && Distance > ArrivalThreshold * 2.0f)
        {
            AccumulatedStuckTime += DeltaTime;
        }
        else
        {
            AccumulatedStuckTime = 0.0f;
            LastPositionForStuckCheck = NewPosition;
        }
    }
    // è¿™é‡ŒåŸæœ¬æœ‰ ShouldForceTeleport/PerformForceTeleportï¼Œä½†ä½ å½“å‰ bAllowTeleportDuringRecruit é»˜è®¤å…³é—­
    // è‹¥ä½ åç»­å¸Œæœ›å¯ç”¨â€œå¡ä½/è¶…æ—¶ä¼ é€â€ï¼Œå¯åœ¨è¿™é‡ŒåŠ ä¸Šåˆ¤æ–­è°ƒç”¨ï¼ˆä¸å½±å“æœ¬æ¬¡æŠ–åŠ¨ä¿®å¤æ ¸å¿ƒï¼‰ã€‚
}

void UXBSoldierFollowComponent::UpdateAlignmentPhase(float DeltaTime)
{
    AActor* Owner = GetOwner();
    if (!Owner)
    {
        return;
    }

    FRotator FormationRotation = CalculateFormationWorldRotation();

    if (IsRotationAligned(FormationRotation, AlignmentToleranceDegrees))
    {
        UE_LOG(LogXBSoldier, Log, TEXT("è·Ÿéšç»„ä»¶ï¼šå¯¹é½å®Œæˆï¼Œåˆ‡æ¢åˆ°é”å®šæ¨¡å¼"));

        Owner->SetActorRotation(FRotator(0.0f, FormationRotation.Yaw, 0.0f));
        SetFollowMode(EXBFollowMode::Locked);
        OnRecruitTransitionCompleted.Broadcast();
        return;
    }

    FRotator CurrentRotation = Owner->GetActorRotation();
    FRotator NewRotation = FMath::RInterpTo(
        CurrentRotation,
        FormationRotation,
        DeltaTime,
        AlignmentRotationSpeed
    );
    Owner->SetActorRotation(FRotator(0.0f, NewRotation.Yaw, 0.0f));

    FVector TargetPosition = GetSmoothedFormationTarget();
    FVector CurrentPosition = Owner->GetActorLocation();
    float Distance = FVector::Dist2D(CurrentPosition, TargetPosition);

    if (Distance > ArrivalThreshold * 2.0f)
    {
        UCharacterMovementComponent* MoveComp = GetCachedMovementComponent();
        ACharacter* CharOwner = Cast<ACharacter>(Owner);

        if (MoveComp && CharOwner)
        {
            float LeaderSpeed = 0.0f;
            if (CachedLeaderCharacter.IsValid())
            {
                LeaderSpeed = CachedLeaderCharacter->GetCurrentMoveSpeed();
            }

            MoveComp->MaxWalkSpeed = FMath::Max(LeaderSpeed, LockedFollowMoveSpeed);

            FVector MoveDirection = (TargetPosition - CurrentPosition).GetSafeNormal2D();
            if (!MoveDirection.IsNearlyZero())
            {
                CharOwner->AddMovementInput(MoveDirection, 1.0f);
            }
        }
    }
}

/**
 * @brief æ›´æ–°å¹½çµç›®æ ‡ï¼ˆä½ç½®ä¸Yawæ’å€¼ï¼‰
 * @param DeltaTime å¸§é—´éš”
 * @note  ğŸ”§ å…³é”®ä¿®å¤ç‚¹ï¼š
 *        1) å¹½çµYawé‡‡ç”¨è§’åº¦å®‰å…¨çš„æŒ‡æ•°å¹³æ»‘ï¼ˆé¿å… 0/360 æŠ–åŠ¨ï¼‰
 *        2) æ§½ä½Yawä½¿ç”¨â€œæœ€å°æ’å€¼é€Ÿåº¦â€ï¼Œä¿è¯ GhostRotationInterpSpeed å¾ˆä½ä¹Ÿä¸æŠ–
 *        3) æ§½ä½Yawå¯é™åˆ¶æœ€å¤§è§’é€Ÿåº¦ï¼Œé¿å…å¤§æ—‹è½¬æ—¶ç›®æ ‡ç‚¹ç”©åŠ¨å¯¼è‡´å£«å…µç©¿æ’å †å 
 *        4) æ§½ä½ä¸­å¿ƒé»˜è®¤ç”¨ä¸»å°†å³æ—¶ä½ç½®ï¼Œå‡å°‘ç»•æ»åä¸­å¿ƒæ—‹è½¬é€ æˆçš„äº¤å‰è·¯å¾„
 */
void UXBSoldierFollowComponent::UpdateGhostTarget(float DeltaTime)
{
     AActor* Leader = FollowTargetRef.Get();
    if (!Leader || !IsValid(Leader))
    {
        bGhostInitialized = false;
        GhostSlotTargetLocation = FVector::ZeroVector;
        return;
    }

    const FVector LeaderLocation = Leader->GetActorLocation();
    const float LeaderYaw = FRotator::NormalizeAxis(Leader->GetActorRotation().Yaw);

    // âœ¨ æ–°å¢ - è§’åº¦å®‰å…¨æŒ‡æ•°å¹³æ»‘ï¼ˆå¸§ç‡æ— å…³ï¼‰
    auto InterpAngleExp = [](float CurrentDeg, float TargetDeg, float Dt, float Speed) -> float
    {
        if (Speed <= KINDA_SMALL_NUMBER || Dt <= KINDA_SMALL_NUMBER)
        {
            return FRotator::NormalizeAxis(TargetDeg);
        }

        // ä¸ºä»€ä¹ˆä½¿ç”¨ FindDeltaAngleDegreesï¼šå®ƒå¤©ç„¶å¤„ç† 359->0 çš„æœ€çŸ­è§’è·¯å¾„
        const float Delta = FMath::FindDeltaAngleDegrees(CurrentDeg, TargetDeg);
        const float Alpha = 1.0f - FMath::Exp(-Speed * Dt);
        return FRotator::NormalizeAxis(CurrentDeg + Delta * Alpha);
    };

    // åˆå§‹åŒ–
    if (!bGhostInitialized)
    {
        GhostTargetLocation = LeaderLocation;

        GhostYawDegrees = LeaderYaw;
        GhostSlotYawDegrees = LeaderYaw;

        GhostTargetRotation = FRotator(0.0f, GhostYawDegrees, 0.0f);

        bGhostInitialized = true;

        // åˆå§‹åŒ–æ§½ä½ç›®æ ‡ç‚¹
        const FVector2D SlotOffset = GetSlotLocalOffset();
        const FVector LocalOffset3D(SlotOffset.X, SlotOffset.Y, 0.0f);

        const FVector SlotCenter = bUseInstantLeaderLocationForSlotCenter ? LeaderLocation : GhostTargetLocation;
        GhostSlotTargetLocation = SlotCenter + FRotator(0.0f, GhostSlotYawDegrees, 0.0f).RotateVector(LocalOffset3D);
        return;
    }

    // å¹½çµä½ç½®æ’å€¼ï¼šç”¨äºæ•´ä½“å¹³æ»‘
    GhostTargetLocation = FMath::VInterpTo(
        GhostTargetLocation,
        LeaderLocation,
        DeltaTime,
        GhostLocationInterpSpeed
    );

    // å¹½çµYawæ’å€¼ï¼šç”¨äºå£«å…µæœå‘/é˜Ÿä¼æœå‘å¹³æ»‘
    GhostYawDegrees = InterpAngleExp(GhostYawDegrees, LeaderYaw, DeltaTime, GhostRotationInterpSpeed);
    GhostTargetRotation = FRotator(0.0f, GhostYawDegrees, 0.0f);

    // ğŸ”§ ä¿®æ”¹ - æ§½ä½Yawï¼šå¼ºåˆ¶æœ€å°æ’å€¼é€Ÿåº¦ï¼Œé¿å…ä½ æŠŠ GhostRotationInterpSpeed è°ƒä½åå‡ºç°æŠ–åŠ¨
    const float SlotYawInterpSpeed = FMath::Max(GhostRotationInterpSpeed, MinGhostSlotYawInterpSpeed);

    // å…ˆæ’å€¼åˆ°â€œæœŸæœ›æ§½ä½Yawâ€
    const float PrevSlotYaw = GhostSlotYawDegrees;
    float NewSlotYaw = InterpAngleExp(GhostSlotYawDegrees, LeaderYaw, DeltaTime, SlotYawInterpSpeed);

    // âœ¨ æ–°å¢ - é™åˆ¶æ§½ä½Yawæœ€å¤§è§’é€Ÿåº¦ï¼šé˜²æ­¢ä¸»å°†å¤§å¹…å¿«é€Ÿè½¬èº«æ—¶æ§½ä½ç›®æ ‡ç‚¹ç¬é—´ç”©åŠ¨å¯¼è‡´ç©¿æ’å †å 
    if (bClampSlotYawRate && DeltaTime > KINDA_SMALL_NUMBER)
    {
        const float MaxDelta = MaxSlotYawRateDegPerSec * DeltaTime;
        const float RawDelta = FMath::FindDeltaAngleDegrees(PrevSlotYaw, NewSlotYaw);

        const float ClampedDelta = FMath::Clamp(RawDelta, -MaxDelta, MaxDelta);
        NewSlotYaw = FRotator::NormalizeAxis(PrevSlotYaw + ClampedDelta);
    }

    GhostSlotYawDegrees = NewSlotYaw;

    // è®¡ç®—æ§½ä½ç›®æ ‡ç‚¹ï¼ˆæ³¨æ„ï¼šä¸­å¿ƒç‚¹é»˜è®¤ä½¿ç”¨ä¸»å°†å³æ—¶ä½ç½®ï¼‰
    const FVector2D SlotOffset = GetSlotLocalOffset();
    const FVector LocalOffset3D(SlotOffset.X, SlotOffset.Y, 0.0f);

    const FVector SlotCenter = bUseInstantLeaderLocationForSlotCenter ? LeaderLocation : GhostTargetLocation;
    GhostSlotTargetLocation = SlotCenter + FRotator(0.0f, GhostSlotYawDegrees, 0.0f).RotateVector(LocalOffset3D);
}

FVector UXBSoldierFollowComponent::GetSmoothedFormationTarget() const
{
    if (bGhostInitialized && !GhostSlotTargetLocation.IsZero())
    {
        return GhostSlotTargetLocation;
    }

    return CalculateFormationWorldPosition();
}

/**
 * @brief è®¡ç®—ç¼–é˜Ÿä¸–ç•Œä½ç½®
 * @return æ§½ä½ä¸–ç•Œåæ ‡
 * @note  ğŸ”§ ä¿®æ”¹ - ä½ç½®ä¼˜å…ˆä½¿ç”¨â€œæ§½ä½Yawâ€è€Œä¸æ˜¯â€œå¹½çµYawâ€ï¼Œé¿å…æ—‹è½¬æ»åå¼•å‘æŠ–åŠ¨
 */
FVector UXBSoldierFollowComponent::CalculateFormationWorldPosition() const
{
    AActor* Leader = FollowTargetRef.Get();
    if (!Leader || !IsValid(Leader))
    {
        AActor* Owner = GetOwner();
        return Owner ? Owner->GetActorLocation() : FVector::ZeroVector;
    }

    const FVector LeaderLocation = bGhostInitialized ? GhostTargetLocation : Leader->GetActorLocation();

    const float YawForSlot = bGhostInitialized
        ? GhostSlotYawDegrees
        : FRotator::NormalizeAxis(Leader->GetActorRotation().Yaw);

    const FVector2D SlotOffset = GetSlotLocalOffset();
    const FVector LocalOffset3D(SlotOffset.X, SlotOffset.Y, 0.0f);

    const FVector WorldOffset = FRotator(0.0f, YawForSlot, 0.0f).RotateVector(LocalOffset3D);
    return LeaderLocation + WorldOffset;
}

/**
 * @brief è®¡ç®—ç¼–é˜Ÿä¸–ç•Œæ—‹è½¬
 * @return é˜Ÿä¼æœå‘ï¼ˆYawï¼‰
 * @note  ä½¿ç”¨å¹½çµYawåšå¹³æ»‘ï¼Œè®©é˜Ÿä¼æœå‘æ›´æŸ”å’Œï¼›ä¸å½±å“æ§½ä½ä½ç½®ç¨³å®šæ€§
 */
FRotator UXBSoldierFollowComponent::CalculateFormationWorldRotation() const
{
    AActor* Leader = FollowTargetRef.Get();
    if (!Leader || !IsValid(Leader))
    {
        AActor* Owner = GetOwner();
        return Owner ? Owner->GetActorRotation() : FRotator::ZeroRotator;
    }

    const float Yaw = bGhostInitialized
        ? GhostYawDegrees
        : FRotator::NormalizeAxis(Leader->GetActorRotation().Yaw);

    return FRotator(0.0f, Yaw, 0.0f);
}

// ==================== ç›®æ ‡è®¾ç½® ====================

void UXBSoldierFollowComponent::SetFollowTarget(AActor* NewTarget)
{
    FollowTargetRef = NewTarget;
    CachedLeaderCharacter = Cast<AXBCharacterBase>(NewTarget);

    if (NewTarget)
    {
        if (AXBCharacterBase* CharTarget = Cast<AXBCharacterBase>(NewTarget))
        {
            CachedFormationComponent = CharTarget->GetFormationComponent();

            bLeaderIsSprinting = CharTarget->IsSprinting();
            CachedLeaderSpeed = CharTarget->GetCurrentMoveSpeed();
        }

        // ğŸ”§ ä¿®æ”¹ - åˆå§‹åŒ–Yawç¼“å­˜ï¼ˆYaw-onlyï¼‰ï¼Œé¿å…ç¬¬ä¸€å¸§è§’åº¦çªè·³
        const float InitYaw = FRotator::NormalizeAxis(NewTarget->GetActorRotation().Yaw);
        GhostYawDegrees = InitYaw;
        GhostSlotYawDegrees = InitYaw;

        GhostTargetLocation = NewTarget->GetActorLocation();
        GhostTargetRotation = FRotator(0.0f, GhostYawDegrees, 0.0f);

        bGhostInitialized = true;

        const FVector2D SlotOffset = GetSlotLocalOffset();
        GhostSlotTargetLocation = GhostTargetLocation + FRotator(0.0f, GhostSlotYawDegrees, 0.0f).RotateVector(FVector(SlotOffset.X, SlotOffset.Y, 0.0f));

        UE_LOG(LogXBSoldier, Log, TEXT("è·Ÿéšç»„ä»¶ï¼šè®¾ç½®è·Ÿéšç›®æ ‡=%sï¼Œæ§½ä½å³æ—¶Yaw=%s"),
            *NewTarget->GetName(),
            bUseInstantLeaderYawForSlot ? TEXT("å¯ç”¨") : TEXT("ç¦ç”¨"));
    }
    else
    {
        CachedFormationComponent = nullptr;
        CachedLeaderCharacter = nullptr;
        bLeaderIsSprinting = false;
        CachedLeaderSpeed = 0.0f;

        bGhostInitialized = false;
        GhostSlotTargetLocation = FVector::ZeroVector;
    }
}

void UXBSoldierFollowComponent::SetFormationSlotIndex(int32 SlotIndex)
{
    FormationSlotIndex = SlotIndex;
    UE_LOG(LogXBSoldier, Verbose, TEXT("è·Ÿéšç»„ä»¶ï¼šè®¾ç½®æ§½ä½ç´¢å¼•=%d"), SlotIndex);
}

// ==================== ç¼“å­˜/ç¢°æ’/æ¨¡å¼/å…¶ä»–å‡½æ•°ä¿æŒä¸å˜ï¼ˆä½ çš„åŸå®ç°ï¼‰ ====================

UCharacterMovementComponent* UXBSoldierFollowComponent::GetCachedMovementComponent()
{
    if (CachedMovementComponent.IsValid())
    {
        return CachedMovementComponent.Get();
    }

    AActor* Owner = GetOwner();
    if (!Owner)
    {
        return nullptr;
    }

    if (ACharacter* CharOwner = Cast<ACharacter>(Owner))
    {
        CachedMovementComponent = CharOwner->GetCharacterMovement();
    }

    return CachedMovementComponent.Get();
}

UCapsuleComponent* UXBSoldierFollowComponent::GetCachedCapsuleComponent()
{
    if (CachedCapsuleComponent.IsValid())
    {
        return CachedCapsuleComponent.Get();
    }

    AActor* Owner = GetOwner();
    if (!Owner)
    {
        return nullptr;
    }

    if (ACharacter* CharOwner = Cast<ACharacter>(Owner))
    {
        CachedCapsuleComponent = CharOwner->GetCapsuleComponent();
    }

    return CachedCapsuleComponent.Get();
}

void UXBSoldierFollowComponent::SetSoldierCollisionEnabled(bool bEnableCollision)
{
    UCapsuleComponent* Capsule = GetCachedCapsuleComponent();
    if (!Capsule)
    {
        return;
    }

    if (bEnableCollision)
    {
        if (bCollisionModified)
        {
            Capsule->SetCollisionResponseToChannel(ECC_Pawn, OriginalPawnResponse);
            bCollisionModified = false;
        }
    }
    else
    {
        if (!bCollisionModified)
        {
            OriginalPawnResponse = Capsule->GetCollisionResponseToChannel(ECC_Pawn);
            Capsule->SetCollisionResponseToChannel(ECC_Pawn, ECR_Overlap);
            bCollisionModified = true;
        }
    }
}

void UXBSoldierFollowComponent::SetMovementMode(bool bEnableWalking)
{
    UCharacterMovementComponent* MoveComp = GetCachedMovementComponent();
    if (!MoveComp)
    {
        return;
    }

    MoveComp->SetComponentTickEnabled(true);

    if (bEnableWalking)
    {
        MoveComp->SetMovementMode(MOVE_Walking);
        MoveComp->GravityScale = 1.0f;
    }
    else
    {
        MoveComp->SetMovementMode(MOVE_Flying);
        MoveComp->GravityScale = 0.0f;
    }
}

void UXBSoldierFollowComponent::SetRVOAvoidanceEnabled(bool bEnable)
{
    UCharacterMovementComponent* MoveComp = GetCachedMovementComponent();
    if (MoveComp)
    {
        MoveComp->SetAvoidanceEnabled(false);
    }
}

void UXBSoldierFollowComponent::SetCombatState(bool bInCombat)
{
    if (bIsInCombat == bInCombat)
    {
        return;
    }

    bIsInCombat = bInCombat;

    if (bInCombat)
    {
        SetSoldierCollisionEnabled(true);
    }

    SetMovementMode(true);

    OnCombatStateChanged.Broadcast(bInCombat);
}

void UXBSoldierFollowComponent::SetFollowMode(EXBFollowMode NewMode)
{
    if (CurrentMode == NewMode)
    {
        return;
    }

    EXBFollowMode OldMode = CurrentMode;
    CurrentMode = NewMode;

    if (NewMode != EXBFollowMode::RecruitTransition)
    {
        CurrentRecruitPhase = EXBRecruitTransitionPhase::Moving;
    }

    if (bDisableCollisionDuringTransition)
    {
        if (NewMode == EXBFollowMode::RecruitTransition)
        {
            SetSoldierCollisionEnabled(false);
        }
        else if (NewMode == EXBFollowMode::Locked && !bIsInCombat)
        {
            SetSoldierCollisionEnabled(true);
        }
    }

    SetMovementMode(true);

    UE_LOG(LogXBSoldier, Log, TEXT("è·Ÿéšç»„ä»¶ï¼šæ¨¡å¼åˆ‡æ¢ %d -> %d"),
        static_cast<int32>(OldMode), static_cast<int32>(NewMode));
}

void UXBSoldierFollowComponent::EnterCombatMode()
{
    SetCombatState(true);
    SetFollowMode(EXBFollowMode::Free);
}

void UXBSoldierFollowComponent::ExitCombatMode()
{
    SetCombatState(false);
    SetFollowMode(EXBFollowMode::RecruitTransition);
    StartRecruitTransition();
}

void UXBSoldierFollowComponent::TeleportToFormationPosition()
{
    AActor* Owner = GetOwner();
    if (!Owner)
    {
        return;
    }

    FVector TargetPos = CalculateFormationWorldPosition();
    FRotator TargetRot = CalculateFormationWorldRotation();
    FVector CurrentPos = Owner->GetActorLocation();

    float GroundZ = GetGroundHeightAtLocation(
        FVector2D(TargetPos.X, TargetPos.Y),
        CurrentPos.Z
    );

    float CharacterHalfHeight = 88.0f;
    if (UCapsuleComponent* Capsule = GetCachedCapsuleComponent())
    {
        CharacterHalfHeight = Capsule->GetScaledCapsuleHalfHeight();
    }

    Owner->SetActorLocation(FVector(TargetPos.X, TargetPos.Y, GroundZ + CharacterHalfHeight));

    if (bFollowRotation)
    {
        Owner->SetActorRotation(TargetRot);
    }

    LastPositionForStuckCheck = Owner->GetActorLocation();
    AccumulatedStuckTime = 0.0f;

    UE_LOG(LogXBSoldier, Log, TEXT("è·Ÿéšç»„ä»¶ï¼šä¼ é€åˆ°ç¼–é˜Ÿä½ç½®ï¼Œåœ°é¢Z=%.1f"), GroundZ);
}
/**
 * @brief å¼€å§‹æ’å€¼åˆ°ç¼–é˜Ÿä½ç½®
 * @note  ğŸ”§ ä¿®æ”¹ - ç›´æ¥å¤ç”¨æ‹›å‹Ÿè¿‡æ¸¡é€»è¾‘ï¼Œå¹¶ç¡®ä¿ bRecruitMovementActive ç”Ÿæ•ˆ
 *        è¿™æ˜¯ç¼–é˜Ÿæ›´æ–°è¡¥ä½çš„æ ¸å¿ƒå…¥å£ï¼Œå¿…é¡»èƒ½çœŸæ­£æ¨åŠ¨ç§»åŠ¨ç»„ä»¶äº§ç”Ÿé€Ÿåº¦
 */
void UXBSoldierFollowComponent::StartInterpolateToFormation()
{
    // ä¸ºä»€ä¹ˆç»Ÿä¸€èµ°æ‹›å‹Ÿè¿‡æ¸¡ï¼šèƒ½ä¿è¯ç§»åŠ¨ç»„ä»¶é©±åŠ¨ã€é€Ÿåº¦å¹³æ»‘ã€æ—‹è½¬æ··åˆä¸€è‡´
    SetCombatState(false);
    SetFollowMode(EXBFollowMode::RecruitTransition);

    // ğŸ”§ ä¿®æ”¹ - é‡ç½®åˆ°è¾¾ç¡®è®¤è®¡æ—¶ï¼Œé¿å…ä¸Šä¸€è½®æ®‹ç•™é€ æˆé¡¿æŒ«
    ArrivedTimeAccumulator = 0.0f;

    // ç›´æ¥å¯åŠ¨ï¼ˆéµä» RecruitStartDelay é…ç½®ï¼‰
    StartRecruitTransition();

    UE_LOG(LogXBSoldier, Log, TEXT("è·Ÿéšç»„ä»¶ï¼šStartInterpolateToFormation -> è¿›å…¥æ‹›å‹Ÿè¿‡æ¸¡è¡¥ä½ï¼ˆç»„ä»¶é©±åŠ¨ï¼‰"));
}

void UXBSoldierFollowComponent::StartRecruitTransition()
{
    SetCombatState(false);
    SetFollowMode(EXBFollowMode::RecruitTransition);

    CurrentRecruitPhase = EXBRecruitTransitionPhase::Moving;

    if (DelayedRecruitStartHandle.IsValid())
    {
        GetWorld()->GetTimerManager().ClearTimer(DelayedRecruitStartHandle);
    }

    bRecruitMovementActive = false;

    if (RecruitStartDelay > 0.0f)
    {
        GetWorld()->GetTimerManager().SetTimer(
            DelayedRecruitStartHandle,
            this,
            &UXBSoldierFollowComponent::StartRecruitTransition_Internal,
            RecruitStartDelay,
            false
        );
        return;
    }

    StartRecruitTransition_Internal();
}
/**
 * @brief å†…éƒ¨å¯åŠ¨æ‹›å‹Ÿè¿‡æ¸¡ï¼ˆå»¶è¿Ÿç»“æŸåçœŸæ­£å¼€å§‹ç§»åŠ¨ï¼‰
 * @note  ğŸ”§ ä¿®æ”¹ - é‡ç½®åˆ°è¾¾ç´¯ç§¯è®¡æ—¶ï¼Œé¿å…ä¸Šä¸€æ¬¡æ®‹ç•™å¯¼è‡´â€œåˆšå¼€å§‹å°±åˆ¤å®šåˆ°ä½â€å¼•å‘é¡¿æŒ«
 */
void UXBSoldierFollowComponent::StartRecruitTransition_Internal()
{
    if (UWorld* World = GetWorld())
    {
        RecruitTransitionStartTime = World->GetTimeSeconds();
    }

    if (AActor* Owner = GetOwner())
    {
        LastPositionForStuckCheck = Owner->GetActorLocation();
    }

    AccumulatedStuckTime = 0.0f;

    // ğŸ”§ ä¿®æ”¹ - åˆ°è¾¾ç¡®è®¤è®¡æ—¶æ¸…é›¶ï¼ˆéå¸¸å…³é”®ï¼‰
    ArrivedTimeAccumulator = 0.0f;

    UCharacterMovementComponent* MoveComp = GetCachedMovementComponent();
    if (MoveComp)
    {
        // ä¸ºä»€ä¹ˆè¦ä¿è¯ Walkingï¼šé¿å…å¤–éƒ¨çŠ¶æ€æ®‹ç•™å¯¼è‡´é€Ÿåº¦/æ‘©æ“¦/è´´åœ°ä¸ä¸€è‡´
        MoveComp->GravityScale = 1.0f;
        MoveComp->SetComponentTickEnabled(true);
        MoveComp->SetMovementMode(MOVE_Walking);

        // é€Ÿåº¦ç¼“å­˜ç”¨äºåç»­å¹³æ»‘
        SmoothedSpeedCache = MoveComp->MaxWalkSpeed;
    }

    if (CachedLeaderCharacter.IsValid())
    {
        bLeaderIsSprinting = CachedLeaderCharacter->IsSprinting();
        CachedLeaderSpeed = CachedLeaderCharacter->GetCurrentMoveSpeed();
    }

    bRecruitMovementActive = true;

    UE_LOG(LogXBSoldier, Log, TEXT("è·Ÿéšç»„ä»¶ï¼šå¼€å§‹æ‹›å‹Ÿè¿‡æ¸¡ï¼ˆå»¶è¿Ÿ%.2fså·²å¤„ç†ï¼‰ï¼Œåˆ°è¾¾è®¡æ—¶å·²é‡ç½®"), RecruitStartDelay);
}

FVector UXBSoldierFollowComponent::GetTargetPosition() const
{
    return GetSmoothedFormationTarget();
}

bool UXBSoldierFollowComponent::IsAtFormationPosition() const
{
    return GetDistanceToFormation() <= ArrivalThreshold;
}

float UXBSoldierFollowComponent::GetDistanceToFormation() const
{
    AActor* Owner = GetOwner();
    if (!Owner)
    {
        return 0.0f;
    }

    FVector TargetPos = CalculateFormationWorldPosition();
    return FVector::Dist2D(Owner->GetActorLocation(), TargetPos);
}
/**
 * @brief ç§»åŠ¨åˆ°ç›®æ ‡ä½ç½®ï¼ˆåªæ§åˆ¶XYï¼ŒZä¿æŒå½“å‰å€¼ï¼‰
 * @param TargetPosition ç›®æ ‡ä½ç½®
 * @param DeltaTime å¸§é—´éš”
 * @param MoveSpeed ç§»åŠ¨é€Ÿåº¦
 * @return æ˜¯å¦å·²åˆ°è¾¾
 * @note  Z ç”± CharacterMovement çš„é‡åŠ›/è´´åœ°è´Ÿè´£ï¼Œè¿™é‡Œä¸æ‰‹åŠ¨æ”¹Zï¼Œé¿å…ä¸Šä¸‹æŠ–åŠ¨ä¸ç©¿æ’åœ°é¢
 */
bool UXBSoldierFollowComponent::MoveTowardsTargetXY(const FVector& TargetPosition, float DeltaTime, float MoveSpeed)
{
    AActor* Owner = GetOwner();
    if (!Owner || DeltaTime <= KINDA_SMALL_NUMBER)
    {
        return false;
    }

    // ä¸ºä»€ä¹ˆåªå¤„ç†XYï¼šè·Ÿéš/ç¼–é˜Ÿæ˜¯å¹³é¢é˜Ÿåˆ—é€»è¾‘ï¼ŒZäº¤ç»™ç‰©ç†/å¯¼èˆªè´´åœ°å¯é¿å…å°é˜¶ä¸å¡é¢æŠ–åŠ¨
    const FVector CurrentPosition = Owner->GetActorLocation();

    const FVector2D CurrentXY(CurrentPosition.X, CurrentPosition.Y);
    const FVector2D TargetXY(TargetPosition.X, TargetPosition.Y);

    FVector2D Direction = TargetXY - CurrentXY;
    const float Distance = Direction.Size();

    // åˆ°è¾¾é˜ˆå€¼å†…ç›´æ¥å¯¹é½XYï¼ˆä¸åŠ¨Zï¼‰
    if (Distance <= ArrivalThreshold)
    {
        Owner->SetActorLocation(FVector(TargetXY.X, TargetXY.Y, CurrentPosition.Z));
        return true;
    }

    Direction.Normalize();

    const float MoveDistance = MoveSpeed * DeltaTime;

    FVector2D NewXY;
    if (MoveDistance >= Distance)
    {
        NewXY = TargetXY;
    }
    else
    {
        NewXY = CurrentXY + Direction * MoveDistance;
    }

    // åªæ”¹XYï¼šZä¿æŒä¸å˜ï¼Œé¿å…â€œäººä¸ºå†™Zâ€ä¸ç§»åŠ¨ç»„ä»¶è´´åœ°ä¿®æ­£æ‰“æ¶é€ æˆæŠ–åŠ¨
    Owner->SetActorLocation(FVector(NewXY.X, NewXY.Y, CurrentPosition.Z));

    return MoveDistance >= Distance;
}

/**
 * @brief æ˜¯å¦éœ€è¦å¼ºåˆ¶ä¼ é€
 * @return æ˜¯å¦åº”è¯¥ä¼ é€
 * @note  å½“å‰é»˜è®¤ bAllowTeleportDuringRecruit=falseï¼Œå› æ­¤é€šå¸¸ä¸ä¼šè§¦å‘ï¼ˆä¿æŒä½ åŸé¡¹ç›®ç­–ç•¥ï¼‰
 */
bool UXBSoldierFollowComponent::ShouldForceTeleport() const
{
    AActor* Owner = GetOwner();
    UWorld* World = GetWorld();

    if (!Owner || !World || !bAllowTeleportDuringRecruit)
    {
        return false;
    }

    const float CurrentTime = World->GetTimeSeconds();

    // è·ç¦»è¿‡è¿œï¼šè¯´æ˜è¿½èµ¶æˆæœ¬å¤ªé«˜ï¼Œä¼ é€å›ç¼–é˜Ÿé¿å…æ‰é˜Ÿ
    const float Distance = GetDistanceToFormation();
    if (Distance > ForceTeleportDistance)
    {
        return true;
    }

    // è¶…æ—¶ï¼šé•¿æ—¶é—´è¿½ä¸ä¸Šï¼Œé¿å…æ°¸è¿œæ‹–å°¾
    const float ElapsedTime = CurrentTime - RecruitTransitionStartTime;
    if (RecruitTransitionTimeout > 0.0f && ElapsedTime > RecruitTransitionTimeout)
    {
        return true;
    }

    // å¡ä½ï¼šä½é€ŸæŒç»­è¿‡ä¹…è¯´æ˜å¯èƒ½è¢«ç¢°æ’/å¡ä½é˜»å¡
    if (StuckDetectionTime > 0.0f && AccumulatedStuckTime > StuckDetectionTime)
    {
        return true;
    }

    return false;
}

/**
 * @brief æ‰§è¡Œå¼ºåˆ¶ä¼ é€
 * @note  ä¼ é€åç›´æ¥åˆ‡æ¢åˆ° Lockedï¼Œç¡®ä¿ç«‹åˆ»ç¨³å®šè´´åˆç¼–é˜Ÿ
 */
void UXBSoldierFollowComponent::PerformForceTeleport()
{
    UE_LOG(LogXBSoldier, Warning, TEXT("è·Ÿéšç»„ä»¶ï¼šæ‰§è¡Œå¼ºåˆ¶ä¼ é€ï¼ˆè·ç¦»/è¶…æ—¶/å¡ä½è§¦å‘ï¼‰"));

    TeleportToFormationPosition();
    SetFollowMode(EXBFollowMode::Locked);

    // ä¸ºä»€ä¹ˆè¦æ¸…ç†ç¼“å­˜ï¼šä¼ é€åä¸å†æ˜¯â€œè¿½èµ¶â€è¯­ä¹‰ï¼Œå¦åˆ™é€Ÿåº¦è¡¥å¿å¯èƒ½é€ æˆç¬æ—¶åŠ é€Ÿ
    bLeaderIsSprinting = false;
    CachedLeaderSpeed = 0.0f;

    OnRecruitTransitionCompleted.Broadcast();
}

/**
 * @brief è·å–æ§½ä½æœ¬åœ°åç§»
 * @return æ§½ä½LocalOffsetï¼ˆXå‘åã€Yå‘å·¦å³ï¼‰
 * @note  ä¼˜å…ˆä» FormationComponent è¯»å–ï¼ˆä½ çš„ç¼–é˜Ÿé…ç½®æœ€æƒå¨ï¼‰ï¼›æ²¡æœ‰åˆ™å›é€€åˆ°ç®€æ˜“ç½‘æ ¼
 */
FVector2D UXBSoldierFollowComponent::GetSlotLocalOffset() const
{
    // ä¼˜å…ˆä»ç¼–é˜Ÿç»„ä»¶è·å–ï¼Œç¡®ä¿ä¸å°†é¢†ç¼–é˜Ÿä¸€è‡´
    if (CachedFormationComponent.IsValid() && FormationSlotIndex != INDEX_NONE)
    {
        UXBFormationComponent* FormationComp = CachedFormationComponent.Get();
        if (FormationComp)
        {
            const TArray<FXBFormationSlot>& Slots = FormationComp->GetFormationSlots();
            if (Slots.IsValidIndex(FormationSlotIndex))
            {
                return Slots[FormationSlotIndex].LocalOffset;
            }
        }
    }

    // å›é€€ï¼šç®€æ˜“4åˆ—é˜µï¼ˆé¿å…æ²¡æœ‰ç¼–é˜Ÿç»„ä»¶æ—¶å®Œå…¨ä¸å¯ç”¨ï¼‰
    if (FormationSlotIndex >= 0)
    {
        const int32 Columns = 4;
        const int32 Row = FormationSlotIndex / Columns;
        const int32 Col = FormationSlotIndex % Columns;

        const float HorizontalSpacing = 100.0f;
        const float VerticalSpacing = 100.0f;
        const float MinDistanceToLeader = 150.0f;

        const float OffsetX = -(MinDistanceToLeader + Row * VerticalSpacing);
        const float OffsetY = (Col - (Columns - 1) * 0.5f) * HorizontalSpacing;

        return FVector2D(OffsetX, OffsetY);
    }

    return FVector2D::ZeroVector;
}

/**
 * @brief è·å–æŒ‡å®šXYä½ç½®çš„åœ°é¢Zåæ ‡
 * @param XYLocation XYä½ç½®
 * @param FallbackZ æ£€æµ‹å¤±è´¥æ—¶å›é€€Z
 * @return åœ°é¢Z
 * @note  ä»…ç”¨äºâ€œä¼ é€â€è¿™ç±»éœ€è¦å¼ºåˆ¶è½åœ°çš„åœºæ™¯ï¼›æ­£å¸¸ç§»åŠ¨æ—¶ä¸å»ºè®®æ¯å¸§æ‰“å°„çº¿ï¼ˆæˆæœ¬é«˜ï¼‰
 */
float UXBSoldierFollowComponent::GetGroundHeightAtLocation(const FVector2D& XYLocation, float FallbackZ) const
{
    UWorld* World = GetWorld();
    if (!World)
    {
        return FallbackZ;
    }

    const FVector TraceStart(XYLocation.X, XYLocation.Y, FallbackZ + 500.0f);
    const FVector TraceEnd(XYLocation.X, XYLocation.Y, FallbackZ - 1000.0f);

    FHitResult HitResult;
    FCollisionQueryParams QueryParams;
    QueryParams.bTraceComplex = false;

    // ä¸ºä»€ä¹ˆè¦å¿½ç•¥è‡ªå·±/å°†é¢†ï¼šé¿å…å°„çº¿æ‰“åˆ°è§’è‰²èƒ¶å›Šæˆ–å°†é¢†èƒ¶å›Šå¯¼è‡´â€œåœ°é¢é«˜åº¦â€é”™è¯¯
    if (AActor* Owner = GetOwner())
    {
        QueryParams.AddIgnoredActor(Owner);
    }
    if (FollowTargetRef.IsValid())
    {
        QueryParams.AddIgnoredActor(FollowTargetRef.Get());
    }

    const bool bHit = World->LineTraceSingleByChannel(
        HitResult,
        TraceStart,
        TraceEnd,
        ECC_WorldStatic,
        QueryParams
    );

    if (bHit)
    {
        return HitResult.Location.Z;
    }

    return FallbackZ;
}