/* --- å®Œæ•´æ–‡ä»¶ä»£ç  --- */
// Source/XiaoBinDaTianXia/Private/Character/XBCharacterBase.cpp

/**
 * @file XBCharacterBase.cpp
 * @brief è§’è‰²åŸºç±»å®ç°
 * 
 * @note ğŸ”§ ä¿®æ”¹è®°å½•:
 *       1. ä¿®å¤å£«å…µè®¡æ•°åŒæ­¥é—®é¢˜
 *       2. ä¿®å¤å°†é¢†æ­»äº¡æ—¶å¾ªç¯å›è°ƒé—®é¢˜
 *       3. âœ¨ æ–°å¢ æ‰è½å£«å…µæŠ›ç‰©çº¿ç³»ç»Ÿï¼ˆè½åœ°è‡ªåŠ¨å…¥åˆ—ï¼‰
 *       4. ğŸ”§ ä¿®æ”¹ ä½¿ç”¨ FullInitialize å®Œæ•´åˆå§‹åŒ–æ‰è½å£«å…µ
 */

#include "Character/XBCharacterBase.h"
#include "Utils/XBLogCategories.h"
#include "Utils/XBBlueprintFunctionLibrary.h"
#include "AIController.h"
#include "Character/Components/XBCombatComponent.h"
#include "Character/Components/XBMagnetFieldComponent.h"
#include "Character/Components/XBFormationComponent.h"
#include "UI/XBWorldHealthBarComponent.h"
#include "GAS/XBAbilitySystemComponent.h"
#include "GAS/XBAttributeSet.h"
#include "Data/XBLeaderDataTable.h"
#include "Soldier/XBSoldierCharacter.h"
#include "Engine/DataTable.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "Components/CapsuleComponent.h"
#include "Animation/AnimInstance.h"
#include "TimerManager.h"
#include "XBCollisionChannels.h"
#include "AI/XBSoldierPerceptionSubsystem.h"
#include "Particles/ParticleSystemComponent.h"
#include "Soldier/Component/XBSoldierPoolSubsystem.h"
#include "AI/XBSoldierAIController.h"

AXBCharacterBase::AXBCharacterBase()
{
    PrimaryActorTick.bCanEverTick = true;

    if (UCapsuleComponent* Capsule = GetCapsuleComponent())
    {
        Capsule->SetCollisionObjectType(XBCollision::Leader);
        Capsule->SetCollisionResponseToChannel(XBCollision::Leader, ECR_Block);
        Capsule->SetCollisionResponseToChannel(XBCollision::Soldier, ECR_Overlap);
    }

    if (USkeletalMeshComponent* MeshComp = GetMesh())
    {
        MeshComp->SetCollisionResponseToChannel(XBCollision::Leader, ECR_Ignore);
        MeshComp->SetCollisionResponseToChannel(XBCollision::Soldier, ECR_Ignore);
    }

    AbilitySystemComponent = CreateDefaultSubobject<UXBAbilitySystemComponent>(TEXT("AbilitySystemComponent"));
    AttributeSet = CreateDefaultSubobject<UXBAttributeSet>(TEXT("AttributeSet"));
    CombatComponent = CreateDefaultSubobject<UXBCombatComponent>(TEXT("CombatComponent"));

    HealthBarComponent = CreateDefaultSubobject<UXBWorldHealthBarComponent>(TEXT("HealthBarComponent"));
    HealthBarComponent->SetupAttachment(RootComponent);

    MagnetFieldComponent = CreateDefaultSubobject<UXBMagnetFieldComponent>(TEXT("MagnetFieldComponent"));
    MagnetFieldComponent->SetupAttachment(RootComponent);

    FormationComponent = CreateDefaultSubobject<UXBFormationComponent>(TEXT("SoldierFormationComponent"));

    bUseControllerRotationPitch = false;
    bUseControllerRotationYaw = false;
    bUseControllerRotationRoll = false;
}

void AXBCharacterBase::BeginPlay()
{
    Super::BeginPlay();

    // ğŸ”§ ä¿®æ”¹ - å°†ä¸»å°†æ³¨å†Œåˆ°æ„ŸçŸ¥å­ç³»ç»Ÿï¼Œç¡®ä¿å£«å…µå¯ä»¥æ„ŸçŸ¥åˆ°ä¸»å°†
    if (UWorld* World = GetWorld())
    {
        // ğŸ”§ ä¿®æ”¹ - ä»…åœ¨å­ç³»ç»Ÿæœ‰æ•ˆæ—¶æ‰§è¡Œæ³¨å†Œ
        if (UXBSoldierPerceptionSubsystem* Perception = World->GetSubsystem<UXBSoldierPerceptionSubsystem>())
        {
            // ğŸ”§ ä¿®æ”¹ - ä½¿ç”¨ä¸»å°†é˜µè¥æ³¨å†Œï¼Œä¾¿äºé˜µè¥ç­›é€‰
            Perception->RegisterActor(this, Faction);
        }
    }

    InitializeAbilitySystem();
    SetupMovementComponent();

    TargetMoveSpeed = BaseMoveSpeed;

    BindCombatEvents();

    if (MagnetFieldComponent)
    {
        if (!MagnetFieldComponent->OnActorEnteredField.IsBound())
        {
            MagnetFieldComponent->OnActorEnteredField.AddDynamic(this, &AXBCharacterBase::OnMagnetFieldActorEntered);
        }
        MagnetFieldComponent->SetFieldEnabled(true);
    }

    if (ConfigDataTable && !ConfigRowName.IsNone())
    {
        InitializeFromDataTable(ConfigDataTable, ConfigRowName);
    }
}

/**
 * @brief ç»“æŸæ’­æ”¾æ—¶å¤„ç†æ„ŸçŸ¥å­ç³»ç»Ÿæ³¨é”€
 * @param EndPlayReason ç»“æŸåŸå› 
 * @return æ— 
 * @note åŠŸèƒ½è¯´æ˜: é€€å‡ºæ—¶å°†ä¸»å°†ä»æ„ŸçŸ¥å­ç³»ç»Ÿä¸­ç§»é™¤
 * @note è¯¦ç»†æµç¨‹: è·å–ä¸–ç•Œ -> è·å–æ„ŸçŸ¥å­ç³»ç»Ÿ -> æ³¨é”€ Actor -> è°ƒç”¨çˆ¶ç±» EndPlay
 * @note æ³¨æ„äº‹é¡¹: éœ€è¦åœ¨æ³¨é”€åå†è°ƒç”¨çˆ¶ç±» EndPlayï¼Œé¿å…è®¿é—®å·²é”€æ¯å¯¹è±¡
 */
void AXBCharacterBase::EndPlay(const EEndPlayReason::Type EndPlayReason)
{
    // ğŸ”§ ä¿®æ”¹ - è·å–ä¸–ç•Œå®ä¾‹ç”¨äºæ„ŸçŸ¥æ³¨é”€
    if (UWorld* World = GetWorld())
    {
        // ğŸ”§ ä¿®æ”¹ - å­ç³»ç»Ÿæœ‰æ•ˆæ—¶æ‰§è¡Œæ³¨é”€
        if (UXBSoldierPerceptionSubsystem* Perception = World->GetSubsystem<UXBSoldierPerceptionSubsystem>())
        {
            // ğŸ”§ ä¿®æ”¹ - æ³¨é”€å½“å‰ä¸»å°†
            Perception->UnregisterActor(this);
        }
    }

    // ğŸ”§ ä¿®æ”¹ - è°ƒç”¨çˆ¶ç±» EndPlay
    Super::EndPlay(EndPlayReason);
}

void AXBCharacterBase::Tick(float DeltaTime)
{
    Super::Tick(DeltaTime);
    UpdateSprint(DeltaTime);
}

void AXBCharacterBase::SetupMovementComponent()
{
    UCharacterMovementComponent* CMC = GetCharacterMovement();
    if (!CMC)
    {
        return;
    }

    CMC->MaxWalkSpeed = BaseMoveSpeed;
    CMC->BrakingDecelerationWalking = 2000.0f;
    CMC->GroundFriction = 8.0f;
    CMC->bOrientRotationToMovement = true;
    CMC->RotationRate = FRotator(0.0f, 540.0f, 0.0f);
    CMC->MaxAcceleration = 2048.0f;
    CMC->BrakingFrictionFactor = 2.0f;
}

void AXBCharacterBase::OnMagnetFieldActorEntered(AActor* EnteredActor)
{
    if (!EnteredActor)
    {
        return;
    }

    UE_LOG(LogXBRecruit, Log, TEXT("%s: Actor è¿›å…¥ç£åœº: %s"), *GetName(), *EnteredActor->GetName());
}

void AXBCharacterBase::PossessedBy(AController* NewController)
{
    Super::PossessedBy(NewController);

    if (AbilitySystemComponent)
    {
        AbilitySystemComponent->InitAbilityActorInfo(this, this);
    }
}

UAbilitySystemComponent* AXBCharacterBase::GetAbilitySystemComponent() const
{
    return AbilitySystemComponent;
}

void AXBCharacterBase::InitializeAbilitySystem()
{
    if (AbilitySystemComponent)
    {
        AbilitySystemComponent->InitAbilityActorInfo(this, this);
    }
}

void AXBCharacterBase::InitializeFromDataTable(UDataTable* DataTable, FName RowName)
{
    if (!DataTable || RowName.IsNone())
    {
        return;
    }

    FXBLeaderTableRow* LeaderRow = DataTable->FindRow<FXBLeaderTableRow>(RowName, TEXT("AXBCharacterBase::InitializeFromDataTable"));
    if (!LeaderRow)
    {
        return;
    }

    CachedLeaderData = *LeaderRow;

    GrowthConfigCache.HealthPerSoldier = LeaderRow->HealthPerSoldier;
    GrowthConfigCache.ScalePerSoldier = LeaderRow->ScalePerSoldier;
    GrowthConfigCache.MaxScale = LeaderRow->MaxScale;
    GrowthConfigCache.DamageMultiplierPerSoldier = LeaderRow->DamageMultiplierPerSoldier;
    GrowthConfigCache.MaxDamageMultiplier = LeaderRow->MaxDamageMultiplier;

    if (CombatComponent)
    {
        CombatComponent->InitializeFromDataTable(DataTable, RowName);
    }

    ApplyInitialAttributes();

    if (UCharacterMovementComponent* MovementComp = GetCharacterMovement())
    {
        MovementComp->MaxWalkSpeed = LeaderRow->MoveSpeed;
        BaseMoveSpeed = LeaderRow->MoveSpeed;
        TargetMoveSpeed = BaseMoveSpeed;
    }
}

void AXBCharacterBase::ApplyInitialAttributes()
{
    if (!AbilitySystemComponent)
    {
        return;
    }

    const UXBAttributeSet* LocalAttributeSet = AbilitySystemComponent->GetSet<UXBAttributeSet>();
    if (!LocalAttributeSet)
    {
        return;
    }

    AbilitySystemComponent->SetNumericAttributeBase(UXBAttributeSet::GetMaxHealthAttribute(), CachedLeaderData.MaxHealth);
    AbilitySystemComponent->SetNumericAttributeBase(UXBAttributeSet::GetHealthAttribute(), CachedLeaderData.MaxHealth);
    AbilitySystemComponent->SetNumericAttributeBase(UXBAttributeSet::GetHealthMultiplierAttribute(), CachedLeaderData.HealthMultiplier);
    AbilitySystemComponent->SetNumericAttributeBase(UXBAttributeSet::GetDamageMultiplierAttribute(), CachedLeaderData.DamageMultiplier);
    AbilitySystemComponent->SetNumericAttributeBase(UXBAttributeSet::GetMoveSpeedAttribute(), CachedLeaderData.MoveSpeed);
    AbilitySystemComponent->SetNumericAttributeBase(UXBAttributeSet::GetScaleAttribute(), CachedLeaderData.Scale);
}

// ==================== å†²åˆºç³»ç»Ÿå®ç° ====================

void AXBCharacterBase::StartSprint()
{
    if (bIsDead || bIsSprinting)
    {
        return;
    }

    bIsSprinting = true;
    TargetMoveSpeed = BaseMoveSpeed * SprintSpeedMultiplier;

    SetSoldiersEscaping(true);
    OnSprintStateChanged.Broadcast(true);
}

void AXBCharacterBase::StopSprint()
{
    if (!bIsSprinting)
    {
        return;
    }

    bIsSprinting = false;
    TargetMoveSpeed = BaseMoveSpeed;

    SetSoldiersEscaping(false);
    OnSprintStateChanged.Broadcast(false);
}

float AXBCharacterBase::GetCurrentMoveSpeed() const
{
    if (const UCharacterMovementComponent* CMC = GetCharacterMovement())
    {
        return CMC->MaxWalkSpeed;
    }
    return BaseMoveSpeed;
}

/**
 * @brief è·å–æœ€è¿‘æ”»å‡»çš„æ•Œæ–¹é˜µè¥
 * @param OutFaction è¾“å‡ºçš„æ•Œæ–¹é˜µè¥
 * @return æ˜¯å¦æœ‰æœ‰æ•ˆçš„æ•Œæ–¹é˜µè¥è®°å½•
 * @note åŠŸèƒ½è¯´æ˜: å°†ä¸»å°†æœ€è¿‘æ”»å‡»åˆ°çš„æ•Œæ–¹é˜µè¥æš´éœ²ç»™å£«å…µï¼Œç”¨äºä¼˜å…ˆé€‰æ•Œ
 * @note è¯¦ç»†æµç¨‹: æ£€æŸ¥æ˜¯å¦æœ‰è®°å½• -> è¾“å‡ºé˜µè¥ -> è¿”å›ç»“æœ
 * @note æ³¨æ„äº‹é¡¹: è‹¥æ²¡æœ‰è®°å½•ï¼ŒOutFaction ä¸ä¼šè¢«ä¿®æ”¹
 */
bool AXBCharacterBase::GetLastAttackedEnemyFaction(EXBFaction& OutFaction) const
{
    // ğŸ”§ ä¿®æ”¹ - æ— è®°å½•æ—¶ç›´æ¥è¿”å›å¤±è´¥
    if (!bHasLastAttackedEnemyFaction)
    {
        return false;
    }

    // ğŸ”§ ä¿®æ”¹ - è¾“å‡ºè®°å½•çš„æ•Œæ–¹é˜µè¥
    OutFaction = LastAttackedEnemyFaction;

    // ğŸ”§ ä¿®æ”¹ - è¿”å›æˆåŠŸ
    return true;
}

void AXBCharacterBase::UpdateSprint(float DeltaTime)
{
    UCharacterMovementComponent* CMC = GetCharacterMovement();
    if (!CMC)
    {
        return;
    }

    float CurrentSpeed = CMC->MaxWalkSpeed;

    if (!FMath::IsNearlyEqual(CurrentSpeed, TargetMoveSpeed, 1.0f))
    {
        float NewSpeed = FMath::FInterpTo(CurrentSpeed, TargetMoveSpeed, DeltaTime, SpeedInterpRate);
        CMC->MaxWalkSpeed = NewSpeed;
    }
}

// ==================== é˜µè¥ç³»ç»Ÿå®ç° ====================

bool AXBCharacterBase::IsHostileTo(const AXBCharacterBase* Other) const
{
    if (!Other)
    {
        return false;
    }

    return UXBBlueprintFunctionLibrary::AreFactionsHostile(Faction, Other->Faction);
}

bool AXBCharacterBase::IsFriendlyTo(const AXBCharacterBase* Other) const
{
    if (!Other)
    {
        return false;
    }

    return UXBBlueprintFunctionLibrary::AreFactionsFriendly(Faction, Other->Faction);
}

// ==================== å£«å…µç®¡ç†å®ç° ====================

bool AXBCharacterBase::Internal_AddSoldierToArray(AXBSoldierCharacter* Soldier)
{
    if (!Soldier || Soldiers.Contains(Soldier))
    {
        return false;
    }

    Soldiers.Add(Soldier);
    return true;
}

bool AXBCharacterBase::Internal_RemoveSoldierFromArray(AXBSoldierCharacter* Soldier)
{
    if (!Soldier)
    {
        return false;
    }

    int32 RemovedIndex = Soldiers.Find(Soldier);
    if (RemovedIndex == INDEX_NONE)
    {
        return false;
    }

    Soldiers.RemoveAt(RemovedIndex);
    ReassignSoldierSlots(RemovedIndex);
    return true;
}

void AXBCharacterBase::UpdateSoldierCount(int32 OldCount)
{
    int32 NewCount = Soldiers.Num();

    if (OldCount != NewCount)
    {
        OnSoldierCountChanged.Broadcast(OldCount, NewCount);
    }
}
/**
 * @brief æ·»åŠ å£«å…µ
 * @param Soldier å£«å…µ
 * @note ğŸ”§ ä¿®å¤ - æ£€æŸ¥å£«å…µæ˜¯å¦å·²åœ¨é˜Ÿä¼ä¸­ï¼Œé¿å…é‡å¤æ·»åŠ 
 */
void AXBCharacterBase::AddSoldier(AXBSoldierCharacter* Soldier)
{
    if (bIsDead)
    {
        UE_LOG(LogXBCharacter, Warning, TEXT("%s: è§’è‰²å·²æ­»äº¡ï¼Œæ— æ³•æ·»åŠ å£«å…µ"), *GetName());
        return;
    }

    if (!Soldier)
    {
        UE_LOG(LogXBCharacter, Warning, TEXT("%s: å£«å…µæŒ‡é’ˆä¸ºç©º"), *GetName());
        return;
    }

    // ğŸ”§ ä¿®æ”¹ - æ£€æŸ¥æ˜¯å¦å·²åœ¨é˜Ÿä¼ä¸­
    int32 ExistingIndex = Soldiers.Find(Soldier);
    if (ExistingIndex != INDEX_NONE)
    {
        UE_LOG(LogXBSoldier, Warning, TEXT("%s: å£«å…µ %s å·²åœ¨é˜Ÿä¼ä¸­ï¼ˆç´¢å¼•: %dï¼‰ï¼ŒåŒæ­¥æ§½ä½"),
            *GetName(), *Soldier->GetName(), ExistingIndex);
        
        // âœ¨ æ–°å¢ - ç¡®ä¿æ§½ä½ç´¢å¼•æ­£ç¡®åŒæ­¥
        if (Soldier->GetFormationSlotIndex() != ExistingIndex)
        {
            Soldier->SetFormationSlotIndex(ExistingIndex);
            UE_LOG(LogXBSoldier, Log, TEXT("%s: åŒæ­¥å£«å…µ %s æ§½ä½ç´¢å¼•ä¸º %d"),
                *GetName(), *Soldier->GetName(), ExistingIndex);
        }
        return;
    }

    int32 OldCount = Soldiers.Num();

    // æ·»åŠ åˆ°æ•°ç»„
    Soldiers.Add(Soldier);

    // âœ¨ æ ¸å¿ƒ - æ§½ä½ç´¢å¼•ç­‰äºæ•°ç»„ä¸­çš„ä½ç½®ï¼ˆæœ€åä¸€ä¸ªï¼‰
    int32 SlotIndex = Soldiers.Num() - 1;
    
    // è®¾ç½®å£«å…µçš„æ§½ä½ç´¢å¼•
    Soldier->SetFormationSlotIndex(SlotIndex);
    
    UE_LOG(LogXBSoldier, Log, TEXT("%s: å£«å…µ %s æ·»åŠ æˆåŠŸï¼Œåˆ†é…æ§½ä½: %d, å½“å‰æ•°é‡: %d"),
        *GetName(), *Soldier->GetName(), SlotIndex, Soldiers.Num());

    // åº”ç”¨æˆé•¿æ•ˆæœ
    ApplyGrowthOnSoldiersAdded(1);

    // æ›´æ–°è®¡æ•°
    UpdateSoldierCount(OldCount);

    // æ›´æ–°ç¼–é˜Ÿç»„ä»¶
    if (FormationComponent)
    {
        FormationComponent->RegenerateFormation(Soldiers.Num());
        
        if (FormationComponent->GetFormationSlots().IsValidIndex(SlotIndex))
        {
            FormationComponent->OccupySlot(SlotIndex, Soldier->GetUniqueID());
        }
    }
}

void AXBCharacterBase::RemoveSoldier(AXBSoldierCharacter* Soldier)
{
    if (!Soldier)
    {
        return;
    }

    int32 OldCount = Soldiers.Num();
    int32 RemovedSlotIndex = Soldier->GetFormationSlotIndex();

    if (!Internal_RemoveSoldierFromArray(Soldier))
    {
        return;
    }

    UpdateSoldierCount(OldCount);

    if (FormationComponent)
    {
        FormationComponent->CompactSlots(Soldiers);
    }
}

void AXBCharacterBase::ReassignSoldierSlots(int32 StartIndex)
{
    for (int32 i = StartIndex; i < Soldiers.Num(); ++i)
    {
        if (Soldiers[i])
        {
            int32 OldSlot = Soldiers[i]->GetFormationSlotIndex();
            if (OldSlot != i)
            {
                Soldiers[i]->SetFormationSlotIndex(i);
            }
        }
    }
}

void AXBCharacterBase::OnSoldierDied(AXBSoldierCharacter* DeadSoldier)
{
    if (!DeadSoldier || bIsCleaningUpSoldiers)
    {
        return;
    }

    RemoveSoldier(DeadSoldier);
    ApplyGrowthOnSoldiersRemoved(1);
}

void AXBCharacterBase::ApplyGrowthOnSoldiersAdded(int32 SoldierCount)
{
    if (bIsDead || SoldierCount <= 0)
    {
        return;
    }

    UpdateLeaderScale();

    const float HealthBonus = SoldierCount * GrowthConfigCache.HealthPerSoldier;
    AddHealthWithOverflow(HealthBonus);

    UpdateDamageMultiplier();

    if (GrowthConfigCache.bEnableSkillEffectScaling)
    {
        UpdateSkillEffectScaling();
    }

    if (GrowthConfigCache.bEnableAttackRangeScaling)
    {
        UpdateAttackRangeScaling();
    }
}

void AXBCharacterBase::UpdateDamageMultiplier()
{
    if (!AbilitySystemComponent)
    {
        return;
    }

    const float BaseDamageMultiplier = CachedLeaderData.DamageMultiplier;
    const float AdditionalMultiplier = Soldiers.Num() * GrowthConfigCache.DamageMultiplierPerSoldier;
    
    const float NewMultiplier = FMath::Min(
        BaseDamageMultiplier + AdditionalMultiplier,
        GrowthConfigCache.MaxDamageMultiplier
    );

    AbilitySystemComponent->SetNumericAttributeBase(
        UXBAttributeSet::GetDamageMultiplierAttribute(),
        NewMultiplier
    );
}

float AXBCharacterBase::GetCurrentDamageMultiplier() const
{
    if (AbilitySystemComponent)
    {
        return AbilitySystemComponent->GetNumericAttribute(UXBAttributeSet::GetDamageMultiplierAttribute());
    }
    return CachedLeaderData.DamageMultiplier;
}

void AXBCharacterBase::ApplyGrowthOnSoldiersRemoved(int32 SoldierCount)
{
    if (SoldierCount <= 0)
    {
        return;
    }

    UpdateLeaderScale();
    UpdateDamageMultiplier();

    if (GrowthConfigCache.bEnableSkillEffectScaling)
    {
        UpdateSkillEffectScaling();
    }

    if (GrowthConfigCache.bEnableAttackRangeScaling)
    {
        UpdateAttackRangeScaling();
    }
}

float AXBCharacterBase::GetCurrentScale() const
{
    if (AbilitySystemComponent)
    {
        return AbilitySystemComponent->GetNumericAttribute(UXBAttributeSet::GetScaleAttribute());
    }
    return BaseScale;
}

float AXBCharacterBase::GetScaledAttackRange() const
{
    float CurrentScale = GetCurrentScale();
    return BaseAttackRange * CurrentScale * GrowthConfigCache.AttackRangeScaleMultiplier;
}

void AXBCharacterBase::OnCombatAttackStateChanged(bool bIsAttacking)
{
    if (!CombatComponent)
    {
        return;
    }

    bool bShouldBlock = CombatComponent->ShouldBlockMovement();
    
    if (UCharacterMovementComponent* MovementComp = GetCharacterMovement())
    {
        if (bShouldBlock)
        {
            MovementComp->DisableMovement();
        }
        else
        {
            MovementComp->SetMovementMode(MOVE_Walking);
        }
    }
}

void AXBCharacterBase::BindCombatEvents()
{
    if (CombatComponent)
    {
        CombatComponent->OnAttackStateChanged.AddDynamic(this, &AXBCharacterBase::OnCombatAttackStateChanged);
    }
}

void AXBCharacterBase::UpdateLeaderScale()
{
    const float AdditionalScale = Soldiers.Num() * GrowthConfigCache.ScalePerSoldier;
    const float NewScale = FMath::Min(BaseScale + AdditionalScale, GrowthConfigCache.MaxScale);

    SetActorScale3D(FVector(NewScale));

    if (AbilitySystemComponent)
    {
        AbilitySystemComponent->SetNumericAttributeBase(UXBAttributeSet::GetScaleAttribute(), NewScale);
    }

    if (CombatComponent && GrowthConfigCache.bEnableAttackRangeScaling)
    {
        float RangeScale = NewScale * GrowthConfigCache.AttackRangeScaleMultiplier;
        CombatComponent->SetAttackRangeScale(RangeScale);
    }
}

void AXBCharacterBase::AddHealthWithOverflow(float HealthToAdd)
{
    if (!AbilitySystemComponent)
    {
        return;
    }

    float CurrentHealth = AbilitySystemComponent->GetNumericAttribute(UXBAttributeSet::GetHealthAttribute());
    float CurrentMaxHealth = AbilitySystemComponent->GetNumericAttribute(UXBAttributeSet::GetMaxHealthAttribute());

    float NewHealth = CurrentHealth + HealthToAdd;

    if (NewHealth > CurrentMaxHealth)
    {
        AbilitySystemComponent->SetNumericAttributeBase(UXBAttributeSet::GetMaxHealthAttribute(), NewHealth);
        AbilitySystemComponent->SetNumericAttributeBase(UXBAttributeSet::GetHealthAttribute(), NewHealth);
    }
    else
    {
        AbilitySystemComponent->SetNumericAttributeBase(UXBAttributeSet::GetHealthAttribute(), NewHealth);
    }
}

void AXBCharacterBase::UpdateSkillEffectScaling()
{
    if (!AbilitySystemComponent)
    {
        return;
    }

    float CurrentScale = GetCurrentScale();
    float EffectScale = CurrentScale * GrowthConfigCache.SkillEffectScaleMultiplier;

    TArray<UActorComponent*> Components;
    GetComponents(UParticleSystemComponent::StaticClass(), Components);

    for (UActorComponent* Comp : Components)
    {
        if (UParticleSystemComponent* PSC = Cast<UParticleSystemComponent>(Comp))
        {
            if (PSC->ComponentHasTag(FName("SkillEffect")))
            {
                PSC->SetWorldScale3D(FVector(EffectScale));
            }
        }
    }
}

void AXBCharacterBase::UpdateAttackRangeScaling()
{
    if (!CombatComponent)
    {
        return;
    }

    float CurrentScale = GetCurrentScale();
    float ScaledRange = BaseAttackRange * CurrentScale * GrowthConfigCache.AttackRangeScaleMultiplier;
}

// ==================== æˆ˜æ–—çŠ¶æ€ç³»ç»Ÿå®ç° ====================

void AXBCharacterBase::EnterCombat()
{
    if (bIsDead)
    {
        return;
    }

    if (bIsInCombat)
    {
        GetWorldTimerManager().ClearTimer(CombatTimeoutHandle);
        GetWorldTimerManager().SetTimer(
            CombatTimeoutHandle,
            this,
            &AXBCharacterBase::OnCombatTimeout,
            CombatTimeoutDuration,
            false
        );
        return;
    }

    bIsInCombat = true;

    if (UWorld* World = GetWorld())
    {
        if (UXBSoldierPerceptionSubsystem* Perception = World->GetSubsystem<UXBSoldierPerceptionSubsystem>())
        {
            Perception->MarkHotspotRegion(GetActorLocation(), 1500.0f);
        }
    }

    for (AXBSoldierCharacter* Soldier : Soldiers)
    {
        if (Soldier && Soldier->GetSoldierState() != EXBSoldierState::Dead)
        {
            Soldier->EnterCombat();
        }
    }

    GetWorldTimerManager().SetTimer(
        CombatTimeoutHandle,
        this,
        &AXBCharacterBase::OnCombatTimeout,
        CombatTimeoutDuration,
        false
    );

    OnCombatStateChanged.Broadcast(true);
}

void AXBCharacterBase::ExitCombat()
{
    if (!bIsInCombat)
    {
        return;
    }

    bIsInCombat = false;

    GetWorldTimerManager().ClearTimer(CombatTimeoutHandle);

    if (UWorld* World = GetWorld())
    {
        if (UXBSoldierPerceptionSubsystem* Perception = World->GetSubsystem<UXBSoldierPerceptionSubsystem>())
        {
            Perception->ClearHotspotRegion(GetActorLocation());
        }
    }

    for (AXBSoldierCharacter* Soldier : Soldiers)
    {
        if (Soldier && Soldier->GetSoldierState() != EXBSoldierState::Dead)
        {
            Soldier->ExitCombat();
        }
    }

    OnCombatStateChanged.Broadcast(false);
}

void AXBCharacterBase::DisengageFromCombat()
{
    float CurrentTime = GetWorld()->GetTimeSeconds();
    if (CurrentTime - LastDisengageTime < DisengageCooldown)
    {
        return;
    }

    LastDisengageTime = CurrentTime;

    ExitCombat();
    RecallAllSoldiers();

    if (bSprintWhenDisengaging)
    {
        StartSprint();

        GetWorldTimerManager().ClearTimer(DisengageSprintTimerHandle);
        GetWorldTimerManager().SetTimer(
            DisengageSprintTimerHandle,
            this,
            &AXBCharacterBase::StopSprint,
            DisengageSprintDuration,
            false
        );
    }

    SetSoldiersEscaping(true);

    FTimerHandle TempHandle;
    GetWorldTimerManager().SetTimer(
        TempHandle,
        [this]()
        {
            SetSoldiersEscaping(false);
        },
        DisengageSprintDuration,
        false
    );
}

void AXBCharacterBase::OnCombatTimeout()
{
    ExitCombat();
}

/**
 * @brief ??????????
 * @param HitTarget ?????
 * @return ?
 * @note ????: ????????????/???????????
 * @note ????: ???? -> ???? -> ????/?? -> ???? -> ????????
 * @note ????: ???????????????
 */
void AXBCharacterBase::OnAttackHit(AActor* HitTarget)
{
    // ?? ?? - ???????
    if (!HitTarget)
    {
        return;
    }

    // ?? ?? - ?????????
    EnterCombat();

    // ?? ?? - ?????????
    AXBCharacterBase* TargetLeader = Cast<AXBCharacterBase>(HitTarget);
    if (TargetLeader && IsHostileTo(TargetLeader))
    {
        // ?? ?? - ????????????
        LastAttackedEnemyLeader = TargetLeader;
        // ?? ?? - ????????????
        bHasLastAttackedEnemyFaction = true;
        LastAttackedEnemyFaction = TargetLeader->GetFaction();
        // ?? ?? - ??????????
        TargetLeader->EnterCombat();

        UE_LOG(LogXBCombat, Log, TEXT("?? %s ?????? %s??????????????"),
            *GetName(), *TargetLeader->GetName());
        return;
    }

    // ?? ?? - ???????????
    AXBSoldierCharacter* TargetSoldier = Cast<AXBSoldierCharacter>(HitTarget);
    if (TargetSoldier && UXBBlueprintFunctionLibrary::AreFactionsHostile(Faction, TargetSoldier->GetFaction()))
    {
        // ?? ?? - ????????????
        bHasLastAttackedEnemyFaction = true;
        LastAttackedEnemyFaction = TargetSoldier->GetFaction();

        UE_LOG(LogXBCombat, Log, TEXT("?? %s ?????? %s?????????????"),
            *GetName(), *TargetSoldier->GetName());
    }
}

void AXBCharacterBase::RecallAllSoldiers()

{
    ExitCombat();

    for (AXBSoldierCharacter* Soldier : Soldiers)
    {
        if (Soldier && Soldier->GetSoldierState() != EXBSoldierState::Dead)
        {
            // ğŸ”§ ä¿®æ”¹ - å¬å›æ—¶åˆ‡æ¢ä¸ºè·ŸéšçŠ¶æ€å¹¶å…³é—­è¡Œä¸ºæ ‘
            Soldier->SetSoldierState(EXBSoldierState::Following);
            Soldier->CurrentAttackTarget = nullptr;

            if (AXBSoldierAIController* SoldierAI = Cast<AXBSoldierAIController>(Soldier->GetController()))
            {
                SoldierAI->StopBehaviorTreeLogic();
                SoldierAI->StopMovement();
            }
            else if (AAIController* AICtrl = Cast<AAIController>(Soldier->GetController()))
            {
                AICtrl->StopMovement();
            }
        }
    }
}

void AXBCharacterBase::SetSoldiersEscaping(bool bEscaping)
{
    for (AXBSoldierCharacter* Soldier : Soldiers)
    {
        if (Soldier)
        {
            Soldier->SetEscaping(bEscaping);
        }
    }
}

// ==================== æ­»äº¡ç³»ç»Ÿå®ç° ====================

void AXBCharacterBase::HandleDeath()
{
    if (bIsDead)
    {
        return;
    }

    bIsDead = true;

    UE_LOG(LogXBCharacter, Log, TEXT("%s: è§’è‰²æ­»äº¡"), *GetName());

    if (MagnetFieldComponent)
    {
        MagnetFieldComponent->SetFieldEnabled(false);
    }

    if (HealthBarComponent)
    {
        HealthBarComponent->SetHealthBarVisible(false);
        HealthBarComponent->SetComponentTickEnabled(false);
    }

    OnCharacterDeath.Broadcast(this);

    // âœ¨ æ ¸å¿ƒ - å…ˆç”Ÿæˆæ‰è½å£«å…µï¼ˆä½¿ç”¨å‡»æ€è€…é…ç½®ï¼Œè½åœ°è‡ªåŠ¨å…¥åˆ—ï¼‰
    SpawnDroppedSoldiers();

    if (UCharacterMovementComponent* MovementComp = GetCharacterMovement())
    {
        MovementComp->DisableMovement();
        MovementComp->StopMovementImmediately();
    }

    if (UCapsuleComponent* Capsule = GetCapsuleComponent())
    {
        Capsule->SetCollisionEnabled(ECollisionEnabled::NoCollision);
    }

    // ğŸ”§ ä¿®æ”¹ - æ­»äº¡åç¼©å°ä½“å‹ï¼ˆç”¨äºå°¸ä½“è¡¨ç°ä¸è·¯å¾„é€šè¡Œï¼‰
    SetActorScale3D(FVector(DeathScale));
    UE_LOG(LogXBCharacter, Log, TEXT("%s: æ­»äº¡åç¼©æ”¾ä¸º %.2f"), *GetName(), DeathScale);

    if (AbilitySystemComponent)
    {
        AbilitySystemComponent->CancelAllAbilities();
    }

    ExitCombat();

    if (bIsSprinting)
    {
        StopSprint();
    }

    KillAllSoldiers();

    bool bMontageStarted = false;
    if (DeathMontage)
    {
        if (USkeletalMeshComponent* MeshComp = GetMesh())
        {
            if (UAnimInstance* AnimInstance = MeshComp->GetAnimInstance())
            {
                AnimInstance->StopAllMontages(0.2f);

                float Duration = AnimInstance->Montage_Play(DeathMontage, 1.0f);
                if (Duration > 0.0f)
                {
                    bMontageStarted = true;

                    FOnMontageEnded EndDelegate;
                    EndDelegate.BindUObject(this, &AXBCharacterBase::OnDeathMontageEnded);
                    AnimInstance->Montage_SetEndDelegate(EndDelegate, DeathMontage);

                    if (!bDelayAfterMontage)
                    {
                        GetWorldTimerManager().SetTimer(
                            DeathDestroyTimerHandle,
                            this,
                            &AXBCharacterBase::OnDestroyTimerExpired,
                            DeathDestroyDelay,
                            false
                        );
                    }
                }
            }
        }
    }

    if (!bMontageStarted)
    {
        GetWorldTimerManager().SetTimer(
            DeathDestroyTimerHandle,
            this,
            &AXBCharacterBase::OnDestroyTimerExpired,
            DeathDestroyDelay,
            false
        );
    }
}

/**
 * @brief ç”Ÿæˆæ‰è½çš„å£«å…µï¼ˆæŠ›ç‰©çº¿é£è¡Œ + è½åœ°è‡ªåŠ¨å…¥åˆ—ï¼‰
 * @note ğŸ”§ é‡æ„ - æ ¸å¿ƒä¿®æ”¹ç‚¹:
 *       1. ä½¿ç”¨ FullInitialize å®Œæ•´åˆå§‹åŒ–å£«å…µï¼ˆæ•°æ®+ç»„ä»¶+è§†è§‰ï¼‰
 *       2. ä¼ å…¥ç›®æ ‡å°†é¢†ï¼Œè½åœ°åè‡ªåŠ¨å…¥åˆ—
 *       3. è®¾ç½®å£«å…µé˜µè¥ä¸ç›®æ ‡å°†é¢†ä¸€è‡´
 */
void AXBCharacterBase::SpawnDroppedSoldiers()
{
    if (SoldierDropConfig.DropCount <= 0)
    {
        return;
    }

    UWorld* World = GetWorld();
    if (!World)
    {
        return;
    }

    // è·å–å‡»æ€è€…ä½œä¸ºç›®æ ‡å°†é¢†
    AXBCharacterBase* TargetLeader = nullptr;
    UDataTable* DropSoldierDataTable = nullptr;
    FName DropSoldierRowName = NAME_None;
    TSubclassOf<AXBSoldierCharacter> DropSoldierClass = SoldierDropConfig.DropSoldierClass;
    EXBFaction DropFaction = EXBFaction::Neutral;

    if (LastDamageInstigator.IsValid())
    {
        TargetLeader = Cast<AXBCharacterBase>(LastDamageInstigator.Get());
        
        if (TargetLeader && !TargetLeader->IsDead())
        {
            DropSoldierDataTable = TargetLeader->GetSoldierDataTable();
            DropSoldierRowName = TargetLeader->GetRecruitSoldierRowName();
            DropFaction = TargetLeader->GetFaction();
            
            if (TargetLeader->GetSoldierActorClass())
            {
                DropSoldierClass = TargetLeader->GetSoldierActorClass();
            }
            
            UE_LOG(LogXBCharacter, Log, TEXT("æ‰è½å£«å…µå°†è‡ªåŠ¨å…¥åˆ—åˆ°å‡»æ€è€… %s"), *TargetLeader->GetName());
        }
        else
        {
            TargetLeader = nullptr;
        }
    }

    // å›é€€é€»è¾‘
    if (!DropSoldierDataTable || DropSoldierRowName.IsNone())
    {
        DropSoldierDataTable = SoldierDataTable;
        DropSoldierRowName = RecruitSoldierRowName;
        DropFaction = EXBFaction::Neutral;
    }

    if (!DropSoldierClass)
    {
        DropSoldierClass = SoldierActorClass;
    }

    if (!DropSoldierClass)
    {
        UE_LOG(LogXBCharacter, Error, TEXT("æ‰è½å£«å…µå¤±è´¥: æœªé…ç½®å£«å…µç±»"));
        return;
    }

    FVector SpawnOrigin = GetActorLocation();
    const FXBDropArcConfig& ArcConfig = SoldierDropConfig.ArcConfig;

    UXBSoldierPoolSubsystem* PoolSubsystem = World->GetSubsystem<UXBSoldierPoolSubsystem>();

    // ğŸ”§ ä¿®æ”¹ - ä½¿ç”¨å£«å…µèƒ¶å›ŠåŠé«˜å‚ä¸è½ç‚¹æ ¡æ­£ï¼Œé¿å…æ‚¬ç©º
    float DropCapsuleHalfHeight = 88.0f;
    if (DropSoldierClass)
    {
        const AXBSoldierCharacter* SoldierCDO = DropSoldierClass->GetDefaultObject<AXBSoldierCharacter>();
        if (SoldierCDO && SoldierCDO->GetCapsuleComponent())
        {
            DropCapsuleHalfHeight = SoldierCDO->GetCapsuleComponent()->GetScaledCapsuleHalfHeight();
        }
    }

    UE_LOG(LogXBCharacter, Log, TEXT("å°†é¢† %s æ­»äº¡ï¼Œç”Ÿæˆ %d ä¸ªæ‰è½å£«å…µï¼Œç›®æ ‡å°†é¢†: %s"),
        *GetName(), 
        SoldierDropConfig.DropCount,
        TargetLeader ? *TargetLeader->GetName() : TEXT("æ— "));

    for (int32 i = 0; i < SoldierDropConfig.DropCount; ++i)
    {
        // è®¡ç®—æŠ›ç‰©çº¿ç»ˆç‚¹ä½ç½®
        float BaseAngle = (360.0f / SoldierDropConfig.DropCount) * i;
        float RandomAngleOffset = FMath::RandRange(-20.0f, 20.0f);
        float Angle = BaseAngle + RandomAngleOffset;

        float Distance = FMath::RandRange(ArcConfig.MinDropDistance, ArcConfig.MaxDropDistance);

        FVector Direction = FRotator(0.0f, Angle, 0.0f).RotateVector(FVector::ForwardVector);
        FVector TargetLocation = SpawnOrigin + Direction * Distance;

        // åœ°é¢æ£€æµ‹
        FHitResult HitResult;
        FVector TraceStart = FVector(TargetLocation.X, TargetLocation.Y, SpawnOrigin.Z + ArcConfig.GroundTraceUpDistance);
        FVector TraceEnd = FVector(TargetLocation.X, TargetLocation.Y, SpawnOrigin.Z - ArcConfig.GroundTraceDownDistance);

        FCollisionQueryParams QueryParams;
        QueryParams.AddIgnoredActor(this);

        bool bHit = World->LineTraceSingleByChannel(
            HitResult,
            TraceStart,
            TraceEnd,
            ECC_WorldStatic,
            QueryParams
        );

        if (bHit)
        {
            // âœ¨ æ–°å¢ - è½åœ°ä½ç½®åŠ ä¸ŠåŠé«˜ï¼Œç¡®ä¿èƒ¶å›Šä½“åº•éƒ¨è§¦åœ°
            TargetLocation = HitResult.Location + FVector(0.0f, 0.0f, DropCapsuleHalfHeight + ArcConfig.LandingExtraZOffset);
        }
        else
        {
            TargetLocation.Z = SpawnOrigin.Z + ArcConfig.LandingExtraZOffset;
        }

        AXBSoldierCharacter* DroppedSoldier = nullptr;

        // å°è¯•ä»å¯¹è±¡æ± è·å–
        if (PoolSubsystem && PoolSubsystem->HasAvailableSoldier())
        {
            DroppedSoldier = PoolSubsystem->AcquireSoldier(SpawnOrigin, FRotator::ZeroRotator);
        }

        // æ± ä¸­æ²¡æœ‰åˆ™ç”Ÿæˆæ–°çš„
        if (!DroppedSoldier)
        {
            FActorSpawnParameters SpawnParams;
            SpawnParams.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AlwaysSpawn;
            // âœ¨ æ–°å¢ - å»¶è¿Ÿ BeginPlayï¼Œé¿å…åœ¨é…ç½®å®Œæˆå‰è§¦å‘
            SpawnParams.bDeferConstruction = true;

            DroppedSoldier = World->SpawnActor<AXBSoldierCharacter>(
                DropSoldierClass,
                SpawnOrigin,
                FRotator::ZeroRotator,
                SpawnParams
            );
            
            if (DroppedSoldier)
            {
                DroppedSoldier->MarkAsPooledSoldier();
                
                // âœ¨ æ–°å¢ - åœ¨ BeginPlay å‰ç¦ç”¨ç¢°æ’ï¼Œé¿å…è§¦å‘ç£åœº
                if (UCapsuleComponent* Capsule = DroppedSoldier->GetCapsuleComponent())
                {
                    Capsule->SetCollisionEnabled(ECollisionEnabled::NoCollision);
                }
                
                // å®Œæˆæ„é€ ï¼ˆè§¦å‘ BeginPlayï¼‰
                DroppedSoldier->FinishSpawning(FTransform(FRotator::ZeroRotator, SpawnOrigin));
            }
        }

        if (DroppedSoldier)
        {
            // âœ¨ æ–°å¢ - ç¡®ä¿ç¢°æ’ç¦ç”¨ï¼ˆå¯¹è±¡æ± è·å–çš„å£«å…µä¹Ÿéœ€è¦ï¼‰
            if (UCapsuleComponent* Capsule = DroppedSoldier->GetCapsuleComponent())
            {
                Capsule->SetCollisionEnabled(ECollisionEnabled::NoCollision);
            }
            
            // å®Œæ•´åˆå§‹åŒ–ï¼ˆä¸ä¼šè§¦å‘ç£åœºï¼Œå› ä¸ºç¢°æ’å·²ç¦ç”¨ï¼‰
            if (DropSoldierDataTable && !DropSoldierRowName.IsNone())
            {
                DroppedSoldier->FullInitialize(DropSoldierDataTable, DropSoldierRowName, DropFaction);
            }
            
            // å¯åŠ¨æŠ›ç‰©çº¿é£è¡Œ
            DroppedSoldier->StartDropFlight(SpawnOrigin, TargetLocation, ArcConfig, TargetLeader);
            
            UE_LOG(LogXBCharacter, Log, TEXT("æ‰è½å£«å…µ [%d] %s å¼€å§‹é£è¡Œ"),
                i, *DroppedSoldier->GetName());
        }
    }
}

void AXBCharacterBase::OnDeathMontageEnded(UAnimMontage* Montage, bool bInterrupted)
{
    if (bDelayAfterMontage)
    {
        GetWorldTimerManager().SetTimer(
            DeathDestroyTimerHandle,
            this,
            &AXBCharacterBase::OnDestroyTimerExpired,
            DeathDestroyDelay,
            false
        );
    }
}

void AXBCharacterBase::OnDestroyTimerExpired()
{
    PreDestroyCleanup();
    Destroy();
}

void AXBCharacterBase::KillAllSoldiers()
{
    bIsCleaningUpSoldiers = true;

    UE_LOG(LogXBSoldier, Log, TEXT("å°†é¢† %s æ­»äº¡ï¼Œå¼€å§‹å¤„ç† %d ä¸ªå£«å…µçš„æ­»äº¡"), 
        *GetName(), Soldiers.Num());

    for (AXBSoldierCharacter* Soldier : Soldiers)
    {
        if (Soldier && IsValid(Soldier))
        {
            if (Soldier->GetSoldierState() != EXBSoldierState::Dead)
            {
                Soldier->TakeSoldierDamage(Soldier->GetCurrentHealth() + 100.0f, this);
            }
        }
    }

    Soldiers.Empty();

    bIsCleaningUpSoldiers = false;
}

void AXBCharacterBase::PreDestroyCleanup()
{
    GetWorldTimerManager().ClearTimer(CombatTimeoutHandle);

    Soldiers.Empty();

    if (AbilitySystemComponent)
    {
        AbilitySystemComponent->CancelAllAbilities();
        AbilitySystemComponent->RemoveAllGameplayCues();
        AbilitySystemComponent->RemoveActiveEffectsWithTags(FGameplayTagContainer());
    }

    GetWorldTimerManager().ClearTimer(DeathDestroyTimerHandle);
}
